package lissa.be;
// Generated 23-sep-2016 12:43:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AlmacenProducto generated by hbm2java
 */
public class AlmacenProducto  implements java.io.Serializable {


     private int idalmacenproducto;
     private Almacen almacen;
     private Producto producto;
     private Integer stockActual;
     private Date fechaRegistro;
     private Date fechaUltAct;
     private boolean estado;
     private String lote;
     private Date fechaVencimiento;
     private BigDecimal precioMin;
     private BigDecimal precioMax;
     private BigDecimal precioVenta;
     private int utilidadMax;
     private int utilidadMin;
     
    public AlmacenProducto() {
    }

	
    public AlmacenProducto(int idalmacenproducto, Almacen almacen, Producto producto, Date fechaRegistro, boolean estado) {
        this.idalmacenproducto = idalmacenproducto;
        this.almacen = almacen;
        this.producto = producto;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
    }
    public AlmacenProducto(int idalmacenproducto, Almacen almacen, Producto producto, Integer stockActual, Date fechaRegistro, Date fechaUltAct, boolean estado) {
       this.idalmacenproducto = idalmacenproducto;
       this.almacen = almacen;
       this.producto = producto;
       this.stockActual = stockActual;
       this.fechaRegistro = fechaRegistro;
       this.fechaUltAct = fechaUltAct;
       this.estado = estado;
    }
   
    public int getIdalmacenproducto() {
        return this.idalmacenproducto;
    }
    
    public void setIdalmacenproducto(int idalmacenproducto) {
        this.idalmacenproducto = idalmacenproducto;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(Integer stockActual) {
        this.stockActual = stockActual;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaUltAct() {
        return this.fechaUltAct;
    }
    
    public void setFechaUltAct(Date fechaUltAct) {
        this.fechaUltAct = fechaUltAct;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public String getLote() {
        return lote;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    public BigDecimal getPrecioMin() {
        return precioMin;
    }

    public void setPrecioMin(BigDecimal precioMin) {
        this.precioMin = precioMin;
    }

    public BigDecimal getPrecioMax() {
        return precioMax;
    }

    public void setPrecioMax(BigDecimal precioMax) {
        this.precioMax = precioMax;
    }

    public BigDecimal getPrecioVenta() {
        return precioVenta;
    }

    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }

    public int getUtilidadMax() {
        return utilidadMax;
    }

    public void setUtilidadMax(int utilidadMax) {
        this.utilidadMax = utilidadMax;
    }

    public int getUtilidadMin() {
        return utilidadMin;
    }

    public void setUtilidadMin(int utilidadMin) {
        this.utilidadMin = utilidadMin;
    }




}


