package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * Anamnesis generated by hbm2java
 */
public class Anamnesis  implements java.io.Serializable {


     private int idanamnesis;
     private Atencion atencion;
     private String anamnesis;
     private String motivoConsulta;
     private String examenClinicoDirigido;
     private Boolean estado;

    public Anamnesis() {
    }

	
    public Anamnesis(int idanamnesis) {
        this.idanamnesis = idanamnesis;
    }
    public Anamnesis(int idanamnesis, Atencion atencion, String anamnesis, String motivoConsulta, String examenClinicoDirigido, Boolean estado) {
       this.idanamnesis = idanamnesis;
       this.atencion = atencion;
       this.anamnesis = anamnesis;
       this.motivoConsulta = motivoConsulta;
       this.examenClinicoDirigido = examenClinicoDirigido;
       this.estado = estado;
    }
   
    public int getIdanamnesis() {
        return this.idanamnesis;
    }
    
    public void setIdanamnesis(int idanamnesis) {
        this.idanamnesis = idanamnesis;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public String getAnamnesis() {
        return this.anamnesis;
    }
    
    public void setAnamnesis(String anamnesis) {
        this.anamnesis = anamnesis;
    }
    public String getMotivoConsulta() {
        return this.motivoConsulta;
    }
    
    public void setMotivoConsulta(String motivoConsulta) {
        this.motivoConsulta = motivoConsulta;
    }
    public String getExamenClinicoDirigido() {
        return this.examenClinicoDirigido;
    }
    
    public void setExamenClinicoDirigido(String examenClinicoDirigido) {
        this.examenClinicoDirigido = examenClinicoDirigido;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


