package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * Antecedente generated by hbm2java
 */
public class Antecedente  implements java.io.Serializable {


     private int idantecedente;
     private Atencion atencion;
     private String antPersonales;
     private String antFamiliares;

    public Antecedente() {
    }

	
    public Antecedente(int idantecedente) {
        this.idantecedente = idantecedente;
    }
    public Antecedente(int idantecedente, Atencion atencion, String antPersonales, String antFamiliares) {
       this.idantecedente = idantecedente;
       this.atencion = atencion;
       this.antPersonales = antPersonales;
       this.antFamiliares = antFamiliares;
    }
   
    public int getIdantecedente() {
        return this.idantecedente;
    }
    
    public void setIdantecedente(int idantecedente) {
        this.idantecedente = idantecedente;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public String getAntPersonales() {
        return this.antPersonales;
    }
    
    public void setAntPersonales(String antPersonales) {
        this.antPersonales = antPersonales;
    }
    public String getAntFamiliares() {
        return this.antFamiliares;
    }
    
    public void setAntFamiliares(String antFamiliares) {
        this.antFamiliares = antFamiliares;
    }




}


