package lissa.be;
// Generated 05/07/2018 12:13:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AtencionOcupacional generated by hbm2java
 */
public class AtencionOcupacional  implements java.io.Serializable {


     private int idatencionocupacional;
     private PersonaJuridica personaJuridica;
     private EvaluacionOcupacional evaluacionOcupacional;
     private HistoriaClinica historiaClinica;
     private PuestoLaboral puestoLaboral;
     private Date fechaExamen;
     private Date fechaEmision;
     private Integer edadIngreso;
     private Date fechaReg;
     private Set<CertMedicoOcupacional> certMedicoOcupacionals = new HashSet<CertMedicoOcupacional>(0);
     private Set<CertMedicoOcupacional2> certMedicoOcupacional2s = new HashSet<CertMedicoOcupacional2>(0);

    public AtencionOcupacional() {
    }


    public int getIdatencionocupacional() {
        return this.idatencionocupacional;
    }
    
    public void setIdatencionocupacional(int idatencionocupacional) {
        this.idatencionocupacional = idatencionocupacional;
    }
    public EvaluacionOcupacional getEvaluacionOcupacional() {
        return this.evaluacionOcupacional;
    }
    
    public void setEvaluacionOcupacional(EvaluacionOcupacional evaluacionOcupacional) {
        this.evaluacionOcupacional = evaluacionOcupacional;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public PuestoLaboral getPuestoLaboral() {
        return this.puestoLaboral;
    }
    
    public void setPuestoLaboral(PuestoLaboral puestoLaboral) {
        this.puestoLaboral = puestoLaboral;
    }
    public Date getFechaExamen() {
        return this.fechaExamen;
    }
    
    public void setFechaExamen(Date fechaExamen) {
        this.fechaExamen = fechaExamen;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Integer getEdadIngreso() {
        return this.edadIngreso;
    }
    
    public void setEdadIngreso(Integer edadIngreso) {
        this.edadIngreso = edadIngreso;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    /**
     * @return the personaJuridica
     */
    public PersonaJuridica getPersonaJuridica() {
        return personaJuridica;
    }

    /**
     * @param personaJuridica the personaJuridica to set
     */
    public void setPersonaJuridica(PersonaJuridica personaJuridica) {
        this.personaJuridica = personaJuridica;
    }

    public Set<CertMedicoOcupacional> getCertMedicoOcupacionals() {
        return certMedicoOcupacionals;
    }

    public void setCertMedicoOcupacionals(Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public Set<CertMedicoOcupacional2> getCertMedicoOcupacional2s() {
        return certMedicoOcupacional2s;
    }

    public void setCertMedicoOcupacional2s(Set<CertMedicoOcupacional2> certMedicoOcupacional2s) {
        this.certMedicoOcupacional2s = certMedicoOcupacional2s;
    }




}


