package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * CertMedicoOcupacional generated by hbm2java
 */
public class CertMedicoOcupacional implements java.io.Serializable {

    private long idcertmedicoocupacional;
    private AtencionOcupacional atencionOcupacional;
    private Condicion condicion;
    private Long idMedico;
    private Set<CmoRecomendaciones> cmoRecomendacioneses = new HashSet<CmoRecomendaciones>(0);
    private Set<CmoObservaciones> cmoObservacioneses = new HashSet<CmoObservaciones>(0);
    private Set<FmoRestricciones> fmoRestriccioneses = new HashSet<FmoRestricciones>(0);
    private Set<CmoCie10> cmoCie10s = new HashSet<CmoCie10>(0);

    public CertMedicoOcupacional() {
    }

    public long getIdcertmedicoocupacional() {
        return this.idcertmedicoocupacional;
    }

    public void setIdcertmedicoocupacional(long idcertmedicoocupacional) {
        this.idcertmedicoocupacional = idcertmedicoocupacional;
    }

    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }

    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }

    public Condicion getCondicion() {
        return this.condicion;
    }

    public void setCondicion(Condicion condicion) {
        this.condicion = condicion;
    }

    public Long getIdMedico() {
        return idMedico;
    }

    public void setIdMedico(Long idMedico) {
        this.idMedico = idMedico;
    }

    public Set<CmoRecomendaciones> getCmoRecomendacioneses() {
        return cmoRecomendacioneses;
    }

    public void setCmoRecomendacioneses(Set<CmoRecomendaciones> cmoRecomendacioneses) {
        this.cmoRecomendacioneses = cmoRecomendacioneses;
    }

    public Set<CmoObservaciones> getCmoObservacioneses() {
        return cmoObservacioneses;
    }

    public void setCmoObservacioneses(Set<CmoObservaciones> cmoObservacioneses) {
        this.cmoObservacioneses = cmoObservacioneses;
    }

    public Set<FmoRestricciones> getFmoRestriccioneses() {
        return fmoRestriccioneses;
    }

    public void setFmoRestriccioneses(Set<FmoRestricciones> fmoRestriccioneses) {
        this.fmoRestriccioneses = fmoRestriccioneses;
    }

    public Set<CmoCie10> getCmoCie10s() {
        return cmoCie10s;
    }

    public void setCmoCie10s(Set<CmoCie10> cmoCie10s) {
        this.cmoCie10s = cmoCie10s;
    }

}
