package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CertificadoMedicoOcupacional generated by hbm2java
 */
public class CertificadoMedicoOcupacional  implements java.io.Serializable {


     private int idcertificadomedicoocupacional;
     private AtencionOcupacional atencionOcupacional;
     private int idUsuario;
     private String condicion;
     private String restricciones;
     private String observaciones;
     private Date fecha;

    public CertificadoMedicoOcupacional() {
    }

	
    public CertificadoMedicoOcupacional(int idcertificadomedicoocupacional, AtencionOcupacional atencionOcupacional, int idUsuario, String condicion, String restricciones, Date fecha) {
        this.idcertificadomedicoocupacional = idcertificadomedicoocupacional;
        this.atencionOcupacional = atencionOcupacional;
        this.idUsuario = idUsuario;
        this.condicion = condicion;
        this.restricciones = restricciones;
        this.fecha = fecha;
    }
    public CertificadoMedicoOcupacional(int idcertificadomedicoocupacional, AtencionOcupacional atencionOcupacional, int idUsuario, String condicion, String restricciones, String observaciones, Date fecha) {
       this.idcertificadomedicoocupacional = idcertificadomedicoocupacional;
       this.atencionOcupacional = atencionOcupacional;
       this.idUsuario = idUsuario;
       this.condicion = condicion;
       this.restricciones = restricciones;
       this.observaciones = observaciones;
       this.fecha = fecha;
    }
   
    public int getIdcertificadomedicoocupacional() {
        return this.idcertificadomedicoocupacional;
    }
    
    public void setIdcertificadomedicoocupacional(int idcertificadomedicoocupacional) {
        this.idcertificadomedicoocupacional = idcertificadomedicoocupacional;
    }
    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }
    
    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getRestricciones() {
        return this.restricciones;
    }
    
    public void setRestricciones(String restricciones) {
        this.restricciones = restricciones;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


