package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1



/**
 * Cie10 generated by hbm2java
 */
public class Cie10  implements java.io.Serializable {


     private long idcie10;
     private ExamenOcupacional examenOcupacional;
     private String codigo;
     private String descripcion;

    public Cie10() {
    }

	
    public Cie10(int idCie10, String codigo) {
        this.idcie10 = idCie10;
        this.codigo = codigo;
    }
    public Cie10(int idCie10, ExamenOcupacional examenOcupacional, String codigo, String descripcion) {
       this.idcie10 = idCie10;
       this.examenOcupacional = examenOcupacional;
       this.codigo = codigo;
       this.descripcion = descripcion;
    }
   
    public long getIdcie10() {
        return this.idcie10;
    }
    
    public void setIdcie10(long idcie10) {
        this.idcie10 = idcie10;
    }
    public ExamenOcupacional getExamenOcupacional() {
        return this.examenOcupacional;
    }
    
    public void setExamenOcupacional(ExamenOcupacional examenOcupacional) {
        this.examenOcupacional = examenOcupacional;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


