package lissa.be;
// Generated 12/07/2018 05:03:55 PM by Hibernate Tools 4.3.1



/**
 * CmoObservaciones generated by hbm2java
 */
public class CmoObservaciones  implements java.io.Serializable {


     private long idcmoobservaciones;
     private CertMedicoOcupacional certMedicoOcupacional;
     private long idObservacion;

    public CmoObservaciones() {
    }

    public CmoObservaciones(long idcmoobservaciones, CertMedicoOcupacional certMedicoOcupacional, long idObservacion) {
       this.idcmoobservaciones = idcmoobservaciones;
       this.certMedicoOcupacional = certMedicoOcupacional;
       this.idObservacion = idObservacion;
    }
   
    public long getIdcmoobservaciones() {
        return this.idcmoobservaciones;
    }
    
    public void setIdcmoobservaciones(long idcmoobservaciones) {
        this.idcmoobservaciones = idcmoobservaciones;
    }
    public CertMedicoOcupacional getCertMedicoOcupacional() {
        return this.certMedicoOcupacional;
    }
    
    public void setCertMedicoOcupacional(CertMedicoOcupacional certMedicoOcupacional) {
        this.certMedicoOcupacional = certMedicoOcupacional;
    }
    public long getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(long idObservacion) {
        this.idObservacion = idObservacion;
    }




}


