package lissa.be;
// Generated 14/07/2018 08:27:00 AM by Hibernate Tools 4.3.1



/**
 * CmoObservaciones2 generated by hbm2java
 */
public class CmoObservaciones2  implements java.io.Serializable {


     private long idcmoobservaciones;
     private CertMedicoOcupacional2 certMedicoOcupacional2;
     private long idObservacion;

    public CmoObservaciones2() {
    }

    public CmoObservaciones2(long idcmoobservaciones, CertMedicoOcupacional2 certMedicoOcupacional2, long idObservacion) {
       this.idcmoobservaciones = idcmoobservaciones;
       this.certMedicoOcupacional2 = certMedicoOcupacional2;
       this.idObservacion = idObservacion;
    }
   
    public long getIdcmoobservaciones() {
        return this.idcmoobservaciones;
    }
    
    public void setIdcmoobservaciones(long idcmoobservaciones) {
        this.idcmoobservaciones = idcmoobservaciones;
    }
    public CertMedicoOcupacional2 getCertMedicoOcupacional2() {
        return this.certMedicoOcupacional2;
    }
    
    public void setCertMedicoOcupacional2(CertMedicoOcupacional2 certMedicoOcupacional2) {
        this.certMedicoOcupacional2 = certMedicoOcupacional2;
    }
    public long getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(long idObservacion) {
        this.idObservacion = idObservacion;
    }




}


