package lissa.be;
// Generated 14/07/2018 08:27:00 AM by Hibernate Tools 4.3.1



/**
 * CmoRecomendaciones2 generated by hbm2java
 */
public class CmoRecomendaciones2  implements java.io.Serializable {


     private long idcmorecomendacion;
     private CertMedicoOcupacional2 certMedicoOcupacional2;
     private long idRecomendacion;

    public CmoRecomendaciones2() {
    }

    public CmoRecomendaciones2(long idcmorecomendacion, CertMedicoOcupacional2 certMedicoOcupacional2, long idRecomendacion) {
       this.idcmorecomendacion = idcmorecomendacion;
       this.certMedicoOcupacional2 = certMedicoOcupacional2;
       this.idRecomendacion = idRecomendacion;
    }
   
    public long getIdcmorecomendacion() {
        return this.idcmorecomendacion;
    }
    
    public void setIdcmorecomendacion(long idcmorecomendacion) {
        this.idcmorecomendacion = idcmorecomendacion;
    }
    public CertMedicoOcupacional2 getCertMedicoOcupacional2() {
        return this.certMedicoOcupacional2;
    }
    
    public void setCertMedicoOcupacional2(CertMedicoOcupacional2 certMedicoOcupacional2) {
        this.certMedicoOcupacional2 = certMedicoOcupacional2;
    }
    public long getIdRecomendacion() {
        return this.idRecomendacion;
    }
    
    public void setIdRecomendacion(long idRecomendacion) {
        this.idRecomendacion = idRecomendacion;
    }




}


