package lissa.be;
// Generated 10-oct-2016 10:03:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int idcompra;
     private FarComprobante farComprobante;
     private String numeroComprobante;
     private Date fechaCompra;
     private Integer idProveedor;
     private String serie;
     private String horaReg;
     private Date fechaReg;
     private BigDecimal valorNeto;
     private BigDecimal valorIgv;
     private BigDecimal valorBruto;
     private String estado;
     private String motivoAunulacion;
     private int numeroCompra;
     private int idUsuarioReg;
     private BigDecimal valorDescuento;
     private BigDecimal valorTotal;
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);

    public Compra() {
    }

	
    public Compra(int idcompra, String serie, String horaReg, Date fechaReg, BigDecimal montoSubtotal, BigDecimal montoIgv, BigDecimal montoTotal, String estado, String motivoAunulacion, int numeroCompra, int idUsuarioReg) {
        this.idcompra = idcompra;
        this.serie = serie;
        this.horaReg = horaReg;
        this.fechaReg = fechaReg;
        this.valorNeto = montoSubtotal;
        this.valorIgv = montoIgv;
        this.valorBruto = montoTotal;
        this.estado = estado;
        this.motivoAunulacion = motivoAunulacion;
        this.numeroCompra = numeroCompra;
        this.idUsuarioReg = idUsuarioReg;
    }
    public Compra(int idcompra, String numeroComprobante, Date fechaCompra, Integer idProveedor, String serie, String horaReg, Date fechaReg, BigDecimal montoSubtotal, BigDecimal montoIgv, BigDecimal montoTotal, String estado, String motivoAunulacion, int numeroCompra, int idUsuarioReg, Set<DetalleCompra> detalleCompras) {
       this.idcompra = idcompra;
       this.numeroComprobante = numeroComprobante;
       this.fechaCompra = fechaCompra;
       this.idProveedor = idProveedor;
       this.serie = serie;
       this.horaReg = horaReg;
       this.fechaReg = fechaReg;
       this.valorNeto = montoSubtotal;
       this.valorIgv = montoIgv;
       this.valorBruto = montoTotal;
       this.estado = estado;
       this.motivoAunulacion = motivoAunulacion;
       this.numeroCompra = numeroCompra;
       this.idUsuarioReg = idUsuarioReg;
       this.detalleCompras = detalleCompras;
    }
   
    public int getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public String getNumeroComprobante() {
        return this.numeroComprobante;
    }
    
    public void setNumeroComprobante(String numeroComprobante) {
        this.numeroComprobante = numeroComprobante;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getHoraReg() {
        return this.horaReg;
    }
    
    public void setHoraReg(String horaReg) {
        this.horaReg = horaReg;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public BigDecimal getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(BigDecimal valorNeto) {
        this.valorNeto = valorNeto;
    }
    public BigDecimal getValorIgv() {
        return this.valorIgv;
    }
    
    public void setValorIgv(BigDecimal valorIgv) {
        this.valorIgv = valorIgv;
    }
    public BigDecimal getValorBruto() {
        return this.valorBruto;
    }
    
    public void setValorBruto(BigDecimal valorBruto) {
        this.valorBruto = valorBruto;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMotivoAunulacion() {
        return this.motivoAunulacion;
    }
    
    public void setMotivoAunulacion(String motivoAunulacion) {
        this.motivoAunulacion = motivoAunulacion;
    }
    public int getNumeroCompra() {
        return this.numeroCompra;
    }
    
    public void setNumeroCompra(int numeroCompra) {
        this.numeroCompra = numeroCompra;
    }
    public int getIdUsuarioReg() {
        return this.idUsuarioReg;
    }
    
    public void setIdUsuarioReg(int idUsuarioReg) {
        this.idUsuarioReg = idUsuarioReg;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
    public BigDecimal getValorDescuento() {
        return valorDescuento;
    }
    public void setValorDescuento(BigDecimal valorDescuento) {
        this.valorDescuento = valorDescuento;
    }
    public BigDecimal getValorTotal() {
        return valorTotal;
    }
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    public FarComprobante getFarComprobante() {
        return farComprobante;
    }

    public void setFarComprobante(FarComprobante farComprobante) {
        this.farComprobante = farComprobante;
    }




}


