package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DatoAdicional generated by hbm2java
 */
public class DatoAdicional  implements java.io.Serializable {


     private int isdatoadicional;
     private Atencion atencion;
     private String observaciones;
     private Date proximaCita;
     private Boolean estado;

    public DatoAdicional() {
    }

	
    public DatoAdicional(int isdatoadicional) {
        this.isdatoadicional = isdatoadicional;
    }
    public DatoAdicional(int isdatoadicional, Atencion atencion, String observaciones, Date proximaCita, Boolean estado) {
       this.isdatoadicional = isdatoadicional;
       this.atencion = atencion;
       this.observaciones = observaciones;
       this.proximaCita = proximaCita;
       this.estado = estado;
    }
   
    public int getIsdatoadicional() {
        return this.isdatoadicional;
    }
    
    public void setIsdatoadicional(int isdatoadicional) {
        this.isdatoadicional = isdatoadicional;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getProximaCita() {
        return this.proximaCita;
    }
    
    public void setProximaCita(Date proximaCita) {
        this.proximaCita = proximaCita;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


