package lissa.be;
// Generated 23-sep-2016 12:43:58 by Hibernate Tools 4.3.1

/**
 * DetalleKardex generated by hbm2java
 */
public class DetalleKardex implements java.io.Serializable {

    private int iddetallekardex;
    private Kardex kardex;
    private Producto producto;
    private int cantidad;
    private int stockAnt;
    private int stockActual;
    private Integer merma;
    private Integer stockActOrig;
    private Integer stockAntOrig;

    private int numeroMovimiento;

    public DetalleKardex() {
    }

    public DetalleKardex(int iddetallekardex, Kardex kardex, Producto producto, int cantidad, int stockAnt, int stockActual) {
        this.iddetallekardex = iddetallekardex;
        this.kardex = kardex;
        this.producto = producto;
        this.cantidad = cantidad;
        this.stockAnt = stockAnt;
        this.stockActual = stockActual;
    }

    public DetalleKardex(int iddetallekardex, Kardex kardex, Producto producto, int cantidad, int stockAnt, int stockActual, Integer merma, Integer stockActOrig, Integer stockAntOrig) {
        this.iddetallekardex = iddetallekardex;
        this.kardex = kardex;
        this.producto = producto;
        this.cantidad = cantidad;
        this.stockAnt = stockAnt;
        this.stockActual = stockActual;
        this.merma = merma;
        this.stockActOrig = stockActOrig;
        this.stockAntOrig = stockAntOrig;
    }

    public int getIddetallekardex() {
        return this.iddetallekardex;
    }

    public void setIddetallekardex(int iddetallekardex) {
        this.iddetallekardex = iddetallekardex;
    }

    public Kardex getKardex() {
        return this.kardex;
    }

    public void setKardex(Kardex kardex) {
        this.kardex = kardex;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public int getStockAnt() {
        return this.stockAnt;
    }

    public void setStockAnt(int stockAnt) {
        this.stockAnt = stockAnt;
    }

    public int getStockActual() {
        return this.stockActual;
    }

    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }

    public Integer getMerma() {
        return this.merma;
    }

    public void setMerma(Integer merma) {
        this.merma = merma;
    }

    public Integer getStockActOrig() {
        return this.stockActOrig;
    }

    public void setStockActOrig(Integer stockActOrig) {
        this.stockActOrig = stockActOrig;
    }

    public Integer getStockAntOrig() {
        return this.stockAntOrig;
    }

    public void setStockAntOrig(Integer stockAntOrig) {
        this.stockAntOrig = stockAntOrig;
    }

    public int getNumeroMovimiento() {
        return numeroMovimiento;
    }

    public void setNumeroMovimiento(int numeroMovimiento) {
        this.numeroMovimiento = numeroMovimiento;
    }

}
