package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * Diagnostico generated by hbm2java
 */
public class Diagnostico  implements java.io.Serializable {


     private int iddiagnostico;
     private Atencion atencion;
     private Cie10 cie10;
     private String diagnostico;
     private String descripcion;

    public Diagnostico() {
    }

	
    public Diagnostico(int iddiagnostico, Atencion atencion, Cie10 cie10) {
        this.iddiagnostico = iddiagnostico;
        this.atencion = atencion;
        this.cie10 = cie10;
    }
    public Diagnostico(int iddiagnostico, Atencion atencion, Cie10 cie10, String diagnostico, String descripcion) {
       this.iddiagnostico = iddiagnostico;
       this.atencion = atencion;
       this.cie10 = cie10;
       this.diagnostico = diagnostico;
       this.descripcion = descripcion;
    }
   
    public int getIddiagnostico() {
        return this.iddiagnostico;
    }
    
    public void setIddiagnostico(int iddiagnostico) {
        this.iddiagnostico = iddiagnostico;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public Cie10 getCie10() {
        return this.cie10;
    }
    
    public void setCie10(Cie10 cie10) {
        this.cie10 = cie10;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


