package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * DiagnosticoOsteomuscular generated by hbm2java
 */
public class DiagnosticoOsteomuscular  implements java.io.Serializable {


     private int iddiagnosticoosteomuscular;
     private FichaOsteomuscular fichaOsteomuscular;
     private String diagnostico;

    public DiagnosticoOsteomuscular() {
    }

	
    public DiagnosticoOsteomuscular(int iddiagnosticoosteomuscular, FichaOsteomuscular fichaOsteomuscular) {
        this.iddiagnosticoosteomuscular = iddiagnosticoosteomuscular;
        this.fichaOsteomuscular = fichaOsteomuscular;
    }
    public DiagnosticoOsteomuscular(int iddiagnosticoosteomuscular, FichaOsteomuscular fichaOsteomuscular, String diagnostico) {
       this.iddiagnosticoosteomuscular = iddiagnosticoosteomuscular;
       this.fichaOsteomuscular = fichaOsteomuscular;
       this.diagnostico = diagnostico;
    }
   
    public int getIddiagnosticoosteomuscular() {
        return this.iddiagnosticoosteomuscular;
    }
    
    public void setIddiagnosticoosteomuscular(int iddiagnosticoosteomuscular) {
        this.iddiagnosticoosteomuscular = iddiagnosticoosteomuscular;
    }
    public FichaOsteomuscular getFichaOsteomuscular() {
        return this.fichaOsteomuscular;
    }
    
    public void setFichaOsteomuscular(FichaOsteomuscular fichaOsteomuscular) {
        this.fichaOsteomuscular = fichaOsteomuscular;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }




}


