package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EvaluacionOcupacional generated by hbm2java
 */
public class EvaluacionOcupacional implements java.io.Serializable {

    private int idevaluacionocupacional;
    private String evaluacion;
    private Boolean estado;
    private Set<AtencionOcupacional> atencionOcupacionals = new HashSet<AtencionOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public EvaluacionOcupacional() {
    }

    public EvaluacionOcupacional(int idevaluacionocupacional, String evaluacion) {
        this.idevaluacionocupacional = idevaluacionocupacional;
        this.evaluacion = evaluacion;
    }

    public EvaluacionOcupacional(int idevaluacionocupacional, String evaluacion, Boolean estado, Set<AtencionOcupacional> atencionOcupacionals) {
        this.idevaluacionocupacional = idevaluacionocupacional;
        this.evaluacion = evaluacion;
        this.estado = estado;
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public int getIdevaluacionocupacional() {
        return this.idevaluacionocupacional;
    }

    public void setIdevaluacionocupacional(int idevaluacionocupacional) {
        this.idevaluacionocupacional = idevaluacionocupacional;
    }

    public String getEvaluacion() {
        return this.evaluacion;
    }

    public void setEvaluacion(String evaluacion) {
        this.evaluacion = evaluacion;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<AtencionOcupacional> getAtencionOcupacionals() {
        return this.atencionOcupacionals;
    }

    public void setAtencionOcupacionals(Set<AtencionOcupacional> atencionOcupacionals) {
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getEvaluacion();
            default:
                return "<SELECCIONE>";
        }
    }

}
