package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * ExamenAuxiliar generated by hbm2java
 */
public class ExamenAuxiliar  implements java.io.Serializable {


     private int idexamenauxiliar;
     private Atencion atencion;
     private String examen;
     private Boolean estado;

    public ExamenAuxiliar() {
    }

	
    public ExamenAuxiliar(int idexamenauxiliar) {
        this.idexamenauxiliar = idexamenauxiliar;
    }
    public ExamenAuxiliar(int idexamenauxiliar, Atencion atencion, String examen, Boolean estado) {
       this.idexamenauxiliar = idexamenauxiliar;
       this.atencion = atencion;
       this.examen = examen;
       this.estado = estado;
    }
   
    public int getIdexamenauxiliar() {
        return this.idexamenauxiliar;
    }
    
    public void setIdexamenauxiliar(int idexamenauxiliar) {
        this.idexamenauxiliar = idexamenauxiliar;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public String getExamen() {
        return this.examen;
    }
    
    public void setExamen(String examen) {
        this.examen = examen;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


