package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ExamenOcupacional generated by hbm2java
 */
public class ExamenOcupacional implements java.io.Serializable {

    private long idexamenocupacional;
    private String descripcion;
    private Set<Restriccion> restriccions = new HashSet<Restriccion>(0);
    private Set<Cie10> cie10s = new HashSet<Cie10>(0);
    private Set<Recomendacion> recomendacions = new HashSet<Recomendacion>(0);
    private Set<MotivoObservacion> motivoObservacions = new HashSet<MotivoObservacion>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public ExamenOcupacional() {
    }

    public ExamenOcupacional(long idexamenocupacional, String descripcion) {
        this.idexamenocupacional = idexamenocupacional;
        this.descripcion = descripcion;
    }

    public ExamenOcupacional(long idexamenocupacional, String descripcion, Set<Restriccion> restriccions, Set<Cie10> cie10s, Set<Recomendacion> recomendacions, Set<MotivoObservacion> motivoObservacions) {
        this.idexamenocupacional = idexamenocupacional;
        this.descripcion = descripcion;
        this.restriccions = restriccions;
        this.cie10s = cie10s;
        this.recomendacions = recomendacions;
        this.motivoObservacions = motivoObservacions;
    }

    public long getIdexamenocupacional() {
        return this.idexamenocupacional;
    }

    public void setIdexamenocupacional(long idexamenocupacional) {
        this.idexamenocupacional = idexamenocupacional;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Restriccion> getRestriccions() {
        return this.restriccions;
    }

    public void setRestriccions(Set<Restriccion> restriccions) {
        this.restriccions = restriccions;
    }

    public Set<Cie10> getCie10s() {
        return this.cie10s;
    }

    public void setCie10s(Set<Cie10> cie10s) {
        this.cie10s = cie10s;
    }

    public Set<Recomendacion> getRecomendacions() {
        return this.recomendacions;
    }

    public void setRecomendacions(Set<Recomendacion> recomendacions) {
        this.recomendacions = recomendacions;
    }

    public Set<MotivoObservacion> getMotivoObservacions() {
        return this.motivoObservacions;
    }

    public void setMotivoObservacions(Set<MotivoObservacion> motivoObservacions) {
        this.motivoObservacions = motivoObservacions;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDescripcion();
            default:
                return "<SELECCIONE>";
        }
    }

}
