package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ExamenOcupacional generated by hbm2java
 */
public class ExamenOcupacional implements java.io.Serializable {

    private int idexamenocupacional;
    private String examen;
    private Boolean estado;
    private Set<AtencionOcupacional> atencionOcupacionals = new HashSet<AtencionOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public ExamenOcupacional() {
    }

    public ExamenOcupacional(int idexamenocupacional) {
        this.idexamenocupacional = idexamenocupacional;
    }

    public ExamenOcupacional(int idexamenocupacional, String examen, Boolean estado, Set<AtencionOcupacional> atencionOcupacionals) {
        this.idexamenocupacional = idexamenocupacional;
        this.examen = examen;
        this.estado = estado;
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public int getIdexamenocupacional() {
        return this.idexamenocupacional;
    }

    public void setIdexamenocupacional(int idexamenocupacional) {
        this.idexamenocupacional = idexamenocupacional;
    }

    public String getExamen() {
        return this.examen;
    }

    public void setExamen(String examen) {
        this.examen = examen;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<AtencionOcupacional> getAtencionOcupacionals() {
        return this.atencionOcupacionals;
    }

    public void setAtencionOcupacionals(Set<AtencionOcupacional> atencionOcupacionals) {
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getExamen();
            default:
                return "<SELECCIONE>";
        }
    }

}
