package lissa.be;
// Generated 10-dic-2016 10:56:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FarComprobante generated by hbm2java
 */
public class FarComprobante implements java.io.Serializable {

    private int idfarcomprobante;
    private String comprobante;
    private String tipoComprobante;
    private boolean estado;
    private Set<Venta> ventas = new HashSet<Venta>(0);
    private Set<Compra> compras = new HashSet<Compra>(0);

    private int op = -1;
    public static final int DEFECTO = -1, DATO = 3;
    public static final String VENTA = "VENTA", COMPRA = "COMPRA", DISTRIBUCION = "DISTRIBUCION";

    public FarComprobante() {
    }

    public FarComprobante(int idfarcomprobante, String comprobante, String tipoComprobante, boolean estado) {
        this.idfarcomprobante = idfarcomprobante;
        this.comprobante = comprobante;
        this.tipoComprobante = tipoComprobante;
        this.estado = estado;
    }

    public FarComprobante(int idfarcomprobante, String comprobante, String tipoComprobante, boolean estado, Set<Venta> ventas, Set<Compra> compras) {
        this.idfarcomprobante = idfarcomprobante;
        this.comprobante = comprobante;
        this.tipoComprobante = tipoComprobante;
        this.estado = estado;
        this.ventas = ventas;
        this.compras = compras;
    }

    public int getIdfarcomprobante() {
        return this.idfarcomprobante;
    }

    public void setIdfarcomprobante(int idfarcomprobante) {
        this.idfarcomprobante = idfarcomprobante;
    }

    public String getComprobante() {
        return this.comprobante;
    }

    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }

    public String getTipoComprobante() {
        return this.tipoComprobante;
    }

    public void setTipoComprobante(String tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Set<Venta> getVentas() {
        return this.ventas;
    }

    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

    public Set<Compra> getCompras() {
        return this.compras;
    }

    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }

    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getComprobante();
            default:
                return "<Seleccione>";
        }
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

}
