package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FichaOsteomuscular generated by hbm2java
 */
public class FichaOsteomuscular  implements java.io.Serializable {


     private int idfichaosteomuscular;
     private AtencionOcupacional atencionOcupacional;
     private String puesto;
     private Double postSedente;
     private Double postBipodestacion;
     private String postForzada;
     private String movRepetitivos;
     private String movManualCarga;
     private Double pesoDesde;
     private Double pesoHasta;
     private boolean metLevanta;
     private boolean metEmpuja;
     private boolean metArrastra;
     private String usuarioPvd;
     private Double horasDia;
     private boolean dominanciaDiestro;
     private boolean dominanciaZurdo;
     private boolean lordosisCervicalNormal;
     private boolean lordosisCervicalIncrementada;
     private boolean lordosisCervicalDisminuida;
     private boolean cifosisNormal;
     private boolean cifosisIncrementada;
     private boolean cifosisDisminuida;
     private boolean lordosisLumbarNormal;
     private boolean lordosisLumbarIncrementada;
     private boolean lordosisLumbarDisminuida;
     private boolean escoliosisDorsal;
     private boolean escoliosisLumbar;
     private boolean cervicalFlexion;
     private boolean cervicalExtension;
     private boolean cervicalDer;
     private boolean cervicalIzq;
     private boolean cervicalRotacion;
     private boolean lumbarFlexion;
     private boolean lumbarExtension;
     private boolean lumbarDer;
     private boolean lumbarIzq;
     private boolean lumbarRotacion;
     private String movDolorObservacion;
     private boolean opofisisEspDolorosa;
     private String opofisisEspDolorosaObser;
     private boolean contracturaMuscular;
     private String contracturaMuscularObser;
     private boolean dolorEspalda;
     private String dolorEspaldaObser;
     private String signoLasegueDer;
     private String signoLasegueIzq;
     private String signoBragardDer;
     private String signoBragardIzq;
     private String testPhalenDer;
     private String testPhalenIzq;
     private String testTinelDer;
     private String testTinelIzq;
     private boolean cavoDer;
     private boolean cavoIzq;
     private boolean planoDer;
     private boolean planoIzq;
     private String rotulianoDer;
     private String rotulianoIzq;
     private String aquilioDer;
     private String aquilioIzq;
     private String descAnomaliaNeg;
     private int idUser;
     private String conclusion;
     private Set<Articulacion> articulacions = new HashSet<Articulacion>(0);
     private Set<DiagnosticoOsteomuscular> diagnosticoOsteomusculars = new HashSet<DiagnosticoOsteomuscular>(0);

    public FichaOsteomuscular() {
    }

	
    public FichaOsteomuscular(int idfichaosteomuscular, AtencionOcupacional atencionOcupacional, boolean metLevanta, boolean metEmpuja, boolean metArrastra, boolean dominanciaDiestro, boolean dominanciaZurdo, boolean lordosisCervicalNormal, boolean lordosisCervicalIncrementada, boolean lordosisCervicalDisminuida, boolean cifosisNormal, boolean cifosisIncrementada, boolean cifosisDisminuida, boolean lordosisLumbarNormal, boolean lordosisLumbarIncrementada, boolean lordosisLumbarDisminuida, boolean escoliosisDorsal, boolean escoliosisLumbar, boolean cervicalFlexion, boolean cervicalExtension, boolean cervicalDer, boolean cervicalIzq, boolean cervicalRotacion, boolean lumbarFlexion, boolean lumbarExtension, boolean lumbarDer, boolean lumbarIzq, boolean lumbarRotacion, String movDolorObservacion, boolean opofisisEspDolorosa, String opofisisEspDolorosaObser, boolean contracturaMuscular, String contracturaMuscularObser, boolean dolorEspalda, String dolorEspaldaObser, String signoLasegueDer, String signoLasegueIzq, String signoBragardDer, String signoBragardIzq, String testPhalenDer, String testPhalenIzq, String testTinelDer, String testTinelIzq, boolean cavoDer, boolean cavoIzq, boolean planoDer, boolean planoIzq, String rotulianoDer, String rotulianoIzq, String aquilioDer, String aquilioIzq, String descAnomaliaNeg, int idUser) {
        this.idfichaosteomuscular = idfichaosteomuscular;
        this.atencionOcupacional = atencionOcupacional;
        this.metLevanta = metLevanta;
        this.metEmpuja = metEmpuja;
        this.metArrastra = metArrastra;
        this.dominanciaDiestro = dominanciaDiestro;
        this.dominanciaZurdo = dominanciaZurdo;
        this.lordosisCervicalNormal = lordosisCervicalNormal;
        this.lordosisCervicalIncrementada = lordosisCervicalIncrementada;
        this.lordosisCervicalDisminuida = lordosisCervicalDisminuida;
        this.cifosisNormal = cifosisNormal;
        this.cifosisIncrementada = cifosisIncrementada;
        this.cifosisDisminuida = cifosisDisminuida;
        this.lordosisLumbarNormal = lordosisLumbarNormal;
        this.lordosisLumbarIncrementada = lordosisLumbarIncrementada;
        this.lordosisLumbarDisminuida = lordosisLumbarDisminuida;
        this.escoliosisDorsal = escoliosisDorsal;
        this.escoliosisLumbar = escoliosisLumbar;
        this.cervicalFlexion = cervicalFlexion;
        this.cervicalExtension = cervicalExtension;
        this.cervicalDer = cervicalDer;
        this.cervicalIzq = cervicalIzq;
        this.cervicalRotacion = cervicalRotacion;
        this.lumbarFlexion = lumbarFlexion;
        this.lumbarExtension = lumbarExtension;
        this.lumbarDer = lumbarDer;
        this.lumbarIzq = lumbarIzq;
        this.lumbarRotacion = lumbarRotacion;
        this.movDolorObservacion = movDolorObservacion;
        this.opofisisEspDolorosa = opofisisEspDolorosa;
        this.opofisisEspDolorosaObser = opofisisEspDolorosaObser;
        this.contracturaMuscular = contracturaMuscular;
        this.contracturaMuscularObser = contracturaMuscularObser;
        this.dolorEspalda = dolorEspalda;
        this.dolorEspaldaObser = dolorEspaldaObser;
        this.signoLasegueDer = signoLasegueDer;
        this.signoLasegueIzq = signoLasegueIzq;
        this.signoBragardDer = signoBragardDer;
        this.signoBragardIzq = signoBragardIzq;
        this.testPhalenDer = testPhalenDer;
        this.testPhalenIzq = testPhalenIzq;
        this.testTinelDer = testTinelDer;
        this.testTinelIzq = testTinelIzq;
        this.cavoDer = cavoDer;
        this.cavoIzq = cavoIzq;
        this.planoDer = planoDer;
        this.planoIzq = planoIzq;
        this.rotulianoDer = rotulianoDer;
        this.rotulianoIzq = rotulianoIzq;
        this.aquilioDer = aquilioDer;
        this.aquilioIzq = aquilioIzq;
        this.descAnomaliaNeg = descAnomaliaNeg;
        this.idUser = idUser;
    }
    public FichaOsteomuscular(int idfichaosteomuscular, AtencionOcupacional atencionOcupacional, String puesto, Double postSedente, Double postBipodestacion, String postForzada, String movRepetitivos, String movManualCarga, Double pesoDesde, Double pesoHasta, boolean metLevanta, boolean metEmpuja, boolean metArrastra, String usuarioPvd, Double horasDia, boolean dominanciaDiestro, boolean dominanciaZurdo, boolean lordosisCervicalNormal, boolean lordosisCervicalIncrementada, boolean lordosisCervicalDisminuida, boolean cifosisNormal, boolean cifosisIncrementada, boolean cifosisDisminuida, boolean lordosisLumbarNormal, boolean lordosisLumbarIncrementada, boolean lordosisLumbarDisminuida, boolean escoliosisDorsal, boolean escoliosisLumbar, boolean cervicalFlexion, boolean cervicalExtension, boolean cervicalDer, boolean cervicalIzq, boolean cervicalRotacion, boolean lumbarFlexion, boolean lumbarExtension, boolean lumbarDer, boolean lumbarIzq, boolean lumbarRotacion, String movDolorObservacion, boolean opofisisEspDolorosa, String opofisisEspDolorosaObser, boolean contracturaMuscular, String contracturaMuscularObser, boolean dolorEspalda, String dolorEspaldaObser, String signoLasegueDer, String signoLasegueIzq, String signoBragardDer, String signoBragardIzq, String testPhalenDer, String testPhalenIzq, String testTinelDer, String testTinelIzq, boolean cavoDer, boolean cavoIzq, boolean planoDer, boolean planoIzq, String rotulianoDer, String rotulianoIzq, String aquilioDer, String aquilioIzq, String descAnomaliaNeg, int idUser, Set<Articulacion> articulacions, Set<DiagnosticoOsteomuscular> diagnosticoOsteomusculars) {
       this.idfichaosteomuscular = idfichaosteomuscular;
       this.atencionOcupacional = atencionOcupacional;
       this.puesto = puesto;
       this.postSedente = postSedente;
       this.postBipodestacion = postBipodestacion;
       this.postForzada = postForzada;
       this.movRepetitivos = movRepetitivos;
       this.movManualCarga = movManualCarga;
       this.pesoDesde = pesoDesde;
       this.pesoHasta = pesoHasta;
       this.metLevanta = metLevanta;
       this.metEmpuja = metEmpuja;
       this.metArrastra = metArrastra;
       this.usuarioPvd = usuarioPvd;
       this.horasDia = horasDia;
       this.dominanciaDiestro = dominanciaDiestro;
       this.dominanciaZurdo = dominanciaZurdo;
       this.lordosisCervicalNormal = lordosisCervicalNormal;
       this.lordosisCervicalIncrementada = lordosisCervicalIncrementada;
       this.lordosisCervicalDisminuida = lordosisCervicalDisminuida;
       this.cifosisNormal = cifosisNormal;
       this.cifosisIncrementada = cifosisIncrementada;
       this.cifosisDisminuida = cifosisDisminuida;
       this.lordosisLumbarNormal = lordosisLumbarNormal;
       this.lordosisLumbarIncrementada = lordosisLumbarIncrementada;
       this.lordosisLumbarDisminuida = lordosisLumbarDisminuida;
       this.escoliosisDorsal = escoliosisDorsal;
       this.escoliosisLumbar = escoliosisLumbar;
       this.cervicalFlexion = cervicalFlexion;
       this.cervicalExtension = cervicalExtension;
       this.cervicalDer = cervicalDer;
       this.cervicalIzq = cervicalIzq;
       this.cervicalRotacion = cervicalRotacion;
       this.lumbarFlexion = lumbarFlexion;
       this.lumbarExtension = lumbarExtension;
       this.lumbarDer = lumbarDer;
       this.lumbarIzq = lumbarIzq;
       this.lumbarRotacion = lumbarRotacion;
       this.movDolorObservacion = movDolorObservacion;
       this.opofisisEspDolorosa = opofisisEspDolorosa;
       this.opofisisEspDolorosaObser = opofisisEspDolorosaObser;
       this.contracturaMuscular = contracturaMuscular;
       this.contracturaMuscularObser = contracturaMuscularObser;
       this.dolorEspalda = dolorEspalda;
       this.dolorEspaldaObser = dolorEspaldaObser;
       this.signoLasegueDer = signoLasegueDer;
       this.signoLasegueIzq = signoLasegueIzq;
       this.signoBragardDer = signoBragardDer;
       this.signoBragardIzq = signoBragardIzq;
       this.testPhalenDer = testPhalenDer;
       this.testPhalenIzq = testPhalenIzq;
       this.testTinelDer = testTinelDer;
       this.testTinelIzq = testTinelIzq;
       this.cavoDer = cavoDer;
       this.cavoIzq = cavoIzq;
       this.planoDer = planoDer;
       this.planoIzq = planoIzq;
       this.rotulianoDer = rotulianoDer;
       this.rotulianoIzq = rotulianoIzq;
       this.aquilioDer = aquilioDer;
       this.aquilioIzq = aquilioIzq;
       this.descAnomaliaNeg = descAnomaliaNeg;
       this.idUser = idUser;
       this.articulacions = articulacions;
       this.diagnosticoOsteomusculars = diagnosticoOsteomusculars;
    }
   
    public int getIdfichaosteomuscular() {
        return this.idfichaosteomuscular;
    }
    
    public void setIdfichaosteomuscular(int idfichaosteomuscular) {
        this.idfichaosteomuscular = idfichaosteomuscular;
    }
    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }
    
    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Double getPostSedente() {
        return this.postSedente;
    }
    
    public void setPostSedente(Double postSedente) {
        this.postSedente = postSedente;
    }
    public Double getPostBipodestacion() {
        return this.postBipodestacion;
    }
    
    public void setPostBipodestacion(Double postBipodestacion) {
        this.postBipodestacion = postBipodestacion;
    }
    public String getPostForzada() {
        return this.postForzada;
    }
    
    public void setPostForzada(String postForzada) {
        this.postForzada = postForzada;
    }
    public String getMovRepetitivos() {
        return this.movRepetitivos;
    }
    
    public void setMovRepetitivos(String movRepetitivos) {
        this.movRepetitivos = movRepetitivos;
    }
    public String getMovManualCarga() {
        return this.movManualCarga;
    }
    
    public void setMovManualCarga(String movManualCarga) {
        this.movManualCarga = movManualCarga;
    }
    public Double getPesoDesde() {
        return this.pesoDesde;
    }
    
    public void setPesoDesde(Double pesoDesde) {
        this.pesoDesde = pesoDesde;
    }
    public Double getPesoHasta() {
        return this.pesoHasta;
    }
    
    public void setPesoHasta(Double pesoHasta) {
        this.pesoHasta = pesoHasta;
    }
    public boolean isMetLevanta() {
        return this.metLevanta;
    }
    
    public void setMetLevanta(boolean metLevanta) {
        this.metLevanta = metLevanta;
    }
    public boolean isMetEmpuja() {
        return this.metEmpuja;
    }
    
    public void setMetEmpuja(boolean metEmpuja) {
        this.metEmpuja = metEmpuja;
    }
    public boolean isMetArrastra() {
        return this.metArrastra;
    }
    
    public void setMetArrastra(boolean metArrastra) {
        this.metArrastra = metArrastra;
    }
    public String getUsuarioPvd() {
        return this.usuarioPvd;
    }
    
    public void setUsuarioPvd(String usuarioPvd) {
        this.usuarioPvd = usuarioPvd;
    }
    public Double getHorasDia() {
        return this.horasDia;
    }
    
    public void setHorasDia(Double horasDia) {
        this.horasDia = horasDia;
    }
    public boolean isDominanciaDiestro() {
        return this.dominanciaDiestro;
    }
    
    public void setDominanciaDiestro(boolean dominanciaDiestro) {
        this.dominanciaDiestro = dominanciaDiestro;
    }
    public boolean isDominanciaZurdo() {
        return this.dominanciaZurdo;
    }
    
    public void setDominanciaZurdo(boolean dominanciaZurdo) {
        this.dominanciaZurdo = dominanciaZurdo;
    }
    public boolean isLordosisCervicalNormal() {
        return this.lordosisCervicalNormal;
    }
    
    public void setLordosisCervicalNormal(boolean lordosisCervicalNormal) {
        this.lordosisCervicalNormal = lordosisCervicalNormal;
    }
    public boolean isLordosisCervicalIncrementada() {
        return this.lordosisCervicalIncrementada;
    }
    
    public void setLordosisCervicalIncrementada(boolean lordosisCervicalIncrementada) {
        this.lordosisCervicalIncrementada = lordosisCervicalIncrementada;
    }
    public boolean isLordosisCervicalDisminuida() {
        return this.lordosisCervicalDisminuida;
    }
    
    public void setLordosisCervicalDisminuida(boolean lordosisCervicalDisminuida) {
        this.lordosisCervicalDisminuida = lordosisCervicalDisminuida;
    }
    public boolean isCifosisNormal() {
        return this.cifosisNormal;
    }
    
    public void setCifosisNormal(boolean cifosisNormal) {
        this.cifosisNormal = cifosisNormal;
    }
    public boolean isCifosisIncrementada() {
        return this.cifosisIncrementada;
    }
    
    public void setCifosisIncrementada(boolean cifosisIncrementada) {
        this.cifosisIncrementada = cifosisIncrementada;
    }
    public boolean isCifosisDisminuida() {
        return this.cifosisDisminuida;
    }
    
    public void setCifosisDisminuida(boolean cifosisDisminuida) {
        this.cifosisDisminuida = cifosisDisminuida;
    }
    public boolean isLordosisLumbarNormal() {
        return this.lordosisLumbarNormal;
    }
    
    public void setLordosisLumbarNormal(boolean lordosisLumbarNormal) {
        this.lordosisLumbarNormal = lordosisLumbarNormal;
    }
    public boolean isLordosisLumbarIncrementada() {
        return this.lordosisLumbarIncrementada;
    }
    
    public void setLordosisLumbarIncrementada(boolean lordosisLumbarIncrementada) {
        this.lordosisLumbarIncrementada = lordosisLumbarIncrementada;
    }
    public boolean isLordosisLumbarDisminuida() {
        return this.lordosisLumbarDisminuida;
    }
    
    public void setLordosisLumbarDisminuida(boolean lordosisLumbarDisminuida) {
        this.lordosisLumbarDisminuida = lordosisLumbarDisminuida;
    }
    public boolean isEscoliosisDorsal() {
        return this.escoliosisDorsal;
    }
    
    public void setEscoliosisDorsal(boolean escoliosisDorsal) {
        this.escoliosisDorsal = escoliosisDorsal;
    }
    public boolean isEscoliosisLumbar() {
        return this.escoliosisLumbar;
    }
    
    public void setEscoliosisLumbar(boolean escoliosisLumbar) {
        this.escoliosisLumbar = escoliosisLumbar;
    }
    public boolean isCervicalFlexion() {
        return this.cervicalFlexion;
    }
    
    public void setCervicalFlexion(boolean cervicalFlexion) {
        this.cervicalFlexion = cervicalFlexion;
    }
    public boolean isCervicalExtension() {
        return this.cervicalExtension;
    }
    
    public void setCervicalExtension(boolean cervicalExtension) {
        this.cervicalExtension = cervicalExtension;
    }
    public boolean isCervicalDer() {
        return this.cervicalDer;
    }
    
    public void setCervicalDer(boolean cervicalDer) {
        this.cervicalDer = cervicalDer;
    }
    public boolean isCervicalIzq() {
        return this.cervicalIzq;
    }
    
    public void setCervicalIzq(boolean cervicalIzq) {
        this.cervicalIzq = cervicalIzq;
    }
    public boolean isCervicalRotacion() {
        return this.cervicalRotacion;
    }
    
    public void setCervicalRotacion(boolean cervicalRotacion) {
        this.cervicalRotacion = cervicalRotacion;
    }
    public boolean isLumbarFlexion() {
        return this.lumbarFlexion;
    }
    
    public void setLumbarFlexion(boolean lumbarFlexion) {
        this.lumbarFlexion = lumbarFlexion;
    }
    public boolean isLumbarExtension() {
        return this.lumbarExtension;
    }
    
    public void setLumbarExtension(boolean lumbarExtension) {
        this.lumbarExtension = lumbarExtension;
    }
    public boolean isLumbarDer() {
        return this.lumbarDer;
    }
    
    public void setLumbarDer(boolean lumbarDer) {
        this.lumbarDer = lumbarDer;
    }
    public boolean isLumbarIzq() {
        return this.lumbarIzq;
    }
    
    public void setLumbarIzq(boolean lumbarIzq) {
        this.lumbarIzq = lumbarIzq;
    }
    public boolean isLumbarRotacion() {
        return this.lumbarRotacion;
    }
    
    public void setLumbarRotacion(boolean lumbarRotacion) {
        this.lumbarRotacion = lumbarRotacion;
    }
    public String getMovDolorObservacion() {
        return this.movDolorObservacion;
    }
    
    public void setMovDolorObservacion(String movDolorObservacion) {
        this.movDolorObservacion = movDolorObservacion;
    }
    public boolean isOpofisisEspDolorosa() {
        return this.opofisisEspDolorosa;
    }
    
    public void setOpofisisEspDolorosa(boolean opofisisEspDolorosa) {
        this.opofisisEspDolorosa = opofisisEspDolorosa;
    }
    public String getOpofisisEspDolorosaObser() {
        return this.opofisisEspDolorosaObser;
    }
    
    public void setOpofisisEspDolorosaObser(String opofisisEspDolorosaObser) {
        this.opofisisEspDolorosaObser = opofisisEspDolorosaObser;
    }
    public boolean isContracturaMuscular() {
        return this.contracturaMuscular;
    }
    
    public void setContracturaMuscular(boolean contracturaMuscular) {
        this.contracturaMuscular = contracturaMuscular;
    }
    public String getContracturaMuscularObser() {
        return this.contracturaMuscularObser;
    }
    
    public void setContracturaMuscularObser(String contracturaMuscularObser) {
        this.contracturaMuscularObser = contracturaMuscularObser;
    }
    public boolean isDolorEspalda() {
        return this.dolorEspalda;
    }
    
    public void setDolorEspalda(boolean dolorEspalda) {
        this.dolorEspalda = dolorEspalda;
    }
    public String getDolorEspaldaObser() {
        return this.dolorEspaldaObser;
    }
    
    public void setDolorEspaldaObser(String dolorEspaldaObser) {
        this.dolorEspaldaObser = dolorEspaldaObser;
    }
    public String getSignoLasegueDer() {
        return this.signoLasegueDer;
    }
    
    public void setSignoLasegueDer(String signoLasegueDer) {
        this.signoLasegueDer = signoLasegueDer;
    }
    public String getSignoLasegueIzq() {
        return this.signoLasegueIzq;
    }
    
    public void setSignoLasegueIzq(String signoLasegueIzq) {
        this.signoLasegueIzq = signoLasegueIzq;
    }
    public String getSignoBragardDer() {
        return this.signoBragardDer;
    }
    
    public void setSignoBragardDer(String signoBragardDer) {
        this.signoBragardDer = signoBragardDer;
    }
    public String getSignoBragardIzq() {
        return this.signoBragardIzq;
    }
    
    public void setSignoBragardIzq(String signoBragardIzq) {
        this.signoBragardIzq = signoBragardIzq;
    }
    public String getTestPhalenDer() {
        return this.testPhalenDer;
    }
    
    public void setTestPhalenDer(String testPhalenDer) {
        this.testPhalenDer = testPhalenDer;
    }
    public String getTestPhalenIzq() {
        return this.testPhalenIzq;
    }
    
    public void setTestPhalenIzq(String testPhalenIzq) {
        this.testPhalenIzq = testPhalenIzq;
    }
    public String getTestTinelDer() {
        return this.testTinelDer;
    }
    
    public void setTestTinelDer(String testTinelDer) {
        this.testTinelDer = testTinelDer;
    }
    public String getTestTinelIzq() {
        return this.testTinelIzq;
    }
    
    public void setTestTinelIzq(String testTinelIzq) {
        this.testTinelIzq = testTinelIzq;
    }
    public boolean isCavoDer() {
        return this.cavoDer;
    }
    
    public void setCavoDer(boolean cavoDer) {
        this.cavoDer = cavoDer;
    }
    public boolean isCavoIzq() {
        return this.cavoIzq;
    }
    
    public void setCavoIzq(boolean cavoIzq) {
        this.cavoIzq = cavoIzq;
    }
    public boolean isPlanoDer() {
        return this.planoDer;
    }
    
    public void setPlanoDer(boolean planoDer) {
        this.planoDer = planoDer;
    }
    public boolean isPlanoIzq() {
        return this.planoIzq;
    }
    
    public void setPlanoIzq(boolean planoIzq) {
        this.planoIzq = planoIzq;
    }
    public String getRotulianoDer() {
        return this.rotulianoDer;
    }
    
    public void setRotulianoDer(String rotulianoDer) {
        this.rotulianoDer = rotulianoDer;
    }
    public String getRotulianoIzq() {
        return this.rotulianoIzq;
    }
    
    public void setRotulianoIzq(String rotulianoIzq) {
        this.rotulianoIzq = rotulianoIzq;
    }
    public String getAquilioDer() {
        return this.aquilioDer;
    }
    
    public void setAquilioDer(String aquilioDer) {
        this.aquilioDer = aquilioDer;
    }
    public String getAquilioIzq() {
        return this.aquilioIzq;
    }
    
    public void setAquilioIzq(String aquilioIzq) {
        this.aquilioIzq = aquilioIzq;
    }
    public String getDescAnomaliaNeg() {
        return this.descAnomaliaNeg;
    }
    
    public void setDescAnomaliaNeg(String descAnomaliaNeg) {
        this.descAnomaliaNeg = descAnomaliaNeg;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public Set<Articulacion> getArticulacions() {
        return this.articulacions;
    }
    
    public void setArticulacions(Set<Articulacion> articulacions) {
        this.articulacions = articulacions;
    }
    public Set<DiagnosticoOsteomuscular> getDiagnosticoOsteomusculars() {
        return this.diagnosticoOsteomusculars;
    }
    
    public void setDiagnosticoOsteomusculars(Set<DiagnosticoOsteomuscular> diagnosticoOsteomusculars) {
        this.diagnosticoOsteomusculars = diagnosticoOsteomusculars;
    }

    public String getConclusion() {
        return conclusion;
    }

    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }




}


