package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * FichaAudiometria generated by hbm2java
 */
public class FichaAudiometria  implements java.io.Serializable {


     private int idfichaaudiometria;
     private AtencionOcupacional atencionOcupacional;
     private Boolean otitsCronica;
     private Boolean ototoxidad;
     private Boolean tec;
     private Boolean meningitis;
     private Boolean rinitis;
     private Boolean parotiditis;
     private Boolean sarampion;
     private Boolean walkman;
     private Boolean traumaAuditivo;
     private String otros;
     private String tampones;
     private String orejanas;
     private String algodones;
     private String otrosProtecAuric;
     private String ocupacionalesObserv;
     private Boolean acufenos;
     private Boolean vertigo;
     private Boolean hipoacusia;
     private Boolean otalgia;
     private Boolean esposicionRecienteRuido;
     private Boolean practicasRuidosas;
     private String pabellonDer;
     private String pabellonIzq;
     private String auditivoDer;
     private String auditivoIzq;
     private String timpanoDer;
     private String timpanoIzq;
     private String fosasNasalesDer;
     private String fosasNasalesIzq;
     private String conclusion;
     private String recomendaciones;
     private int idUsuario;

    public FichaAudiometria() {
    }

	
    public FichaAudiometria(int idfichaaudiometria, AtencionOcupacional atencionOcupacional, int idUsuario) {
        this.idfichaaudiometria = idfichaaudiometria;
        this.atencionOcupacional = atencionOcupacional;
        this.idUsuario = idUsuario;
    }
    public FichaAudiometria(int idfichaaudiometria, AtencionOcupacional atencionOcupacional, Boolean otitsCronica, Boolean ototoxidad, Boolean tec, Boolean meningitis, Boolean rinitis, Boolean parotiditis, Boolean sarampion, Boolean walkman, Boolean traumaAuditivo, String otros, String tampones, String orejanas, String algodones, String otrosProtecAuric, String ocupacionalesObserv, Boolean acufenos, Boolean vertigo, Boolean hipoacusia, Boolean otalgia, Boolean esposicionRecienteRuido, Boolean practicasRuidosas, String pabellonDer, String pabellonIzq, String auditivoDer, String auditivoIzq, String timpanoDer, String timpanoIzq, String fosasNasalesDer, String fosasNasalesIzq, String diagnostico, String recomendaciones, int idUsuario) {
       this.idfichaaudiometria = idfichaaudiometria;
       this.atencionOcupacional = atencionOcupacional;
       this.otitsCronica = otitsCronica;
       this.ototoxidad = ototoxidad;
       this.tec = tec;
       this.meningitis = meningitis;
       this.rinitis = rinitis;
       this.parotiditis = parotiditis;
       this.sarampion = sarampion;
       this.walkman = walkman;
       this.traumaAuditivo = traumaAuditivo;
       this.otros = otros;
       this.tampones = tampones;
       this.orejanas = orejanas;
       this.algodones = algodones;
       this.otrosProtecAuric = otrosProtecAuric;
       this.ocupacionalesObserv = ocupacionalesObserv;
       this.acufenos = acufenos;
       this.vertigo = vertigo;
       this.hipoacusia = hipoacusia;
       this.otalgia = otalgia;
       this.esposicionRecienteRuido = esposicionRecienteRuido;
       this.practicasRuidosas = practicasRuidosas;
       this.pabellonDer = pabellonDer;
       this.pabellonIzq = pabellonIzq;
       this.auditivoDer = auditivoDer;
       this.auditivoIzq = auditivoIzq;
       this.timpanoDer = timpanoDer;
       this.timpanoIzq = timpanoIzq;
       this.fosasNasalesDer = fosasNasalesDer;
       this.fosasNasalesIzq = fosasNasalesIzq;
       this.conclusion = diagnostico;
       this.recomendaciones = recomendaciones;
       this.idUsuario = idUsuario;
    }
   
    public int getIdfichaaudiometria() {
        return this.idfichaaudiometria;
    }
    
    public void setIdfichaaudiometria(int idfichaaudiometria) {
        this.idfichaaudiometria = idfichaaudiometria;
    }
    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }
    
    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }
    public Boolean getOtitsCronica() {
        return this.otitsCronica;
    }
    
    public void setOtitsCronica(Boolean otitsCronica) {
        this.otitsCronica = otitsCronica;
    }
    public Boolean getOtotoxidad() {
        return this.ototoxidad;
    }
    
    public void setOtotoxidad(Boolean ototoxidad) {
        this.ototoxidad = ototoxidad;
    }
    public Boolean getTec() {
        return this.tec;
    }
    
    public void setTec(Boolean tec) {
        this.tec = tec;
    }
    public Boolean getMeningitis() {
        return this.meningitis;
    }
    
    public void setMeningitis(Boolean meningitis) {
        this.meningitis = meningitis;
    }
    public Boolean getRinitis() {
        return this.rinitis;
    }
    
    public void setRinitis(Boolean rinitis) {
        this.rinitis = rinitis;
    }
    public Boolean getParotiditis() {
        return this.parotiditis;
    }
    
    public void setParotiditis(Boolean parotiditis) {
        this.parotiditis = parotiditis;
    }
    public Boolean getSarampion() {
        return this.sarampion;
    }
    
    public void setSarampion(Boolean sarampion) {
        this.sarampion = sarampion;
    }
    public Boolean getWalkman() {
        return this.walkman;
    }
    
    public void setWalkman(Boolean walkman) {
        this.walkman = walkman;
    }
    public Boolean getTraumaAuditivo() {
        return this.traumaAuditivo;
    }
    
    public void setTraumaAuditivo(Boolean traumaAuditivo) {
        this.traumaAuditivo = traumaAuditivo;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public String getTampones() {
        return this.tampones;
    }
    
    public void setTampones(String tampones) {
        this.tampones = tampones;
    }
    public String getOrejanas() {
        return this.orejanas;
    }
    
    public void setOrejanas(String orejanas) {
        this.orejanas = orejanas;
    }
    public String getAlgodones() {
        return this.algodones;
    }
    
    public void setAlgodones(String algodones) {
        this.algodones = algodones;
    }
    public String getOtrosProtecAuric() {
        return this.otrosProtecAuric;
    }
    
    public void setOtrosProtecAuric(String otrosProtecAuric) {
        this.otrosProtecAuric = otrosProtecAuric;
    }
    public String getOcupacionalesObserv() {
        return this.ocupacionalesObserv;
    }
    
    public void setOcupacionalesObserv(String ocupacionalesObserv) {
        this.ocupacionalesObserv = ocupacionalesObserv;
    }
    public Boolean getAcufenos() {
        return this.acufenos;
    }
    
    public void setAcufenos(Boolean acufenos) {
        this.acufenos = acufenos;
    }
    public Boolean getVertigo() {
        return this.vertigo;
    }
    
    public void setVertigo(Boolean vertigo) {
        this.vertigo = vertigo;
    }
    public Boolean getHipoacusia() {
        return this.hipoacusia;
    }
    
    public void setHipoacusia(Boolean hipoacusia) {
        this.hipoacusia = hipoacusia;
    }
    public Boolean getOtalgia() {
        return this.otalgia;
    }
    
    public void setOtalgia(Boolean otalgia) {
        this.otalgia = otalgia;
    }
    public Boolean getEsposicionRecienteRuido() {
        return this.esposicionRecienteRuido;
    }
    
    public void setEsposicionRecienteRuido(Boolean esposicionRecienteRuido) {
        this.esposicionRecienteRuido = esposicionRecienteRuido;
    }
    public Boolean getPracticasRuidosas() {
        return this.practicasRuidosas;
    }
    
    public void setPracticasRuidosas(Boolean practicasRuidosas) {
        this.practicasRuidosas = practicasRuidosas;
    }
    public String getPabellonDer() {
        return this.pabellonDer;
    }
    
    public void setPabellonDer(String pabellonDer) {
        this.pabellonDer = pabellonDer;
    }
    public String getPabellonIzq() {
        return this.pabellonIzq;
    }
    
    public void setPabellonIzq(String pabellonIzq) {
        this.pabellonIzq = pabellonIzq;
    }
    public String getAuditivoDer() {
        return this.auditivoDer;
    }
    
    public void setAuditivoDer(String auditivoDer) {
        this.auditivoDer = auditivoDer;
    }
    public String getAuditivoIzq() {
        return this.auditivoIzq;
    }
    
    public void setAuditivoIzq(String auditivoIzq) {
        this.auditivoIzq = auditivoIzq;
    }
    public String getTimpanoDer() {
        return this.timpanoDer;
    }
    
    public void setTimpanoDer(String timpanoDer) {
        this.timpanoDer = timpanoDer;
    }
    public String getTimpanoIzq() {
        return this.timpanoIzq;
    }
    
    public void setTimpanoIzq(String timpanoIzq) {
        this.timpanoIzq = timpanoIzq;
    }
    public String getFosasNasalesDer() {
        return this.fosasNasalesDer;
    }
    
    public void setFosasNasalesDer(String fosasNasalesDer) {
        this.fosasNasalesDer = fosasNasalesDer;
    }
    public String getFosasNasalesIzq() {
        return this.fosasNasalesIzq;
    }
    
    public void setFosasNasalesIzq(String fosasNasalesIzq) {
        this.fosasNasalesIzq = fosasNasalesIzq;
    }
    public String getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }
    public String getRecomendaciones() {
        return this.recomendaciones;
    }
    
    public void setRecomendaciones(String recomendaciones) {
        this.recomendaciones = recomendaciones;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


