package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FichaPsicologica generated by hbm2java
 */
public class FichaPsicologica  implements java.io.Serializable {


     private int idfichapsicologica;
     private AtencionOcupacional atencionOcupacional;
     private String motivoEvaluacion;
     private String historiaFamiliar;
     private String accidenteEnfermedad;
     private String habito;
     private String otraObservacion;
     private String presentacion;
     private String postura;
     private String discursoRitmo;
     private String discursoTono;
     private String discursoArt;
     private String orientacionTiempo;
     private String orientacionEspacio;
     private String orientacionPersona;
     private String lucidoAtento;
     private String pensamiento;
     private String percepcion;
     private String memoriaCp;
     private String memoriaMp;
     private String memoriaLp;
     private String inteligencia;
     private String apetito;
     private String suenio;
     private String personalidad;
     private String afectividad;
     private String conductaSexual;
     private String dxAreaCognitiva;
     private String dxAreaEmocional;
     private Date fechaEvaluacion;
     private String condicion;
     private int idUsuario;
     private boolean examenPsicolaboral;
     private boolean examenPsicotecnico;
     private Set<PacientePrueba> pacientePruebas = new HashSet<PacientePrueba>(0);

    public FichaPsicologica() {
    }

	
    public FichaPsicologica(int idfichapsicologica, AtencionOcupacional atencionOcupacional, String tipoExamen, String motivoEvaluacion, String riesgos, String seguridad, String historiaFamiliar, String accidenteEnfermedad, String habito, String otraObservacion, String presentacion, String postura, String discursoRitmo, String discursoTono, String discursoArt, String orientacionTiempo, String orientacionEspacio, String orientacionPersona, String lucidoAtento, String pensamiento, String percepcion, String memoriaCp, String memoriaMp, String memoriaLp, String inteligencia, String apetito, String suenio, String personalidad, String afectividad, String conductaSexual, String dxAreaCognitiva, String dxAreaEmocional, Date fechaEvaluacion, String condicion, int idUsuario) {
        this.idfichapsicologica = idfichapsicologica;
        this.atencionOcupacional = atencionOcupacional;
        this.motivoEvaluacion = motivoEvaluacion;
        this.historiaFamiliar = historiaFamiliar;
        this.accidenteEnfermedad = accidenteEnfermedad;
        this.habito = habito;
        this.otraObservacion = otraObservacion;
        this.presentacion = presentacion;
        this.postura = postura;
        this.discursoRitmo = discursoRitmo;
        this.discursoTono = discursoTono;
        this.discursoArt = discursoArt;
        this.orientacionTiempo = orientacionTiempo;
        this.orientacionEspacio = orientacionEspacio;
        this.orientacionPersona = orientacionPersona;
        this.lucidoAtento = lucidoAtento;
        this.pensamiento = pensamiento;
        this.percepcion = percepcion;
        this.memoriaCp = memoriaCp;
        this.memoriaMp = memoriaMp;
        this.memoriaLp = memoriaLp;
        this.inteligencia = inteligencia;
        this.apetito = apetito;
        this.suenio = suenio;
        this.personalidad = personalidad;
        this.afectividad = afectividad;
        this.conductaSexual = conductaSexual;
        this.dxAreaCognitiva = dxAreaCognitiva;
        this.dxAreaEmocional = dxAreaEmocional;
        this.fechaEvaluacion = fechaEvaluacion;
        this.condicion = condicion;
        this.idUsuario = idUsuario;
    }
    public FichaPsicologica(int idfichapsicologica, AtencionOcupacional atencionOcupacional, String tipoExamen, String motivoEvaluacion, String riesgos, String seguridad, String historiaFamiliar, String accidenteEnfermedad, String habito, String otraObservacion, String presentacion, String postura, String discursoRitmo, String discursoTono, String discursoArt, String orientacionTiempo, String orientacionEspacio, String orientacionPersona, String lucidoAtento, String pensamiento, String percepcion, String memoriaCp, String memoriaMp, String memoriaLp, String inteligencia, String apetito, String suenio, String personalidad, String afectividad, String conductaSexual, String dxAreaCognitiva, String dxAreaEmocional, Date fechaEvaluacion, String condicion, int idUsuario, Set<PacientePrueba> pacientePruebas) {
       this.idfichapsicologica = idfichapsicologica;
       this.atencionOcupacional = atencionOcupacional;
       this.motivoEvaluacion = motivoEvaluacion;
       this.historiaFamiliar = historiaFamiliar;
       this.accidenteEnfermedad = accidenteEnfermedad;
       this.habito = habito;
       this.otraObservacion = otraObservacion;
       this.presentacion = presentacion;
       this.postura = postura;
       this.discursoRitmo = discursoRitmo;
       this.discursoTono = discursoTono;
       this.discursoArt = discursoArt;
       this.orientacionTiempo = orientacionTiempo;
       this.orientacionEspacio = orientacionEspacio;
       this.orientacionPersona = orientacionPersona;
       this.lucidoAtento = lucidoAtento;
       this.pensamiento = pensamiento;
       this.percepcion = percepcion;
       this.memoriaCp = memoriaCp;
       this.memoriaMp = memoriaMp;
       this.memoriaLp = memoriaLp;
       this.inteligencia = inteligencia;
       this.apetito = apetito;
       this.suenio = suenio;
       this.personalidad = personalidad;
       this.afectividad = afectividad;
       this.conductaSexual = conductaSexual;
       this.dxAreaCognitiva = dxAreaCognitiva;
       this.dxAreaEmocional = dxAreaEmocional;
       this.fechaEvaluacion = fechaEvaluacion;
       this.condicion = condicion;
       this.idUsuario = idUsuario;
       this.pacientePruebas = pacientePruebas;
    }
   
    public int getIdfichapsicologica() {
        return this.idfichapsicologica;
    }
    
    public void setIdfichapsicologica(int idfichapsicologica) {
        this.idfichapsicologica = idfichapsicologica;
    }
    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }
    
    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }
    public String getMotivoEvaluacion() {
        return this.motivoEvaluacion;
    }
    
    public void setMotivoEvaluacion(String motivoEvaluacion) {
        this.motivoEvaluacion = motivoEvaluacion;
    }
    public String getHistoriaFamiliar() {
        return this.historiaFamiliar;
    }
    
    public void setHistoriaFamiliar(String historiaFamiliar) {
        this.historiaFamiliar = historiaFamiliar;
    }
    public String getAccidenteEnfermedad() {
        return this.accidenteEnfermedad;
    }
    
    public void setAccidenteEnfermedad(String accidenteEnfermedad) {
        this.accidenteEnfermedad = accidenteEnfermedad;
    }
    public String getHabito() {
        return this.habito;
    }
    
    public void setHabito(String habito) {
        this.habito = habito;
    }
    public String getOtraObservacion() {
        return this.otraObservacion;
    }
    
    public void setOtraObservacion(String otraObservacion) {
        this.otraObservacion = otraObservacion;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public String getPostura() {
        return this.postura;
    }
    
    public void setPostura(String postura) {
        this.postura = postura;
    }
    public String getDiscursoRitmo() {
        return this.discursoRitmo;
    }
    
    public void setDiscursoRitmo(String discursoRitmo) {
        this.discursoRitmo = discursoRitmo;
    }
    public String getDiscursoTono() {
        return this.discursoTono;
    }
    
    public void setDiscursoTono(String discursoTono) {
        this.discursoTono = discursoTono;
    }
    public String getDiscursoArt() {
        return this.discursoArt;
    }
    
    public void setDiscursoArt(String discursoArt) {
        this.discursoArt = discursoArt;
    }
    public String getOrientacionTiempo() {
        return this.orientacionTiempo;
    }
    
    public void setOrientacionTiempo(String orientacionTiempo) {
        this.orientacionTiempo = orientacionTiempo;
    }
    public String getOrientacionEspacio() {
        return this.orientacionEspacio;
    }
    
    public void setOrientacionEspacio(String orientacionEspacio) {
        this.orientacionEspacio = orientacionEspacio;
    }
    public String getOrientacionPersona() {
        return this.orientacionPersona;
    }
    
    public void setOrientacionPersona(String orientacionPersona) {
        this.orientacionPersona = orientacionPersona;
    }
    public String getLucidoAtento() {
        return this.lucidoAtento;
    }
    
    public void setLucidoAtento(String lucidoAtento) {
        this.lucidoAtento = lucidoAtento;
    }
    public String getPensamiento() {
        return this.pensamiento;
    }
    
    public void setPensamiento(String pensamiento) {
        this.pensamiento = pensamiento;
    }
    public String getPercepcion() {
        return this.percepcion;
    }
    
    public void setPercepcion(String percepcion) {
        this.percepcion = percepcion;
    }
    public String getMemoriaCp() {
        return this.memoriaCp;
    }
    
    public void setMemoriaCp(String memoriaCp) {
        this.memoriaCp = memoriaCp;
    }
    public String getMemoriaMp() {
        return this.memoriaMp;
    }
    
    public void setMemoriaMp(String memoriaMp) {
        this.memoriaMp = memoriaMp;
    }
    public String getMemoriaLp() {
        return this.memoriaLp;
    }
    
    public void setMemoriaLp(String memoriaLp) {
        this.memoriaLp = memoriaLp;
    }
    public String getInteligencia() {
        return this.inteligencia;
    }
    
    public void setInteligencia(String inteligencia) {
        this.inteligencia = inteligencia;
    }
    public String getApetito() {
        return this.apetito;
    }
    
    public void setApetito(String apetito) {
        this.apetito = apetito;
    }
    public String getSuenio() {
        return this.suenio;
    }
    
    public void setSuenio(String suenio) {
        this.suenio = suenio;
    }
    public String getPersonalidad() {
        return this.personalidad;
    }
    
    public void setPersonalidad(String personalidad) {
        this.personalidad = personalidad;
    }
    public String getAfectividad() {
        return this.afectividad;
    }
    
    public void setAfectividad(String afectividad) {
        this.afectividad = afectividad;
    }
    public String getConductaSexual() {
        return this.conductaSexual;
    }
    
    public void setConductaSexual(String conductaSexual) {
        this.conductaSexual = conductaSexual;
    }
    public String getDxAreaCognitiva() {
        return this.dxAreaCognitiva;
    }
    
    public void setDxAreaCognitiva(String dxAreaCognitiva) {
        this.dxAreaCognitiva = dxAreaCognitiva;
    }
    public String getDxAreaEmocional() {
        return this.dxAreaEmocional;
    }
    
    public void setDxAreaEmocional(String dxAreaEmocional) {
        this.dxAreaEmocional = dxAreaEmocional;
    }
    public Date getFechaEvaluacion() {
        return this.fechaEvaluacion;
    }
    
    public void setFechaEvaluacion(Date fechaEvaluacion) {
        this.fechaEvaluacion = fechaEvaluacion;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set<PacientePrueba> getPacientePruebas() {
        return this.pacientePruebas;
    }
    
    public void setPacientePruebas(Set<PacientePrueba> pacientePruebas) {
        this.pacientePruebas = pacientePruebas;
    }

    public boolean isExamenPsicolaboral() {
        return examenPsicolaboral;
    }

    public void setExamenPsicolaboral(boolean examenPsicolaboral) {
        this.examenPsicolaboral = examenPsicolaboral;
    }

    public boolean isExamenPsicotecnico() {
        return examenPsicotecnico;
    }

    public void setExamenPsicotecnico(boolean examenPsicotecnico) {
        this.examenPsicotecnico = examenPsicotecnico;
    }




}


