package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * FichaPsicologicaPsicotecnico generated by hbm2java
 */
public class FichaPsicologicaPsicotecnico  implements java.io.Serializable {


     private int idfichapsicologicapsicotecnico;
     private AtencionOcupacional atencionOcupacional;
     private String motivoEvaluacion;
     private String presentacion;
     private String postura;
     private String discursoRitmo;
     private String discursoTono;
     private String discursoArticulacion;
     private String orientacionTiempo;
     private String orientacionEspacio;
     private String orientacionPersona;
     private String nivelIntelectual;
     private String coordinacionVisomotriz;
     private String nivelMemoria;
     private String personalidad;
     private String afectividad;
     private String conAreaCognitiva;
     private String conAreaEmocional;
     private String recomendacion;
     private String condicion;
     private int idUsuario;

    public FichaPsicologicaPsicotecnico() {
    }

    public FichaPsicologicaPsicotecnico(int idfichapsicologicapsicotecnico, AtencionOcupacional atencionOcupacional, String motivoEvaluacion, String presentacion, String postura, String discursoRitmo, String discursoTono, String discursoArticulacion, String orientacionTiempo, String orientacionEspacio, String orientacionPersona, String nivelIntelectual, String coordinacionVisomotriz, String nivelMemoria, String personalidad, String afectividad, String conAreaCognitiva, String conAreaEmocional, String recomendacion, String condicion, int idUsuario) {
       this.idfichapsicologicapsicotecnico = idfichapsicologicapsicotecnico;
       this.atencionOcupacional = atencionOcupacional;
       this.motivoEvaluacion = motivoEvaluacion;
       this.presentacion = presentacion;
       this.postura = postura;
       this.discursoRitmo = discursoRitmo;
       this.discursoTono = discursoTono;
       this.discursoArticulacion = discursoArticulacion;
       this.orientacionTiempo = orientacionTiempo;
       this.orientacionEspacio = orientacionEspacio;
       this.orientacionPersona = orientacionPersona;
       this.nivelIntelectual = nivelIntelectual;
       this.coordinacionVisomotriz = coordinacionVisomotriz;
       this.nivelMemoria = nivelMemoria;
       this.personalidad = personalidad;
       this.afectividad = afectividad;
       this.conAreaCognitiva = conAreaCognitiva;
       this.conAreaEmocional = conAreaEmocional;
       this.recomendacion = recomendacion;
       this.condicion = condicion;
       this.idUsuario = idUsuario;
    }
   
    public int getIdfichapsicologicapsicotecnico() {
        return this.idfichapsicologicapsicotecnico;
    }
    
    public void setIdfichapsicologicapsicotecnico(int idfichapsicologicapsicotecnico) {
        this.idfichapsicologicapsicotecnico = idfichapsicologicapsicotecnico;
    }
    public AtencionOcupacional getAtencionOcupacional() {
        return this.atencionOcupacional;
    }
    
    public void setAtencionOcupacional(AtencionOcupacional atencionOcupacional) {
        this.atencionOcupacional = atencionOcupacional;
    }
    public String getMotivoEvaluacion() {
        return this.motivoEvaluacion;
    }
    
    public void setMotivoEvaluacion(String motivoEvaluacion) {
        this.motivoEvaluacion = motivoEvaluacion;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public String getPostura() {
        return this.postura;
    }
    
    public void setPostura(String postura) {
        this.postura = postura;
    }
    public String getDiscursoRitmo() {
        return this.discursoRitmo;
    }
    
    public void setDiscursoRitmo(String discursoRitmo) {
        this.discursoRitmo = discursoRitmo;
    }
    public String getDiscursoTono() {
        return this.discursoTono;
    }
    
    public void setDiscursoTono(String discursoTono) {
        this.discursoTono = discursoTono;
    }
    public String getDiscursoArticulacion() {
        return this.discursoArticulacion;
    }
    
    public void setDiscursoArticulacion(String discursoArticulacion) {
        this.discursoArticulacion = discursoArticulacion;
    }
    public String getOrientacionTiempo() {
        return this.orientacionTiempo;
    }
    
    public void setOrientacionTiempo(String orientacionTiempo) {
        this.orientacionTiempo = orientacionTiempo;
    }
    public String getOrientacionEspacio() {
        return this.orientacionEspacio;
    }
    
    public void setOrientacionEspacio(String orientacionEspacio) {
        this.orientacionEspacio = orientacionEspacio;
    }
    public String getOrientacionPersona() {
        return this.orientacionPersona;
    }
    
    public void setOrientacionPersona(String orientacionPersona) {
        this.orientacionPersona = orientacionPersona;
    }
    public String getNivelIntelectual() {
        return this.nivelIntelectual;
    }
    
    public void setNivelIntelectual(String nivelIntelectual) {
        this.nivelIntelectual = nivelIntelectual;
    }
    public String getCoordinacionVisomotriz() {
        return this.coordinacionVisomotriz;
    }
    
    public void setCoordinacionVisomotriz(String coordinacionVisomotriz) {
        this.coordinacionVisomotriz = coordinacionVisomotriz;
    }
    public String getNivelMemoria() {
        return this.nivelMemoria;
    }
    
    public void setNivelMemoria(String nivelMemoria) {
        this.nivelMemoria = nivelMemoria;
    }
    public String getPersonalidad() {
        return this.personalidad;
    }
    
    public void setPersonalidad(String personalidad) {
        this.personalidad = personalidad;
    }
    public String getAfectividad() {
        return this.afectividad;
    }
    
    public void setAfectividad(String afectividad) {
        this.afectividad = afectividad;
    }
    public String getConAreaCognitiva() {
        return this.conAreaCognitiva;
    }
    
    public void setConAreaCognitiva(String conAreaCognitiva) {
        this.conAreaCognitiva = conAreaCognitiva;
    }
    public String getConAreaEmocional() {
        return this.conAreaEmocional;
    }
    
    public void setConAreaEmocional(String conAreaEmocional) {
        this.conAreaEmocional = conAreaEmocional;
    }
    public String getRecomendacion() {
        return this.recomendacion;
    }
    
    public void setRecomendacion(String recomendacion) {
        this.recomendacion = recomendacion;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


