package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FondoSolidaridad generated by hbm2java
 */
public class FondoSolidaridad  implements java.io.Serializable {


     private int idFondoSolidaridad;
     private Persona persona;
     private Date fechaReg;
     private Boolean estado;
     private BigDecimal importe;
     private Set<ServicioFondoSolidaridad> servicioFondoSolidaridads = new HashSet<ServicioFondoSolidaridad>(0);
     private Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads = new HashSet<ServiciosFondoSolidaridad>(0);
     private Set<HistorialAtencionFps> historialAtencionFpses = new HashSet<HistorialAtencionFps>(0);

    public FondoSolidaridad() {
    }

	
    public FondoSolidaridad(int idFondoSolidaridad) {
        this.idFondoSolidaridad = idFondoSolidaridad;
    }
    public FondoSolidaridad(int idFondoSolidaridad, Persona persona, Date fechaReg, Boolean estado, BigDecimal importe, Set<ServicioFondoSolidaridad> servicioFondoSolidaridads) {
       this.idFondoSolidaridad = idFondoSolidaridad;
       this.persona = persona;
       this.fechaReg = fechaReg;
       this.estado = estado;
       this.importe = importe;
       this.servicioFondoSolidaridads = servicioFondoSolidaridads;
    }
   
    public int getIdFondoSolidaridad() {
        return this.idFondoSolidaridad;
    }
    
    public void setIdFondoSolidaridad(int idFondoSolidaridad) {
        this.idFondoSolidaridad = idFondoSolidaridad;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Set<ServicioFondoSolidaridad> getServicioFondoSolidaridads() {
        return this.servicioFondoSolidaridads;
    }
    
    public void setServicioFondoSolidaridads(Set<ServicioFondoSolidaridad> servicioFondoSolidaridads) {
        this.servicioFondoSolidaridads = servicioFondoSolidaridads;
    }

    public Set<ServiciosFondoSolidaridad> getServiciosFondoSolidaridads() {
        return serviciosFondoSolidaridads;
    }

    public void setServiciosFondoSolidaridads(Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads) {
        this.serviciosFondoSolidaridads = serviciosFondoSolidaridads;
    }

    public Set<HistorialAtencionFps> getHistorialAtencionFpses() {
        return historialAtencionFpses;
    }

    public void setHistorialAtencionFpses(Set<HistorialAtencionFps> historialAtencionFpses) {
        this.historialAtencionFpses = historialAtencionFpses;
    }




}


