package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * FuncionVital generated by hbm2java
 */
public class FuncionVital  implements java.io.Serializable {


     private int idfuncionvital;
     private Atencion atencion;
     private Integer presionArterial;
     private Integer presionArterial2;
     private Double temperatura;
     private Double r;
     private Double p;
     private Double peso;
     private Double talla;
     private Double imc;

    public FuncionVital() {
    }

	
    public FuncionVital(int idfuncionvital) {
        this.idfuncionvital = idfuncionvital;
    }
    public FuncionVital(int idfuncionvital, Atencion atencion, Integer presionArterial, Integer presionArterial2, Double temperatura, Double r, Double p, Double peso, Double talla, Double imc) {
       this.idfuncionvital = idfuncionvital;
       this.atencion = atencion;
       this.presionArterial = presionArterial;
       this.presionArterial2 = presionArterial2;
       this.temperatura = temperatura;
       this.r = r;
       this.p = p;
       this.peso = peso;
       this.talla = talla;
       this.imc = imc;
    }
   
    public int getIdfuncionvital() {
        return this.idfuncionvital;
    }
    
    public void setIdfuncionvital(int idfuncionvital) {
        this.idfuncionvital = idfuncionvital;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public Integer getPresionArterial() {
        return this.presionArterial;
    }
    
    public void setPresionArterial(Integer presionArterial) {
        this.presionArterial = presionArterial;
    }
    public Integer getPresionArterial2() {
        return this.presionArterial2;
    }
    
    public void setPresionArterial2(Integer presionArterial2) {
        this.presionArterial2 = presionArterial2;
    }
    public Double getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(Double temperatura) {
        this.temperatura = temperatura;
    }
    public Double getR() {
        return this.r;
    }
    
    public void setR(Double r) {
        this.r = r;
    }
    public Double getP() {
        return this.p;
    }
    
    public void setP(Double p) {
        this.p = p;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getTalla() {
        return this.talla;
    }
    
    public void setTalla(Double talla) {
        this.talla = talla;
    }
    public Double getImc() {
        return this.imc;
    }
    
    public void setImc(Double imc) {
        this.imc = imc;
    }




}


