package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HabitoNocivo generated by hbm2java
 */
public class HabitoNocivo implements java.io.Serializable {

    private int idhabitonocivo;
    private String habito;
    private boolean estado;
    private Set<SoFmoHabitos> soFmoHabitoses = new HashSet<SoFmoHabitos>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public HabitoNocivo() {
    }

    public HabitoNocivo(int idhabitonocivo, String habito, boolean estado) {
        this.idhabitonocivo = idhabitonocivo;
        this.habito = habito;
        this.estado = estado;
    }

    public HabitoNocivo(int idhabitonocivo, String habito, boolean estado, Set<SoFmoHabitos> soFmoHabitoses) {
        this.idhabitonocivo = idhabitonocivo;
        this.habito = habito;
        this.estado = estado;
        this.soFmoHabitoses = soFmoHabitoses;
    }

    public int getIdhabitonocivo() {
        return this.idhabitonocivo;
    }

    public void setIdhabitonocivo(int idhabitonocivo) {
        this.idhabitonocivo = idhabitonocivo;
    }

    public String getHabito() {
        return this.habito;
    }

    public void setHabito(String habito) {
        this.habito = habito;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Set<SoFmoHabitos> getSoFmoHabitoses() {
        return this.soFmoHabitoses;
    }

    public void setSoFmoHabitoses(Set<SoFmoHabitos> soFmoHabitoses) {
        this.soFmoHabitoses = soFmoHabitoses;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getHabito();
            default:
                return "<SELECCIONE>";
        }
    }

}
