package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HistorialAtencionFps generated by hbm2java
 */
public class HistorialAtencionFps  implements java.io.Serializable {


     private int idhistorialatencionfps;
     private FondoSolidaridad fondoSolidaridad;
     private int idPaqueteFps;
     private int idServicioFps;
     private int idVenta;
     private BigDecimal montoDisponible;
     private int cantDisponible;
     private BigDecimal montoUtilizado;
     private BigDecimal saldo;
     private long numRegistro;

    public HistorialAtencionFps() {
    }

    public HistorialAtencionFps(int idhistorialatencionfps, FondoSolidaridad fondoSolidaridad, int idPaqueteFps, int idServicioFps, int idVenta, BigDecimal montoDisponible, int cantDisponible, BigDecimal montoUtilizado, BigDecimal saldo, long numRegistro) {
       this.idhistorialatencionfps = idhistorialatencionfps;
       this.fondoSolidaridad = fondoSolidaridad;
       this.idPaqueteFps = idPaqueteFps;
       this.idServicioFps = idServicioFps;
       this.idVenta = idVenta;
       this.montoDisponible = montoDisponible;
       this.cantDisponible = cantDisponible;
       this.montoUtilizado = montoUtilizado;
       this.saldo = saldo;
       this.numRegistro = numRegistro;
    }
   
    public int getIdhistorialatencionfps() {
        return this.idhistorialatencionfps;
    }
    
    public void setIdhistorialatencionfps(int idhistorialatencionfps) {
        this.idhistorialatencionfps = idhistorialatencionfps;
    }
    public FondoSolidaridad getFondoSolidaridad() {
        return this.fondoSolidaridad;
    }
    
    public void setFondoSolidaridad(FondoSolidaridad fondoSolidaridad) {
        this.fondoSolidaridad = fondoSolidaridad;
    }
    public int getIdPaqueteFps() {
        return this.idPaqueteFps;
    }
    
    public void setIdPaqueteFps(int idPaqueteFps) {
        this.idPaqueteFps = idPaqueteFps;
    }
    public int getIdServicioFps() {
        return this.idServicioFps;
    }
    
    public void setIdServicioFps(int idServicioFps) {
        this.idServicioFps = idServicioFps;
    }
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public BigDecimal getMontoDisponible() {
        return this.montoDisponible;
    }
    
    public void setMontoDisponible(BigDecimal montoDisponible) {
        this.montoDisponible = montoDisponible;
    }
    public int getCantDisponible() {
        return this.cantDisponible;
    }
    
    public void setCantDisponible(int cantDisponible) {
        this.cantDisponible = cantDisponible;
    }
    public BigDecimal getMontoUtilizado() {
        return this.montoUtilizado;
    }
    
    public void setMontoUtilizado(BigDecimal montoUtilizado) {
        this.montoUtilizado = montoUtilizado;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public long getNumRegistro() {
        return this.numRegistro;
    }
    
    public void setNumRegistro(long numRegistro) {
        this.numRegistro = numRegistro;
    }




}


