package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemsComprobante generated by hbm2java
 */
public class ItemsComprobante  implements java.io.Serializable {


     private long iditemcomprobante;
     private Beneficio beneficio;
     private Comprobante comprobante;
     private Medico medicoByIdMedicoDeriva;
     private Medico medicoByIdMedicoAtiende;
     private Procedimiento procedimiento;
     private BigDecimal montoProcedimiento;
     private String concepto;
     private Boolean estado;
     private BigDecimal montoAtencion;
     private BigDecimal montoDerivacion;
     private BigDecimal montoPagado;
     private BigDecimal importeAdicional;
     private String observacion;
     private int porcCubierto;
     private BigDecimal montoCubierto;
     private BigDecimal montoCubiertoSoles;
     private Set<ServicioFondoSolidaridad> servicioFondoSolidaridads = new HashSet<ServicioFondoSolidaridad>(0);
     private Set<MedicoDerivaAtiende> medicoDerivaAtiendes = new HashSet<MedicoDerivaAtiende>(0);

    public ItemsComprobante() {
    }

	
    public ItemsComprobante(long iditemcomprobante, int porcCubierto, BigDecimal montoCubierto) {
        this.iditemcomprobante = iditemcomprobante;
        this.porcCubierto = porcCubierto;
        this.montoCubierto = montoCubierto;
    }
    public ItemsComprobante(long iditemcomprobante, Beneficio beneficio, Comprobante comprobante, Medico medicoByIdMedicoDeriva, Medico medicoByIdMedicoAtiende, Procedimiento procedimiento, BigDecimal montoProcedimiento, String concepto, Boolean estado, BigDecimal montoAtencion, BigDecimal montoDerivacion, BigDecimal montoPagado, BigDecimal importeAdicional, String observacion, int porcCubierto, BigDecimal montoCubierto, BigDecimal montoCubiertoSoles, Set<ServicioFondoSolidaridad> servicioFondoSolidaridads, Set<MedicoDerivaAtiende> medicoDerivaAtiendes) {
       this.iditemcomprobante = iditemcomprobante;
       this.beneficio = beneficio;
       this.comprobante = comprobante;
       this.medicoByIdMedicoDeriva = medicoByIdMedicoDeriva;
       this.medicoByIdMedicoAtiende = medicoByIdMedicoAtiende;
       this.procedimiento = procedimiento;
       this.montoProcedimiento = montoProcedimiento;
       this.concepto = concepto;
       this.estado = estado;
       this.montoAtencion = montoAtencion;
       this.montoDerivacion = montoDerivacion;
       this.montoPagado = montoPagado;
       this.importeAdicional = importeAdicional;
       this.observacion = observacion;
       this.porcCubierto = porcCubierto;
       this.montoCubierto = montoCubierto;
       this.montoCubiertoSoles = montoCubiertoSoles;
       this.servicioFondoSolidaridads = servicioFondoSolidaridads;
       this.medicoDerivaAtiendes = medicoDerivaAtiendes;
    }
   
    public long getIditemcomprobante() {
        return this.iditemcomprobante;
    }
    
    public void setIditemcomprobante(long iditemcomprobante) {
        this.iditemcomprobante = iditemcomprobante;
    }
    public Beneficio getBeneficio() {
        return this.beneficio;
    }
    
    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Medico getMedicoByIdMedicoDeriva() {
        return this.medicoByIdMedicoDeriva;
    }
    
    public void setMedicoByIdMedicoDeriva(Medico medicoByIdMedicoDeriva) {
        this.medicoByIdMedicoDeriva = medicoByIdMedicoDeriva;
    }
    public Medico getMedicoByIdMedicoAtiende() {
        return this.medicoByIdMedicoAtiende;
    }
    
    public void setMedicoByIdMedicoAtiende(Medico medicoByIdMedicoAtiende) {
        this.medicoByIdMedicoAtiende = medicoByIdMedicoAtiende;
    }
    public Procedimiento getProcedimiento() {
        return this.procedimiento;
    }
    
    public void setProcedimiento(Procedimiento procedimiento) {
        this.procedimiento = procedimiento;
    }
    public BigDecimal getMontoProcedimiento() {
        return this.montoProcedimiento;
    }
    
    public void setMontoProcedimiento(BigDecimal montoProcedimiento) {
        this.montoProcedimiento = montoProcedimiento;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public BigDecimal getMontoAtencion() {
        return this.montoAtencion;
    }
    
    public void setMontoAtencion(BigDecimal montoAtencion) {
        this.montoAtencion = montoAtencion;
    }
    public BigDecimal getMontoDerivacion() {
        return this.montoDerivacion;
    }
    
    public void setMontoDerivacion(BigDecimal montoDerivacion) {
        this.montoDerivacion = montoDerivacion;
    }
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public BigDecimal getImporteAdicional() {
        return this.importeAdicional;
    }
    
    public void setImporteAdicional(BigDecimal importeAdicional) {
        this.importeAdicional = importeAdicional;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getPorcCubierto() {
        return this.porcCubierto;
    }
    
    public void setPorcCubierto(int porcCubierto) {
        this.porcCubierto = porcCubierto;
    }
    public BigDecimal getMontoCubierto() {
        return this.montoCubierto;
    }
    
    public void setMontoCubierto(BigDecimal montoCubierto) {
        this.montoCubierto = montoCubierto;
    }
    public BigDecimal getMontoCubiertoSoles() {
        return this.montoCubiertoSoles;
    }
    
    public void setMontoCubiertoSoles(BigDecimal montoCubiertoSoles) {
        this.montoCubiertoSoles = montoCubiertoSoles;
    }
    public Set<ServicioFondoSolidaridad> getServicioFondoSolidaridads() {
        return this.servicioFondoSolidaridads;
    }
    
    public void setServicioFondoSolidaridads(Set<ServicioFondoSolidaridad> servicioFondoSolidaridads) {
        this.servicioFondoSolidaridads = servicioFondoSolidaridads;
    }
    public Set<MedicoDerivaAtiende> getMedicoDerivaAtiendes() {
        return this.medicoDerivaAtiendes;
    }
    
    public void setMedicoDerivaAtiendes(Set<MedicoDerivaAtiende> medicoDerivaAtiendes) {
        this.medicoDerivaAtiendes = medicoDerivaAtiendes;
    }




}


