package lissa.be;
// Generated 23-sep-2016 12:43:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kardex generated by hbm2java
 */
public class Kardex  implements java.io.Serializable {


     private int idkardex;
     private Almacen almacenByIdOrigen;
     private Almacen almacenByIdDestino;
     private Almacen almacenByIdAlmacenAfectado;
     private int idFarcomprobante;
     private String operacion;
     private String tipoOperacion;
     private Date fechaMov;
     private String horaMov;
     private String comprobante;
     private long numComprobante;
     private String numSerie;
     private String personaOrigen;
     private String PersonaDestino;
     private String observacion;
     private int grupoNumeracion;
     private Set<DetalleKardex> detalleKardexes = new HashSet<DetalleKardex>(0);

    public Kardex() {
    }

	
    public Kardex(int idkardex, Almacen almacenByIdOrigen, Almacen almacenByIdDestino, int idComprobante, String operacion, Date fechaMov, String horaMov) {
        this.idkardex = idkardex;
        this.almacenByIdOrigen = almacenByIdOrigen;
        this.almacenByIdDestino = almacenByIdDestino;
        this.idFarcomprobante = idComprobante;
        this.operacion = operacion;
        this.fechaMov = fechaMov;
        this.horaMov = horaMov;
    }
    public Kardex(int idkardex, Almacen almacenByIdOrigen, Almacen almacenByIdDestino, int idComprobante, String operacion, Date fechaMov, String horaMov, Set<DetalleKardex> detalleKardexes) {
       this.idkardex = idkardex;
       this.almacenByIdOrigen = almacenByIdOrigen;
       this.almacenByIdDestino = almacenByIdDestino;
       this.idFarcomprobante = idComprobante;
       this.operacion = operacion;
       this.fechaMov = fechaMov;
       this.horaMov = horaMov;
       this.detalleKardexes = detalleKardexes;
    }
   
    public int getIdkardex() {
        return this.idkardex;
    }
    
    public void setIdkardex(int idkardex) {
        this.idkardex = idkardex;
    }
    public Almacen getAlmacenByIdOrigen() {
        return this.almacenByIdOrigen;
    }
    
    public void setAlmacenByIdOrigen(Almacen almacenByIdOrigen) {
        this.almacenByIdOrigen = almacenByIdOrigen;
    }
    public Almacen getAlmacenByIdDestino() {
        return this.almacenByIdDestino;
    }
    
    public void setAlmacenByIdDestino(Almacen almacenByIdDestino) {
        this.almacenByIdDestino = almacenByIdDestino;
    }
    public int getIdFarcomprobante() {
        return this.idFarcomprobante;
    }
    
    public void setIdFarcomprobante(int idFarcomprobante) {
        this.idFarcomprobante = idFarcomprobante;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
    public Date getFechaMov() {
        return this.fechaMov;
    }
    
    public void setFechaMov(Date fechaMov) {
        this.fechaMov = fechaMov;
    }
    public String getHoraMov() {
        return this.horaMov;
    }
    
    public void setHoraMov(String horaMov) {
        this.horaMov = horaMov;
    }
    public Set<DetalleKardex> getDetalleKardexes() {
        return this.detalleKardexes;
    }
    
    public void setDetalleKardexes(Set<DetalleKardex> detalleKardexes) {
        this.detalleKardexes = detalleKardexes;
    }

    public Almacen getAlmacenByIdAlmacenAfectado() {
        return almacenByIdAlmacenAfectado;
    }

    public void setAlmacenByIdAlmacenAfectado(Almacen almacenByIdAlmacenAfectado) {
        this.almacenByIdAlmacenAfectado = almacenByIdAlmacenAfectado;
    }

    public String getTipoOperacion() {
        return tipoOperacion;
    }

    public void setTipoOperacion(String tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

    public String getComprobante() {
        return comprobante;
    }

    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }

    public long getNumComprobante() {
        return numComprobante;
    }

    public void setNumComprobante(long numComprobante) {
        this.numComprobante = numComprobante;
    }

    public String getNumSerie() {
        return numSerie;
    }

    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }

    public String getPersonaOrigen() {
        return personaOrigen;
    }

    public void setPersonaOrigen(String personaOrigen) {
        this.personaOrigen = personaOrigen;
    }

    public String getPersonaDestino() {
        return PersonaDestino;
    }

    public void setPersonaDestino(String PersonaDestino) {
        this.PersonaDestino = PersonaDestino;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public int getGrupoNumeracion() {
        return grupoNumeracion;
    }

    public void setGrupoNumeracion(int grupoNumeracion) {
        this.grupoNumeracion = grupoNumeracion;
    }




}


