package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1



/**
 * MedicoEspecialidad generated by hbm2java
 */
public class MedicoEspecialidad  implements java.io.Serializable {


     private int idmedicoespecialidad;
     private Especialidad especialidad;
     private Medico medico;

    public MedicoEspecialidad() {
    }

    public MedicoEspecialidad(int idmedicoespecialidad, Especialidad especialidad, Medico medico) {
       this.idmedicoespecialidad = idmedicoespecialidad;
       this.especialidad = especialidad;
       this.medico = medico;
    }
   
    public int getIdmedicoespecialidad() {
        return this.idmedicoespecialidad;
    }
    
    public void setIdmedicoespecialidad(int idmedicoespecialidad) {
        this.idmedicoespecialidad = idmedicoespecialidad;
    }
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }




}


