package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MedicoDerivaAtiende generated by hbm2java
 */
public class MedicoDerivaAtiende  implements java.io.Serializable {


     private int idmedicoderivaatiende;
     private ItemsComprobante itemsComprobante;
     private Medico medico;
     private BigDecimal monto;
     private String estadoPago;
     private String tipoMedico;
     private int idCajaafecto;

    public MedicoDerivaAtiende() {
    }

    public MedicoDerivaAtiende(int idmedicoderivaatiende, ItemsComprobante itemsComprobante, Medico medico, BigDecimal monto, String estadoPago, String tipoMedico, int idCajaafecto) {
       this.idmedicoderivaatiende = idmedicoderivaatiende;
       this.itemsComprobante = itemsComprobante;
       this.medico = medico;
       this.monto = monto;
       this.estadoPago = estadoPago;
       this.tipoMedico = tipoMedico;
       this.idCajaafecto = idCajaafecto;
    }
   
    public int getIdmedicoderivaatiende() {
        return this.idmedicoderivaatiende;
    }
    
    public void setIdmedicoderivaatiende(int idmedicoderivaatiende) {
        this.idmedicoderivaatiende = idmedicoderivaatiende;
    }
    public ItemsComprobante getItemsComprobante() {
        return this.itemsComprobante;
    }
    
    public void setItemsComprobante(ItemsComprobante itemsComprobante) {
        this.itemsComprobante = itemsComprobante;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }
    public String getTipoMedico() {
        return this.tipoMedico;
    }
    
    public void setTipoMedico(String tipoMedico) {
        this.tipoMedico = tipoMedico;
    }
    public int getIdCajaafecto() {
        return this.idCajaafecto;
    }
    
    public void setIdCajaafecto(int idCajaafecto) {
        this.idCajaafecto = idCajaafecto;
    }




}


