package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoObservacion generated by hbm2java
 */
public class MotivoObservacion implements java.io.Serializable {

    private long idmotivoobservacion;
    private ExamenOcupacional examenOcupacional;
    private String descripcion;
    private Set<CertMedicoOcupacional> certMedicoOcupacionals = new HashSet<CertMedicoOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public MotivoObservacion() {
    }

    public MotivoObservacion(long idotivoobservacion, ExamenOcupacional examenOcupacional, String descripcion) {
        this.idmotivoobservacion = idotivoobservacion;
        this.examenOcupacional = examenOcupacional;
        this.descripcion = descripcion;
    }

    public MotivoObservacion(long idotivoobservacion, ExamenOcupacional examenOcupacional, String descripcion, Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.idmotivoobservacion = idotivoobservacion;
        this.examenOcupacional = examenOcupacional;
        this.descripcion = descripcion;
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public long getIdmotivoobservacion() {
        return this.idmotivoobservacion;
    }

    public void setIdmotivoobservacion(long idmotivoobservacion) {
        this.idmotivoobservacion = idmotivoobservacion;
    }

    public ExamenOcupacional getExamenOcupacional() {
        return this.examenOcupacional;
    }

    public void setExamenOcupacional(ExamenOcupacional examenOcupacional) {
        this.examenOcupacional = examenOcupacional;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<CertMedicoOcupacional> getCertMedicoOcupacionals() {
        return this.certMedicoOcupacionals;
    }

    public void setCertMedicoOcupacionals(Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDescripcion();
            default:
                return "<SELECCIONE>";
        }
    }

}
