package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private int idpaciente;
     private Persona persona;
     private Date fechaIngreso;
     private Integer numeroAtencion;
     private String tipoIngreso;
     private Integer idHistoriaClinica;
     private String estado;
     private String horaIngreso;
     private Especialidad especialidad;
     private Usuario usuario;



     private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);

    public Paciente() {
    }


   
    public int getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(int idpaciente) {
        this.idpaciente = idpaciente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getNumeroAtencion() {
        return this.numeroAtencion;
    }
    
    public void setNumeroAtencion(Integer numeroAtencion) {
        this.numeroAtencion = numeroAtencion;
    }
    public String getTipoIngreso() {
        return this.tipoIngreso;
    }
    
    public void setTipoIngreso(String tipoIngreso) {
        this.tipoIngreso = tipoIngreso;
    }
    public Integer getIdHistoriaClinica() {
        return this.idHistoriaClinica;
    }
    
    public void setIdHistoriaClinica(Integer idHistoriaClinica) {
        this.idHistoriaClinica = idHistoriaClinica;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(String horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    
    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }

    public Especialidad getEspecialidad() {
        return especialidad;
    }

    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


