package lissa.be;
// Generated 05/07/2018 12:13:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import static lissa.be.EvaluacionOcupacional.DATO;

/**
 * PuestoLaboral generated by hbm2java
 */
public class PuestoLaboral implements java.io.Serializable {

    private long idpuestolaboral;
    private String puestoLaboral;
    private String estado;
    private Set<AtencionOcupacional> atencionOcupacionals = new HashSet<AtencionOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public PuestoLaboral() {
    }

    public PuestoLaboral(long idpuestolaboral, String puestoLaboral, String estado) {
        this.idpuestolaboral = idpuestolaboral;
        this.puestoLaboral = puestoLaboral;
        this.estado = estado;
    }

    public PuestoLaboral(long idpuestolaboral, String puestoLaboral, String estado, Set<AtencionOcupacional> atencionOcupacionals) {
        this.idpuestolaboral = idpuestolaboral;
        this.puestoLaboral = puestoLaboral;
        this.estado = estado;
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public long getIdpuestolaboral() {
        return this.idpuestolaboral;
    }

    public void setIdpuestolaboral(long idpuestolaboral) {
        this.idpuestolaboral = idpuestolaboral;
    }

    public String getPuestoLaboral() {
        return this.puestoLaboral;
    }

    public void setPuestoLaboral(String puestoLaboral) {
        this.puestoLaboral = puestoLaboral;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set<AtencionOcupacional> getAtencionOcupacionals() {
        return this.atencionOcupacionals;
    }

    public void setAtencionOcupacionals(Set<AtencionOcupacional> atencionOcupacionals) {
        this.atencionOcupacionals = atencionOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getPuestoLaboral();
            default:
                return "<SELECCIONE>";
        }
    }

}
