package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import static lissa.be.MotivoObservacion.DATO;

/**
 * Recomendacion generated by hbm2java
 */
public class Recomendacion implements java.io.Serializable {

    private long idrecomendacion;
    private ExamenOcupacional examenOcupacional;
    private String descipcion;
    private Set<CertMedicoOcupacional> certMedicoOcupacionals = new HashSet<CertMedicoOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public Recomendacion() {
    }

    public Recomendacion(long idrecomendacion, ExamenOcupacional examenOcupacional) {
        this.idrecomendacion = idrecomendacion;
        this.examenOcupacional = examenOcupacional;
    }

    public Recomendacion(long idrecomendacion, ExamenOcupacional examenOcupacional, String descipcion, Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.idrecomendacion = idrecomendacion;
        this.examenOcupacional = examenOcupacional;
        this.descipcion = descipcion;
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public long getIdrecomendacion() {
        return this.idrecomendacion;
    }

    public void setIdrecomendacion(long idrecomendacion) {
        this.idrecomendacion = idrecomendacion;
    }

    public ExamenOcupacional getExamenOcupacional() {
        return this.examenOcupacional;
    }

    public void setExamenOcupacional(ExamenOcupacional examenOcupacional) {
        this.examenOcupacional = examenOcupacional;
    }

    public String getDescipcion() {
        return this.descipcion;
    }

    public void setDescipcion(String descipcion) {
        this.descipcion = descipcion;
    }

    public Set<CertMedicoOcupacional> getCertMedicoOcupacionals() {
        return this.certMedicoOcupacionals;
    }

    public void setCertMedicoOcupacionals(Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDescipcion();
            default:
                return "<SELECCIONE>";
        }
    }

}
