package lissa.be;
// Generated 10/07/2018 11:20:49 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Restriccion generated by hbm2java
 */
public class Restriccion implements java.io.Serializable {

    private long idrestriccion;
    private ExamenOcupacional examenOcupacional;
    private String descripcion;
    private Set<CertMedicoOcupacional> certMedicoOcupacionals = new HashSet<CertMedicoOcupacional>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public Restriccion() {
    }

    public Restriccion(long idrestriccion, ExamenOcupacional examenOcupacional, String descripcion) {
        this.idrestriccion = idrestriccion;
        this.examenOcupacional = examenOcupacional;
        this.descripcion = descripcion;
    }

    public Restriccion(long idrestriccion, ExamenOcupacional examenOcupacional, String descripcion, Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.idrestriccion = idrestriccion;
        this.examenOcupacional = examenOcupacional;
        this.descripcion = descripcion;
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public long getIdrestriccion() {
        return this.idrestriccion;
    }

    public void setIdrestriccion(long idrestriccion) {
        this.idrestriccion = idrestriccion;
    }

    public ExamenOcupacional getExamenOcupacional() {
        return this.examenOcupacional;
    }

    public void setExamenOcupacional(ExamenOcupacional examenOcupacional) {
        this.examenOcupacional = examenOcupacional;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<CertMedicoOcupacional> getCertMedicoOcupacionals() {
        return this.certMedicoOcupacionals;
    }

    public void setCertMedicoOcupacionals(Set<CertMedicoOcupacional> certMedicoOcupacionals) {
        this.certMedicoOcupacionals = certMedicoOcupacionals;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDescripcion();
            default:
                return "<SELECCIONE>";
        }
    }

}
