package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * SoFmoAntecedentesPatPer generated by hbm2java
 */
public class SoFmoAntecedentesPatPer  implements java.io.Serializable {


     private int idsofmoantedecentespatper;
     private FichaMedicoOcupacional fichaMedicoOcupacional;
     private boolean alergia;
     private boolean diabetes;
     private boolean tbc;
     private boolean hepatitisb;
     private boolean asma;
     private boolean hta;
     private boolean its;
     private boolean tifoidea;
     private boolean bronquitis;
     private boolean neoplasia;
     private boolean convulsiones;
     private boolean otros;
     private boolean quemaduras;
     private boolean cirugias;
     private boolean intoxicaciones;

    public SoFmoAntecedentesPatPer() {
    }

    public SoFmoAntecedentesPatPer(int idsofmoantedecentespatper, FichaMedicoOcupacional fichaMedicoOcupacional, boolean alergia, boolean diabetes, boolean tbc, boolean hepatitisb, boolean asma, boolean hta, boolean its, boolean tifoidea, boolean bronquitis, boolean neoplasia, boolean convulsiones, boolean otros, boolean quemaduras, boolean cirugias, boolean intoxicaciones) {
       this.idsofmoantedecentespatper = idsofmoantedecentespatper;
       this.fichaMedicoOcupacional = fichaMedicoOcupacional;
       this.alergia = alergia;
       this.diabetes = diabetes;
       this.tbc = tbc;
       this.hepatitisb = hepatitisb;
       this.asma = asma;
       this.hta = hta;
       this.its = its;
       this.tifoidea = tifoidea;
       this.bronquitis = bronquitis;
       this.neoplasia = neoplasia;
       this.convulsiones = convulsiones;
       this.otros = otros;
       this.quemaduras = quemaduras;
       this.cirugias = cirugias;
       this.intoxicaciones = intoxicaciones;
    }
   
    public int getIdsofmoantedecentespatper() {
        return this.idsofmoantedecentespatper;
    }
    
    public void setIdsofmoantedecentespatper(int idsofmoantedecentespatper) {
        this.idsofmoantedecentespatper = idsofmoantedecentespatper;
    }
    public FichaMedicoOcupacional getFichaMedicoOcupacional() {
        return this.fichaMedicoOcupacional;
    }
    
    public void setFichaMedicoOcupacional(FichaMedicoOcupacional fichaMedicoOcupacional) {
        this.fichaMedicoOcupacional = fichaMedicoOcupacional;
    }
    public boolean isAlergia() {
        return this.alergia;
    }
    
    public void setAlergia(boolean alergia) {
        this.alergia = alergia;
    }
    public boolean isDiabetes() {
        return this.diabetes;
    }
    
    public void setDiabetes(boolean diabetes) {
        this.diabetes = diabetes;
    }
    public boolean isTbc() {
        return this.tbc;
    }
    
    public void setTbc(boolean tbc) {
        this.tbc = tbc;
    }
    public boolean isHepatitisb() {
        return this.hepatitisb;
    }
    
    public void setHepatitisb(boolean hepatitisb) {
        this.hepatitisb = hepatitisb;
    }
    public boolean isAsma() {
        return this.asma;
    }
    
    public void setAsma(boolean asma) {
        this.asma = asma;
    }
    public boolean isHta() {
        return this.hta;
    }
    
    public void setHta(boolean hta) {
        this.hta = hta;
    }
    public boolean isIts() {
        return this.its;
    }
    
    public void setIts(boolean its) {
        this.its = its;
    }
    public boolean isTifoidea() {
        return this.tifoidea;
    }
    
    public void setTifoidea(boolean tifoidea) {
        this.tifoidea = tifoidea;
    }
    public boolean isBronquitis() {
        return this.bronquitis;
    }
    
    public void setBronquitis(boolean bronquitis) {
        this.bronquitis = bronquitis;
    }
    public boolean isNeoplasia() {
        return this.neoplasia;
    }
    
    public void setNeoplasia(boolean neoplasia) {
        this.neoplasia = neoplasia;
    }
    public boolean isConvulsiones() {
        return this.convulsiones;
    }
    
    public void setConvulsiones(boolean convulsiones) {
        this.convulsiones = convulsiones;
    }
    public boolean isOtros() {
        return this.otros;
    }
    
    public void setOtros(boolean otros) {
        this.otros = otros;
    }
    public boolean isQuemaduras() {
        return this.quemaduras;
    }
    
    public void setQuemaduras(boolean quemaduras) {
        this.quemaduras = quemaduras;
    }
    public boolean isCirugias() {
        return this.cirugias;
    }
    
    public void setCirugias(boolean cirugias) {
        this.cirugias = cirugias;
    }
    public boolean isIntoxicaciones() {
        return this.intoxicaciones;
    }
    
    public void setIntoxicaciones(boolean intoxicaciones) {
        this.intoxicaciones = intoxicaciones;
    }




}


