package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * SoFmoConclusiones generated by hbm2java
 */
public class SoFmoConclusiones  implements java.io.Serializable {


     private int idsofmoconclusiones;
     private FichaMedicoOcupacional fichaMedicoOcupacional;
     private String evalPsicologica;
     private String radiograficas;
     private String hallazgosPatologicos;
     private String audiometria;
     private String espirometria;
     private String otros;
     private String condicion;
     private String recomendacion;
     private String concEvalPsicologicaPsicotecnico;
     private String concOftalmologica;
     private String concOsteomuscular;

    public SoFmoConclusiones() {
    }

    public SoFmoConclusiones(int idsofmoconclusiones, FichaMedicoOcupacional fichaMedicoOcupacional, String evalPsicologica, String radiograficas, String hallazgosPatologicos, String audiometria, String espirometria, String otros, String condicion, String recomendacion, String concEvalPsicologicaPsicotecnico, String concOftalmologica, String concOsteomuscular) {
       this.idsofmoconclusiones = idsofmoconclusiones;
       this.fichaMedicoOcupacional = fichaMedicoOcupacional;
       this.evalPsicologica = evalPsicologica;
       this.radiograficas = radiograficas;
       this.hallazgosPatologicos = hallazgosPatologicos;
       this.audiometria = audiometria;
       this.espirometria = espirometria;
       this.otros = otros;
       this.condicion = condicion;
       this.recomendacion = recomendacion;
       this.concEvalPsicologicaPsicotecnico = concEvalPsicologicaPsicotecnico;
       this.concOftalmologica = concOftalmologica;
       this.concOsteomuscular = concOsteomuscular;
    }
   
    public int getIdsofmoconclusiones() {
        return this.idsofmoconclusiones;
    }
    
    public void setIdsofmoconclusiones(int idsofmoconclusiones) {
        this.idsofmoconclusiones = idsofmoconclusiones;
    }
    public FichaMedicoOcupacional getFichaMedicoOcupacional() {
        return this.fichaMedicoOcupacional;
    }
    
    public void setFichaMedicoOcupacional(FichaMedicoOcupacional fichaMedicoOcupacional) {
        this.fichaMedicoOcupacional = fichaMedicoOcupacional;
    }
    public String getEvalPsicologica() {
        return this.evalPsicologica;
    }
    
    public void setEvalPsicologica(String evalPsicologica) {
        this.evalPsicologica = evalPsicologica;
    }
    public String getRadiograficas() {
        return this.radiograficas;
    }
    
    public void setRadiograficas(String radiograficas) {
        this.radiograficas = radiograficas;
    }
    public String getHallazgosPatologicos() {
        return this.hallazgosPatologicos;
    }
    
    public void setHallazgosPatologicos(String hallazgosPatologicos) {
        this.hallazgosPatologicos = hallazgosPatologicos;
    }
    public String getAudiometria() {
        return this.audiometria;
    }
    
    public void setAudiometria(String audiometria) {
        this.audiometria = audiometria;
    }
    public String getEspirometria() {
        return this.espirometria;
    }
    
    public void setEspirometria(String espirometria) {
        this.espirometria = espirometria;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public String getRecomendacion() {
        return this.recomendacion;
    }
    
    public void setRecomendacion(String recomendacion) {
        this.recomendacion = recomendacion;
    }
    public String getConcEvalPsicologicaPsicotecnico() {
        return this.concEvalPsicologicaPsicotecnico;
    }
    
    public void setConcEvalPsicologicaPsicotecnico(String concEvalPsicologicaPsicotecnico) {
        this.concEvalPsicologicaPsicotecnico = concEvalPsicologicaPsicotecnico;
    }
    public String getConcOftalmologica() {
        return this.concOftalmologica;
    }
    
    public void setConcOftalmologica(String concOftalmologica) {
        this.concOftalmologica = concOftalmologica;
    }
    public String getConcOsteomuscular() {
        return this.concOsteomuscular;
    }
    
    public void setConcOsteomuscular(String concOsteomuscular) {
        this.concOsteomuscular = concOsteomuscular;
    }




}


