package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1



/**
 * SoFmoExamenFisico generated by hbm2java
 */
public class SoFmoExamenFisico  implements java.io.Serializable {


     private int idsofmoexamenfisico;
     private FichaMedicoOcupacional fichaMedicoOcupacional;
     private boolean piel;
     private String pielDesc;
     private boolean cabello;
     private String cabelloDesc;
     private boolean ojos;
     private String ojosDesc;
     private boolean oidos;
     private String oidosDesc;
     private boolean nariz;
     private String narizDesc;
     private boolean boca;
     private String bocaDesc;
     private boolean faringe;
     private String faringeDesc;
     private boolean cuello;
     private String cuelloDesc;
     private boolean respiratorio;
     private String respiratorioDesc;
     private boolean cardiovascular;
     private String cardiovascularDesc;
     private boolean digestivo;
     private String digestivoDesc;
     private boolean genitourinario;
     private String genitourinarioDesc;
     private boolean locomotor;
     private String locomotorDesc;
     private boolean marcha;
     private String marchaDesc;
     private boolean columna;
     private String columnaDesc;
     private boolean miembrosSuperiores;
     private String miembrosSuperioresDesc;
     private boolean miembrosInferiores;
     private String miembrosInferioresDesc;
     private boolean sistemaLinfatico;
     private String sistemaLinfaticoDesc;
     private boolean sistemaNervioso;
     private String sistemaNerviosoDesc;

    public SoFmoExamenFisico() {
    }

    public SoFmoExamenFisico(int idsofmoexamenfisico, FichaMedicoOcupacional fichaMedicoOcupacional, boolean piel, String pielDesc, boolean cabello, String cabelloDesc, boolean ojos, String ojosDesc, boolean oidos, String oidosDesc, boolean nariz, String narizDesc, boolean boca, String bocaDesc, boolean faringe, String faringeDesc, boolean cuello, String cuelloDesc, boolean respiratorio, String respiratorioDesc, boolean cardiovascular, String cardiovascularDesc, boolean digestivo, String digestivoDesc, boolean genitourinario, String genitourinarioDesc, boolean locomotor, String locomotorDesc, boolean marcha, String marchaDesc, boolean columna, String columnaDesc, boolean miembrosSuperiores, String miembrosSuperioresDesc, boolean miembrosInferiores, String miembrosInferioresDesc, boolean sistemaLinfatico, String sistemaLinfaticoDesc, boolean sistemaNervioso, String sistemaNerviosoDesc) {
       this.idsofmoexamenfisico = idsofmoexamenfisico;
       this.fichaMedicoOcupacional = fichaMedicoOcupacional;
       this.piel = piel;
       this.pielDesc = pielDesc;
       this.cabello = cabello;
       this.cabelloDesc = cabelloDesc;
       this.ojos = ojos;
       this.ojosDesc = ojosDesc;
       this.oidos = oidos;
       this.oidosDesc = oidosDesc;
       this.nariz = nariz;
       this.narizDesc = narizDesc;
       this.boca = boca;
       this.bocaDesc = bocaDesc;
       this.faringe = faringe;
       this.faringeDesc = faringeDesc;
       this.cuello = cuello;
       this.cuelloDesc = cuelloDesc;
       this.respiratorio = respiratorio;
       this.respiratorioDesc = respiratorioDesc;
       this.cardiovascular = cardiovascular;
       this.cardiovascularDesc = cardiovascularDesc;
       this.digestivo = digestivo;
       this.digestivoDesc = digestivoDesc;
       this.genitourinario = genitourinario;
       this.genitourinarioDesc = genitourinarioDesc;
       this.locomotor = locomotor;
       this.locomotorDesc = locomotorDesc;
       this.marcha = marcha;
       this.marchaDesc = marchaDesc;
       this.columna = columna;
       this.columnaDesc = columnaDesc;
       this.miembrosSuperiores = miembrosSuperiores;
       this.miembrosSuperioresDesc = miembrosSuperioresDesc;
       this.miembrosInferiores = miembrosInferiores;
       this.miembrosInferioresDesc = miembrosInferioresDesc;
       this.sistemaLinfatico = sistemaLinfatico;
       this.sistemaLinfaticoDesc = sistemaLinfaticoDesc;
       this.sistemaNervioso = sistemaNervioso;
       this.sistemaNerviosoDesc = sistemaNerviosoDesc;
    }
   
    public int getIdsofmoexamenfisico() {
        return this.idsofmoexamenfisico;
    }
    
    public void setIdsofmoexamenfisico(int idsofmoexamenfisico) {
        this.idsofmoexamenfisico = idsofmoexamenfisico;
    }
    public FichaMedicoOcupacional getFichaMedicoOcupacional() {
        return this.fichaMedicoOcupacional;
    }
    
    public void setFichaMedicoOcupacional(FichaMedicoOcupacional fichaMedicoOcupacional) {
        this.fichaMedicoOcupacional = fichaMedicoOcupacional;
    }
    public boolean isPiel() {
        return this.piel;
    }
    
    public void setPiel(boolean piel) {
        this.piel = piel;
    }
    public String getPielDesc() {
        return this.pielDesc;
    }
    
    public void setPielDesc(String pielDesc) {
        this.pielDesc = pielDesc;
    }
    public boolean isCabello() {
        return this.cabello;
    }
    
    public void setCabello(boolean cabello) {
        this.cabello = cabello;
    }
    public String getCabelloDesc() {
        return this.cabelloDesc;
    }
    
    public void setCabelloDesc(String cabelloDesc) {
        this.cabelloDesc = cabelloDesc;
    }
    public boolean isOjos() {
        return this.ojos;
    }
    
    public void setOjos(boolean ojos) {
        this.ojos = ojos;
    }
    public String getOjosDesc() {
        return this.ojosDesc;
    }
    
    public void setOjosDesc(String ojosDesc) {
        this.ojosDesc = ojosDesc;
    }
    public boolean isOidos() {
        return this.oidos;
    }
    
    public void setOidos(boolean oidos) {
        this.oidos = oidos;
    }
    public String getOidosDesc() {
        return this.oidosDesc;
    }
    
    public void setOidosDesc(String oidosDesc) {
        this.oidosDesc = oidosDesc;
    }
    public boolean isNariz() {
        return this.nariz;
    }
    
    public void setNariz(boolean nariz) {
        this.nariz = nariz;
    }
    public String getNarizDesc() {
        return this.narizDesc;
    }
    
    public void setNarizDesc(String narizDesc) {
        this.narizDesc = narizDesc;
    }
    public boolean isBoca() {
        return this.boca;
    }
    
    public void setBoca(boolean boca) {
        this.boca = boca;
    }
    public String getBocaDesc() {
        return this.bocaDesc;
    }
    
    public void setBocaDesc(String bocaDesc) {
        this.bocaDesc = bocaDesc;
    }
    public boolean isFaringe() {
        return this.faringe;
    }
    
    public void setFaringe(boolean faringe) {
        this.faringe = faringe;
    }
    public String getFaringeDesc() {
        return this.faringeDesc;
    }
    
    public void setFaringeDesc(String faringeDesc) {
        this.faringeDesc = faringeDesc;
    }
    public boolean isCuello() {
        return this.cuello;
    }
    
    public void setCuello(boolean cuello) {
        this.cuello = cuello;
    }
    public String getCuelloDesc() {
        return this.cuelloDesc;
    }
    
    public void setCuelloDesc(String cuelloDesc) {
        this.cuelloDesc = cuelloDesc;
    }
    public boolean isRespiratorio() {
        return this.respiratorio;
    }
    
    public void setRespiratorio(boolean respiratorio) {
        this.respiratorio = respiratorio;
    }
    public String getRespiratorioDesc() {
        return this.respiratorioDesc;
    }
    
    public void setRespiratorioDesc(String respiratorioDesc) {
        this.respiratorioDesc = respiratorioDesc;
    }
    public boolean isCardiovascular() {
        return this.cardiovascular;
    }
    
    public void setCardiovascular(boolean cardiovascular) {
        this.cardiovascular = cardiovascular;
    }
    public String getCardiovascularDesc() {
        return this.cardiovascularDesc;
    }
    
    public void setCardiovascularDesc(String cardiovascularDesc) {
        this.cardiovascularDesc = cardiovascularDesc;
    }
    public boolean isDigestivo() {
        return this.digestivo;
    }
    
    public void setDigestivo(boolean digestivo) {
        this.digestivo = digestivo;
    }
    public String getDigestivoDesc() {
        return this.digestivoDesc;
    }
    
    public void setDigestivoDesc(String digestivoDesc) {
        this.digestivoDesc = digestivoDesc;
    }
    public boolean isGenitourinario() {
        return this.genitourinario;
    }
    
    public void setGenitourinario(boolean genitourinario) {
        this.genitourinario = genitourinario;
    }
    public String getGenitourinarioDesc() {
        return this.genitourinarioDesc;
    }
    
    public void setGenitourinarioDesc(String genitourinarioDesc) {
        this.genitourinarioDesc = genitourinarioDesc;
    }
    public boolean isLocomotor() {
        return this.locomotor;
    }
    
    public void setLocomotor(boolean locomotor) {
        this.locomotor = locomotor;
    }
    public String getLocomotorDesc() {
        return this.locomotorDesc;
    }
    
    public void setLocomotorDesc(String locomotorDesc) {
        this.locomotorDesc = locomotorDesc;
    }
    public boolean isMarcha() {
        return this.marcha;
    }
    
    public void setMarcha(boolean marcha) {
        this.marcha = marcha;
    }
    public String getMarchaDesc() {
        return this.marchaDesc;
    }
    
    public void setMarchaDesc(String marchaDesc) {
        this.marchaDesc = marchaDesc;
    }
    public boolean isColumna() {
        return this.columna;
    }
    
    public void setColumna(boolean columna) {
        this.columna = columna;
    }
    public String getColumnaDesc() {
        return this.columnaDesc;
    }
    
    public void setColumnaDesc(String columnaDesc) {
        this.columnaDesc = columnaDesc;
    }
    public boolean isMiembrosSuperiores() {
        return this.miembrosSuperiores;
    }
    
    public void setMiembrosSuperiores(boolean miembrosSuperiores) {
        this.miembrosSuperiores = miembrosSuperiores;
    }
    public String getMiembrosSuperioresDesc() {
        return this.miembrosSuperioresDesc;
    }
    
    public void setMiembrosSuperioresDesc(String miembrosSuperioresDesc) {
        this.miembrosSuperioresDesc = miembrosSuperioresDesc;
    }
    public boolean isMiembrosInferiores() {
        return this.miembrosInferiores;
    }
    
    public void setMiembrosInferiores(boolean miembrosInferiores) {
        this.miembrosInferiores = miembrosInferiores;
    }
    public String getMiembrosInferioresDesc() {
        return this.miembrosInferioresDesc;
    }
    
    public void setMiembrosInferioresDesc(String miembrosInferioresDesc) {
        this.miembrosInferioresDesc = miembrosInferioresDesc;
    }
    public boolean isSistemaLinfatico() {
        return this.sistemaLinfatico;
    }
    
    public void setSistemaLinfatico(boolean sistemaLinfatico) {
        this.sistemaLinfatico = sistemaLinfatico;
    }
    public String getSistemaLinfaticoDesc() {
        return this.sistemaLinfaticoDesc;
    }
    
    public void setSistemaLinfaticoDesc(String sistemaLinfaticoDesc) {
        this.sistemaLinfaticoDesc = sistemaLinfaticoDesc;
    }
    public boolean isSistemaNervioso() {
        return this.sistemaNervioso;
    }
    
    public void setSistemaNervioso(boolean sistemaNervioso) {
        this.sistemaNervioso = sistemaNervioso;
    }
    public String getSistemaNerviosoDesc() {
        return this.sistemaNerviosoDesc;
    }
    
    public void setSistemaNerviosoDesc(String sistemaNerviosoDesc) {
        this.sistemaNerviosoDesc = sistemaNerviosoDesc;
    }




}


