package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento  implements java.io.Serializable {


     private int idtratamiento;
     private Atencion atencion;
     private String tratamiento;
     private Boolean estado;
     private Date fechaInicio;
     private Date fechaFinalizacion;
     private Integer idResultadoExamen;

    public Tratamiento() {
    }

	
    public Tratamiento(int idtratamiento) {
        this.idtratamiento = idtratamiento;
    }
    public Tratamiento(int idtratamiento, Atencion atencion, String tratamiento, Boolean estado, Date fechaInicio, Date fechaFinalizacion, Integer idResultadoExamen) {
       this.idtratamiento = idtratamiento;
       this.atencion = atencion;
       this.tratamiento = tratamiento;
       this.estado = estado;
       this.fechaInicio = fechaInicio;
       this.fechaFinalizacion = fechaFinalizacion;
       this.idResultadoExamen = idResultadoExamen;
    }
   
    public int getIdtratamiento() {
        return this.idtratamiento;
    }
    
    public void setIdtratamiento(int idtratamiento) {
        this.idtratamiento = idtratamiento;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinalizacion() {
        return this.fechaFinalizacion;
    }
    
    public void setFechaFinalizacion(Date fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }
    public Integer getIdResultadoExamen() {
        return this.idResultadoExamen;
    }
    
    public void setIdResultadoExamen(Integer idResultadoExamen) {
        this.idResultadoExamen = idResultadoExamen;
    }




}


