package lissa.gui.saludocupacional;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lissa.be.AtencionOcupacional;
import lissa.be.ExamenClinico;
import lissa.be.FichaOftalmologica;
import lissa.be.FichaPsicologica;
import lissa.be.FichaPsicologicaPsicotecnico;
import lissa.be.InformeMedicoOcupacional;
import lissa.be.Persona;
import lissa.be.Rol;
import lissa.be.SoFmoAntecedentesPatFam;
import lissa.be.SoFmoAntecedentesPatPer;
import lissa.be.Usuario;
import lissa.bl.ExamenClinicoBl;
import lissa.bl.FichaAudiometriaBl;
import lissa.bl.FichaOftalmologicaBl;
import lissa.bl.FichaPsicologicaBl;
import lissa.bl.FichaPsicologicaPsicotecnicoBl;
import lissa.bl.InformeMedicoOcupacionalBl;
import lissa.bl.SoFmoAntecedentesPatFamBl;
import lissa.bl.SoFmoAntecedentesPatPerBl;
import lissa.bl.SoFmoConclusionesBl;
import lissa.ds.DSConeccion;
import lissa.gui.JF_Principal;
import lissa.reportes.ReportGeneric;
import lissa.util.Mensajes;

public class JPanel_InformeMedicoOcupacional extends javax.swing.JPanel {

    private JF_Principal root;
    private AtencionOcupacional oAtencionOcupacional;
    private ExamenClinico oExamenClinico;
    private ExamenClinicoBl oExamenClinicoBl;
    private FichaOftalmologica oFichaOftalmologica;
    private FichaOftalmologicaBl oFichaOftalmologicaBl;
    private FichaAudiometriaBl oFichaAudiometriaBl;
    private FichaPsicologicaBl oFichaPsicologicaBl;
    private FichaPsicologica oFichaPsicologica;
    private FichaPsicologicaPsicotecnico oFichaPsicologicaPsicotecnico;
    private FichaPsicologicaPsicotecnicoBl oFichaPsicologicaPsicotecnicoBl;
    private InformeMedicoOcupacional oInformeMedicoOcupacional;
    private InformeMedicoOcupacionalBl oInformeMedicoOcupacionalBl;
    private Usuario userTemp;
    private Persona perTemp;
    private Rol rolTemp;
    private SoFmoAntecedentesPatPerBl oSoFmoAntecedentesPatPerBl;
    private SoFmoAntecedentesPatFam oSoFmoAntecedentesPatFam;
    private SoFmoAntecedentesPatFamBl oSoFmoAntecedentesPatFamBl;
    private SoFmoAntecedentesPatPer oSoFmoAntecedentesPatPer;
    
    private ReportGeneric reportGenric = null;
    private JPanel reportPanel = null;
    private DSConeccion ds = null;
    private JInternalFrame reportVisor = null;

    public JPanel_InformeMedicoOcupacional(JF_Principal root) {
        initComponents();
        this.root = root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txfExMusculoEsqueletico = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txfGrupoFx = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txfGlucosa = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txfUrea = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txfHemograma = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txfHemoglobina = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txfColesterol = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txfBilirrubina = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txfProteinasTot = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txfCreatinina = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txfExOrina = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txfProteinasFrac = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txfTgp = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txfFosfatasa = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txfGamma = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txfTgo = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txfHisopado = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txfCoprocultivo = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txfBkEsputo = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txfParasitologicoSer = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txfAglutinaciones = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txfHepatitis = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txfParasitologicoDir = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txfToxicologico = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txfSubUniBeta = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txfVsg = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txfVdrl = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txfKhoUnas = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txfRxTorax = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        txfRxLumbar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txfEspirometria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txfAudiometria = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfElectroencefalograma = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txfPruebaEsfuerzo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txfEkg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txfPsilogico = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txfPsicotecnico = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txfTestEstres = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txfTestEpworth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfOftalmologia = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txfOdontograma = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txfDermatologia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDiagnostico = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaConclusiones = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaRecomendaciones = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfTalla = new javax.swing.JTextField();
        txfPeso = new javax.swing.JTextField();
        txfFc = new javax.swing.JTextField();
        txfPa = new javax.swing.JTextField();
        txfImc = new javax.swing.JTextField();

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/cancel.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/Save.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EVALUACIÓN MÉDICA");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("EXAMEN MÚSCULO ESQUELÉTICO");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(jLabel6);
        jPanel3.add(txfExMusculoEsqueletico);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("EXAMENES DE LABORATORIO");
        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new java.awt.GridLayout(9, 6));

        jLabel29.setText("Grupo y Fx Rh");
        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel29);
        jPanel4.add(txfGrupoFx);

        jLabel30.setText("Glucosa");
        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel30);
        jPanel4.add(txfGlucosa);

        jLabel31.setText("Urea");
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel31);
        jPanel4.add(txfUrea);

        jLabel32.setText("Hemograma completo");
        jLabel32.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel32);
        jPanel4.add(txfHemograma);

        jLabel33.setText("Hemoglobina");
        jLabel33.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel33);
        jPanel4.add(txfHemoglobina);

        jLabel34.setText("Colesterol");
        jLabel34.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel34);
        jPanel4.add(txfColesterol);

        jLabel35.setText("Bilirrubina total");
        jLabel35.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel35);
        jPanel4.add(txfBilirrubina);

        jLabel36.setText("Proteínas totales");
        jLabel36.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel36);
        jPanel4.add(txfProteinasTot);

        jLabel37.setText("Creatinina");
        jLabel37.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel37);
        jPanel4.add(txfCreatinina);

        jLabel38.setText("Examen de orina");
        jLabel38.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel38);
        jPanel4.add(txfExOrina);

        jLabel39.setText("Proteínas fraccionadas");
        jLabel39.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel39);
        jPanel4.add(txfProteinasFrac);

        jLabel40.setText("TGP");
        jLabel40.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel40);
        jPanel4.add(txfTgp);

        jLabel41.setText("Fosfatasa alcalina");
        jLabel41.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel41);
        jPanel4.add(txfFosfatasa);

        jLabel42.setText("Gamma glutamil");
        jLabel42.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel42);
        jPanel4.add(txfGamma);

        jLabel43.setText("TGO");
        jLabel43.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel43);
        jPanel4.add(txfTgo);

        jLabel44.setText("Hisopado nasofaringeo");
        jLabel44.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel44);
        jPanel4.add(txfHisopado);

        jLabel45.setText("Coprocultivo");
        jLabel45.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel45);
        jPanel4.add(txfCoprocultivo);

        jLabel46.setText("BK en esputo");
        jLabel46.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel46);
        jPanel4.add(txfBkEsputo);

        jLabel47.setText("Parasitológico seriado");
        jLabel47.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel47);
        jPanel4.add(txfParasitologicoSer);

        jLabel48.setText("Aglutinaciones");
        jLabel48.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel48);
        jPanel4.add(txfAglutinaciones);

        jLabel49.setText("Hepatitis");
        jLabel49.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel49);
        jPanel4.add(txfHepatitis);

        jLabel50.setText("Parasitológico directo");
        jLabel50.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel50);
        jPanel4.add(txfParasitologicoDir);

        jLabel51.setText("Toxicológico");
        jLabel51.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel51);
        jPanel4.add(txfToxicologico);

        jLabel52.setText("Sub unidad beta");
        jLabel52.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel52);
        jPanel4.add(txfSubUniBeta);

        jLabel53.setText("VSG");
        jLabel53.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel53);
        jPanel4.add(txfVsg);

        jLabel54.setText("VDRL");
        jLabel54.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel54);
        jPanel4.add(txfVdrl);

        jLabel55.setText("KHO (uñas)");
        jLabel55.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel55);
        jPanel4.add(txfKhoUnas);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("EXAMENES COMPLEMENTARIOS");
        jLabel56.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new java.awt.GridLayout(14, 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("RADIOGRAFÍA DE TORAX");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel14);
        jPanel5.add(txfRxTorax);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setText("RADIOGRAFÍA LUMBAR");
        jLabel57.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel57);
        jPanel5.add(txfRxLumbar);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ESPIROMETRÍA");
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel12);
        jPanel5.add(txfEspirometria);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("AUDIOMETRÍA");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel13);
        jPanel5.add(txfAudiometria);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("ELECTROENCEFALOGRAMA ");
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel18);
        jPanel5.add(txfElectroencefalograma);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("PRUEBA DE ESFUERZO ");
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel11);
        jPanel5.add(txfPruebaEsfuerzo);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ELECTROCARDIOGRAMA ");
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel10);
        jPanel5.add(txfEkg);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("PSICOLOGÍA");
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel16);
        jPanel5.add(txfPsilogico);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("TEST PSICOTÉCNICO");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel17);
        jPanel5.add(txfPsicotecnico);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("TEST DE ESTRÉS - FATIGA / FOBIA");
        jLabel58.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel58);
        jPanel5.add(txfTestEstres);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("TEST DE EPWORTH");
        jLabel59.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel59);
        jPanel5.add(txfTestEpworth);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("OFTALMOLOGÍA ");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel9);
        jPanel5.add(txfOftalmologia);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("ODONTOGRAMA");
        jLabel60.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel60);
        jPanel5.add(txfOdontograma);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("DERMATOLOGÍA");
        jLabel61.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.add(jLabel61);
        jPanel5.add(txfDermatologia);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("DIAGNOSTICO CIE 10");
        jLabel27.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.add(jLabel27);

        txaDiagnostico.setColumns(20);
        txaDiagnostico.setRows(3);
        jScrollPane1.setViewportView(txaDiagnostico);

        jPanel6.add(jScrollPane1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONCLUSIONES");
        jPanel7.add(jLabel8);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("RECOMENDACIONES");
        jPanel7.add(jLabel15);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        txaConclusiones.setColumns(20);
        txaConclusiones.setRows(5);
        jScrollPane2.setViewportView(txaConclusiones);

        jPanel8.add(jScrollPane2);

        txaRecomendaciones.setColumns(20);
        txaRecomendaciones.setRows(5);
        jScrollPane3.setViewportView(txaRecomendaciones);

        jPanel8.add(jScrollPane3);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new java.awt.GridLayout(2, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Talla (cm)");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Peso (Kg)");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.add(jLabel2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("F.C lpm");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.add(jLabel7);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("P.A mmHg");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.add(jLabel4);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IMC(Kg/m2)");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.add(jLabel3);

        txfTalla.setEditable(false);
        txfTalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txfTalla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txfTalla);

        txfPeso.setEditable(false);
        txfPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txfPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txfPeso);

        txfFc.setEditable(false);
        txfFc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txfFc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txfFc);

        txfPa.setEditable(false);
        txfPa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txfPa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(txfPa);

        txfImc.setEditable(false);
        txfImc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txfImc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfImcActionPerformed(evt);
            }
        });
        jPanel9.add(txfImc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel56)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfImcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfImcActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (isDatosValidos()) {
            oInformeMedicoOcupacional = registrarInforme();
            if (oInformeMedicoOcupacional != null) {
                Mensajes.msjRegCorrecta();
                imprimirInforme(oInformeMedicoOcupacional);
                resetComponent();
            } else {
                Mensajes.msjRegError();
            }
        } else {
            Mensajes.msjValidarIngreso();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txaConclusiones;
    private javax.swing.JTextArea txaDiagnostico;
    private javax.swing.JTextArea txaRecomendaciones;
    private javax.swing.JTextField txfAglutinaciones;
    private javax.swing.JTextField txfAudiometria;
    private javax.swing.JTextField txfBilirrubina;
    private javax.swing.JTextField txfBkEsputo;
    private javax.swing.JTextField txfColesterol;
    private javax.swing.JTextField txfCoprocultivo;
    private javax.swing.JTextField txfCreatinina;
    private javax.swing.JTextField txfDermatologia;
    private javax.swing.JTextField txfEkg;
    private javax.swing.JTextField txfElectroencefalograma;
    private javax.swing.JTextField txfEspirometria;
    private javax.swing.JTextField txfExMusculoEsqueletico;
    private javax.swing.JTextField txfExOrina;
    private javax.swing.JTextField txfFc;
    private javax.swing.JTextField txfFosfatasa;
    private javax.swing.JTextField txfGamma;
    private javax.swing.JTextField txfGlucosa;
    private javax.swing.JTextField txfGrupoFx;
    private javax.swing.JTextField txfHemoglobina;
    private javax.swing.JTextField txfHemograma;
    private javax.swing.JTextField txfHepatitis;
    private javax.swing.JTextField txfHisopado;
    private javax.swing.JTextField txfImc;
    private javax.swing.JTextField txfKhoUnas;
    private javax.swing.JTextField txfOdontograma;
    private javax.swing.JTextField txfOftalmologia;
    private javax.swing.JTextField txfPa;
    private javax.swing.JTextField txfParasitologicoDir;
    private javax.swing.JTextField txfParasitologicoSer;
    private javax.swing.JTextField txfPeso;
    private javax.swing.JTextField txfProteinasFrac;
    private javax.swing.JTextField txfProteinasTot;
    private javax.swing.JTextField txfPruebaEsfuerzo;
    private javax.swing.JTextField txfPsicotecnico;
    private javax.swing.JTextField txfPsilogico;
    private javax.swing.JTextField txfRxLumbar;
    private javax.swing.JTextField txfRxTorax;
    private javax.swing.JTextField txfSubUniBeta;
    private javax.swing.JTextField txfTalla;
    private javax.swing.JTextField txfTestEpworth;
    private javax.swing.JTextField txfTestEstres;
    private javax.swing.JTextField txfTgo;
    private javax.swing.JTextField txfTgp;
    private javax.swing.JTextField txfToxicologico;
    private javax.swing.JTextField txfUrea;
    private javax.swing.JTextField txfVdrl;
    private javax.swing.JTextField txfVsg;
    // End of variables declaration//GEN-END:variables

    void enviarDatosAtencionOcupacionalApanel(AtencionOcupacional atencionOcupacional) {
        oAtencionOcupacional = atencionOcupacional;
        buscarExamenClinico(oAtencionOcupacional);
        buscarResultadoOftalmologia(oAtencionOcupacional);
        buscarResultadoAudiometria(oAtencionOcupacional);
        buscarResultadoPsicologia(oAtencionOcupacional);
        buscarResultadoPsicotecnico(oAtencionOcupacional);
        buscarAntPersonales(oAtencionOcupacional);
        buscarAntFamiliares(oAtencionOcupacional);
    }

    void enviarDatosUser(Usuario userTemp, Persona perTemp, Rol rolTemp) {
        this.userTemp = userTemp;
        this.perTemp = perTemp;
        this.rolTemp = rolTemp;
    }

    private void buscarExamenClinico(AtencionOcupacional oAtencionOcupacional) {
        oExamenClinico = new ExamenClinico();
        oExamenClinicoBl = new ExamenClinicoBl();

        oExamenClinico = oExamenClinicoBl.getExamenClinico(oAtencionOcupacional);
        if (oExamenClinico != null) {
            setearValoresExamen(oExamenClinico);
        }
    }

    private void setearValoresExamen(ExamenClinico oExamenClinico) {
        txfTalla.setText(oExamenClinico.getTalla().toString());
        txfPeso.setText(oExamenClinico.getPeso().toString());
        txfImc.setText(oExamenClinico.getImc().toString());
        txfPa.setText(oExamenClinico.getPresionArterial() + "/" + oExamenClinico.getPresionArterial2());
        txfFc.setText(oExamenClinico.getFrecCardiaca().toString());
    }

    private void buscarResultadoOftalmologia(AtencionOcupacional oAtencionOcupacional) {
        oFichaOftalmologica = new FichaOftalmologica();
        oFichaOftalmologicaBl = new FichaOftalmologicaBl();
        txfOftalmologia.setText(oFichaOftalmologicaBl.getConclusion(oAtencionOcupacional));
    }

    private void buscarResultadoAudiometria(AtencionOcupacional oAtencionOcupacional) {
        oFichaAudiometriaBl = new FichaAudiometriaBl();
        txfAudiometria.setText(oFichaAudiometriaBl.getConclusion(oAtencionOcupacional));
    }

    private void buscarResultadoPsicologia(AtencionOcupacional oAtencionOcupacional) {
        oFichaPsicologicaBl = new FichaPsicologicaBl();
        oFichaPsicologica = oFichaPsicologicaBl.getConclusion(oAtencionOcupacional);
        if (oFichaPsicologica != null) {
            txfPsilogico.setText(oFichaPsicologica.getCondicion());
        }

    }

    private void buscarResultadoPsicotecnico(AtencionOcupacional oAtencionOcupacional) {
        oFichaPsicologicaPsicotecnicoBl = new FichaPsicologicaPsicotecnicoBl();
        oFichaPsicologicaPsicotecnico = oFichaPsicologicaPsicotecnicoBl.getConclusion(oAtencionOcupacional);
        if (oFichaPsicologicaPsicotecnico != null) {
            txfPsicotecnico.setText(oFichaPsicologicaPsicotecnico.getCondicion());
        }

    }

    private boolean isDatosValidos() {
        return true;
    }

    private InformeMedicoOcupacional registrarInforme() {
        oInformeMedicoOcupacional = new InformeMedicoOcupacional();
        oInformeMedicoOcupacionalBl = new InformeMedicoOcupacionalBl();

        oInformeMedicoOcupacional.setIdExamenclinico(oExamenClinico.getIdexamenclinico());
        oInformeMedicoOcupacional.setIdUsuario(userTemp.getIdUsuario());
        oInformeMedicoOcupacional.setAtencionOcupacional(oAtencionOcupacional);
        oInformeMedicoOcupacional.setExamenMusculoEsqueletico(txfExMusculoEsqueletico.getText().toUpperCase().trim());
        /*Examenes de laboratorio*/
        oInformeMedicoOcupacional.setGrupoFactor(txfGrupoFx.getText().trim());
        oInformeMedicoOcupacional.setHemogramaCompleto(txfHemograma.getText().trim());
        oInformeMedicoOcupacional.setBilirrubinaTot(txfBilirrubina.getText().trim());
        oInformeMedicoOcupacional.setExOrina(txfExOrina.getText().trim());
        oInformeMedicoOcupacional.setFosfatasa(txfFosfatasa.getText().trim());
        oInformeMedicoOcupacional.setHisopado(txfHisopado.getText().trim());
        oInformeMedicoOcupacional.setParasitologicoSer(txfParasitologicoSer.getText().trim());
        oInformeMedicoOcupacional.setParasitologicoDir(txfParasitologicoDir.getText().trim());
        oInformeMedicoOcupacional.setVsg(txfVsg.getText().trim());
        oInformeMedicoOcupacional.setGlucosa(txfGlucosa.getText().trim());
        oInformeMedicoOcupacional.setHemoglobina(txfHemoglobina.getText().trim());
        oInformeMedicoOcupacional.setProteinasTot(txfProteinasTot.getText().trim());
        oInformeMedicoOcupacional.setProteinasFrac(txfProteinasFrac.getText().trim());
        oInformeMedicoOcupacional.setGammmaGlutamil(txfGamma.getText().trim());
        oInformeMedicoOcupacional.setCoprocultivo(txfCoprocultivo.getText().trim());
        oInformeMedicoOcupacional.setAglutinaciones(txfAglutinaciones.getText().trim());
        oInformeMedicoOcupacional.setToxicologico(txfToxicologico.getText().trim());
        oInformeMedicoOcupacional.setVdrl(txfVdrl.getText().trim());
        oInformeMedicoOcupacional.setUrea(txfUrea.getText().trim());
        oInformeMedicoOcupacional.setColesterol(txfColesterol.getText().trim());
        oInformeMedicoOcupacional.setCreatinina(txfCreatinina.getText().trim());
        oInformeMedicoOcupacional.setTgp(txfTgp.getText().trim());
        oInformeMedicoOcupacional.setTgo(txfTgo.getText().trim());
        oInformeMedicoOcupacional.setBkEsputo(txfBkEsputo.getText().trim());
        oInformeMedicoOcupacional.setHepatitis(txfHepatitis.getText().trim());
        oInformeMedicoOcupacional.setSubUnidadBeta(txfSubUniBeta.getText().trim());
        oInformeMedicoOcupacional.setKhoUnas(txfKhoUnas.getText().trim());        
        /*Examenes complementarios*/   
        oInformeMedicoOcupacional.setRxTorax(txfRxTorax.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setRxLumbar(txfRxLumbar.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setEspirometria(txfEspirometria.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setAudiometria(txfAudiometria.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setElectroencefalograma(txfElectroencefalograma.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setPruebaEsfuerzo(txfPruebaEsfuerzo.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setEkg(txfEkg.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setPsicologia(txfPsilogico.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setPsicotecnico(txfPsicotecnico.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setTestEstres(txfTestEstres.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setTstEpworth(txfTestEpworth.getText().toUpperCase().trim());        
        oInformeMedicoOcupacional.setOftalmologia(txfOftalmologia.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setOdontograma(txfOdontograma.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setDermatologia(txfDermatologia.getText().toUpperCase().trim());
        /**/
        oInformeMedicoOcupacional.setDiagnosticoCie10(txaDiagnostico.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setConclusiones(txaConclusiones.getText().toUpperCase().trim());
        oInformeMedicoOcupacional.setRecomendaciones(txaRecomendaciones.getText().toUpperCase().trim());

        return oInformeMedicoOcupacionalBl.registrar(oInformeMedicoOcupacional);

    }

    private void buscarAntPersonales(AtencionOcupacional oAtencionOcupacional) {
        oSoFmoAntecedentesPatPerBl = new SoFmoAntecedentesPatPerBl();
        String ant = "";
        oSoFmoAntecedentesPatPer = oSoFmoAntecedentesPatPerBl.buscarAntPatPer(oAtencionOcupacional);
        if (oSoFmoAntecedentesPatPer != null) {
            if (oSoFmoAntecedentesPatPer.isAlergia()) {
                ant = ant + "Alergia,";
            }
            if (oSoFmoAntecedentesPatPer.isDiabetes()) {
                ant = ant + " Diabetes,";
            }
            if (oSoFmoAntecedentesPatPer.isTbc()) {
                ant = ant + " Tbc,";
            }
            if (oSoFmoAntecedentesPatPer.isHepatitisb()) {
                ant = ant + " Hepatitis,";
            }
            if (oSoFmoAntecedentesPatPer.isAsma()) {
                ant = ant + " Asma,";
            }
            if (oSoFmoAntecedentesPatPer.isHta()) {
                ant = ant + " hta,";
            }
            if (oSoFmoAntecedentesPatPer.isIts()) {
                ant = ant + " Its,";
            }
            if (oSoFmoAntecedentesPatPer.isTifoidea()) {
                ant = ant + " Tifoidea,";
            }
            if (oSoFmoAntecedentesPatPer.isBronquitis()) {
                ant = ant + " Bronquitis,";
            }
            if (oSoFmoAntecedentesPatPer.isNeoplasia()) {
                ant = ant + " Neoplasia,";
            }
            if (oSoFmoAntecedentesPatPer.isConvulsiones()) {
                ant = ant + " Convulsiones,";
            }
            if (oSoFmoAntecedentesPatPer.isQuemaduras()) {
                ant = ant + " Quemaduras,";
            }
            if (oSoFmoAntecedentesPatPer.isCirugias()) {
                ant = ant + " Cirugias,";
            }
            if (oSoFmoAntecedentesPatPer.isIntoxicaciones()) {
                ant = ant + " Intoxicaciones,";
            }
            if (oSoFmoAntecedentesPatPer.isOtros()) {
                ant = ant + " Otros";
            }
        }
    }

    private void buscarAntFamiliares(AtencionOcupacional oAtencionOcupacional) {
        oSoFmoAntecedentesPatFamBl = new SoFmoAntecedentesPatFamBl();
        String ant = "";
        oSoFmoAntecedentesPatFam = oSoFmoAntecedentesPatFamBl.buscarAntPatPer(oAtencionOcupacional);
        if (oSoFmoAntecedentesPatFam != null) {
            if (!oSoFmoAntecedentesPatFam.getPadre().equals("") && oSoFmoAntecedentesPatFam.getPadre() != null) {
                ant = ant + oSoFmoAntecedentesPatFam.getPadre();
            }
            if (!oSoFmoAntecedentesPatFam.getMadre().equals("") && oSoFmoAntecedentesPatFam.getMadre() != null) {
                ant = ant + ", " + oSoFmoAntecedentesPatFam.getMadre();
            }
            if (!oSoFmoAntecedentesPatFam.getHermanos().equals("") && oSoFmoAntecedentesPatFam.getHermanos() != null) {
                ant = ant + ", " + oSoFmoAntecedentesPatFam.getHermanos();
            }
            if (!oSoFmoAntecedentesPatFam.getEsposoa().equals("") && oSoFmoAntecedentesPatFam.getEsposoa() != null) {
                ant = ant + ", " + oSoFmoAntecedentesPatFam.getEsposoa();
            }
        }
    }

    private void imprimirInforme(InformeMedicoOcupacional oInformeMedicoOcupacional) {
        try {
            ds = new DSConeccion(root.getConfig());
            reportGenric = new ReportGeneric(ds.getConeccion());
            reportGenric.setReportParent("/lissa/reportes/");
            reportPanel = reportGenric.mkReport("SO_InformeMedicoOcupacional2", new String[]{"ID"}, new Object[]{oInformeMedicoOcupacional.getIdinformemedicoocupacional()});
            reportVisor = new JInternalFrame();
            reportVisor.setTitle("Informe Medico Ocupacional");
            reportVisor.setIconifiable(true);
            reportVisor.setClosable(true);
            reportVisor.getContentPane().add(reportPanel);
            root.insertarInternalFrames(reportVisor);
            reportVisor.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(JPanel_InformeMedicoOcupacional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetComponent() {
        txfTalla.setText("");
        txfPeso.setText("");
        txfFc.setText("");
        txfPa.setText("");
        txfImc.setText(""); 
        txfGrupoFx.setText("");
        txfHemograma.setText("");
        txfBilirrubina.setText("");
        txfExOrina.setText("");
        txfFosfatasa.setText("");
        txfHisopado.setText("");
        txfParasitologicoSer.setText("");
        txfParasitologicoDir.setText("");
        txfVsg.setText("");
        txfGlucosa.setText("");
        txfHemoglobina.setText("");
        txfProteinasTot.setText("");
        txfProteinasFrac.setText("");
        txfGamma.setText("");
        txfCoprocultivo.setText("");
        txfAglutinaciones.setText("");
        txfToxicologico.setText("");
        txfVdrl.setText("");
        txfUrea.setText("");
        txfColesterol.setText("");
        txfCreatinina.setText("");
        txfTgp.setText("");
        txfTgo.setText("");
        txfBkEsputo.setText("");
        txfHepatitis.setText("");
        txfSubUniBeta.setText("");
        txfKhoUnas.setText("");
        /**/
        txfRxTorax.setText("");
        txfRxLumbar.setText("");
        txfEspirometria.setText("");
        txfAudiometria.setText("");
        txfElectroencefalograma.setText("");
        txfPruebaEsfuerzo.setText("");
        txfEkg.setText("");
        txfPsilogico.setText("");
        txfPsicotecnico.setText("");
        txfTestEstres.setText("");
        txfTestEpworth.setText("");        
        txfOftalmologia.setText("");
        txfOdontograma.setText("");
        txfDermatologia.setText("");
        txaDiagnostico.setText("");
        txaConclusiones.setText("");
        txaRecomendaciones.setText("");
    }
}
