package lissa.gui.ocupacional;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lissa.be.AtencionOcupacional;
import lissa.be.CertMedicoOcupacional;
import lissa.be.CertMedicoOcupacional2;
import lissa.be.Cie10;
import lissa.be.CmoCie10;
import lissa.be.CmoObservaciones;
import lissa.be.CmoObservaciones2;
import lissa.be.CmoRecomendaciones;
import lissa.be.CmoRecomendaciones2;
import lissa.be.Condicion;
import lissa.be.ExamenOcupacional;
import lissa.be.FmoRestricciones;
import lissa.be.FmoRestricciones2;
import lissa.be.MotivoObservacion;
import lissa.be.Persona;
import lissa.be.Recomendacion;
import lissa.be.Restriccion;
import lissa.bl.CertMedicoOcupacional2Bl;
import lissa.bl.CertMedicoOcupacionalBl;
import lissa.bl.CmoCie10Bl;
import lissa.bl.CmoObservaciones2Bl;
import lissa.bl.CmoObservacionesBl;
import lissa.bl.CmoRecomendaciones2Bl;
import lissa.bl.CmoRecomendacionesBl;
import lissa.bl.FmoRestricciones2Bl;
import lissa.bl.FmoRestriccionesBl;
import lissa.controller.CondicionCtrl;
import lissa.controller.ExamenOcupacionalCtrl;
import lissa.controller.MotivoObservacionCtrl;
import lissa.controller.RecomendacionCtrl;
import lissa.controller.RestriccionCtrl;
import lissa.ds.DSConeccion;
import lissa.gui.JF_Principal;
import lissa.reportes.ReportGeneric;
import lissa.table.ModeloCmoCie10;
import lissa.table.ModeloObservacion;
import lissa.table.ModeloObservacion2;
import lissa.table.ModeloRecomendacion;
import lissa.table.ModeloRecomendacion2;
import lissa.table.ModeloRestricciones1;
import lissa.table.ModeloRestricciones2;
import lissa.util.Mensajes;
import org.rx.cr.util.Utilitarios;

public class JIF_Certificados extends javax.swing.JInternalFrame {

    private JF_Principal root;
    private CondicionCtrl oCondicionCtrl;
    private ExamenOcupacionalCtrl oExamenOcupacionalCtrl;
    private RestriccionCtrl oRestriccionCtrl;
    private MotivoObservacionCtrl oMotivoObservacionCtrl;
    private RecomendacionCtrl oRecomendacionCtrl;
    private ModeloRestricciones1 oModeloRestricciones1;
    private ModeloObservacion oModeloObservacion1;
    private ModeloRecomendacion oModeloRecomendacion;
    private Persona oPersona;
    private AtencionOcupacional oAtencionOcupacional;
    private CertMedicoOcupacional oCertMedicoOcupacional;
    private CertMedicoOcupacionalBl oCertMedicoOcupacionalBl;
    private CertMedicoOcupacional2 oCertMedicoOcupacional2;
    private CertMedicoOcupacional2Bl oCertMedicoOcupacional2Bl;
    private ModeloRestricciones2 oModeloRestricciones2;
    private ModeloObservacion2 oModeloObservacion2;
    private ModeloRecomendacion2 oModeloRecomendacion2;
    private Cie10 oCie10;
    private ModeloCmoCie10 oModeloCmoCie10;
    private CmoCie10 oCmoCie10;
    private CmoCie10Bl oCmoCie10Bl;
    //Variables para el reporte
    private ReportGeneric reportGenric = null;
    private JPanel reportPanel = null;
    private DSConeccion ds = null;
    private JInternalFrame reportVisor = null;

    public JIF_Certificados(JF_Principal root) {
        initComponents();
        this.root = root;
        oModeloRestricciones1 = new ModeloRestricciones1();
        tblRestricciones1.setModel(oModeloRestricciones1);
        oModeloObservacion1 = new ModeloObservacion();
        tblOnservaciones1.setModel(oModeloObservacion1);
        oModeloRecomendacion = new ModeloRecomendacion();
        tblRecomendaciones.setModel(oModeloRecomendacion);

        oModeloRestricciones2 = new ModeloRestricciones2();
        tblRestricciones2.setModel(oModeloRestricciones2);
        oModeloObservacion2 = new ModeloObservacion2();
        tblOnservaciones2.setModel(oModeloObservacion2);
        oModeloRecomendacion2 = new ModeloRecomendacion2();
        tblRecomendaciones1.setModel(oModeloRecomendacion2);

        oModeloCmoCie10 = new ModeloCmoCie10();
        tblComCie10.setModel(oModeloCmoCie10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbxCondicion1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxRestricciones1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbxObservacion1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbxRecomendacion1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbxCategoria1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecomendaciones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOnservaciones1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRestricciones1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        txfCie10Desc = new javax.swing.JTextField();
        txfCie10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblComCie10 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxRecomendacion2 = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRestricciones2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbxCategoria3 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRecomendaciones1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        cbxCondicion2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cbxRestricciones2 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cbxObservacion2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblOnservaciones2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfApellidosNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfEmpresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfPuestoLaboral = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setTitle("Certificado de Aptitud Medico Ocupacional");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel8.setText("Condición :");

        jLabel9.setText("Restricciones :");

        jLabel10.setText("Motivo de la Observación :");

        jLabel11.setText("Recomendaciones :");

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Categoria :");

        cbxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoria1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblRecomendaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblRecomendaciones);

        tblOnservaciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblOnservaciones1);

        tblRestricciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblRestricciones1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRecomendacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxCondicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxRestricciones1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(73, 73, 73)
                            .addComponent(jButton3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(jButton4))
                                .addComponent(cbxCategoria1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxCondicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxRestricciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel10)
                    .addComponent(cbxObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxRecomendacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CERTIFICADO1", jPanel1);

        jLabel57.setText("CIE-10 :");

        txfCie10Desc.setEnabled(false);

        txfCie10.setEnabled(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/search.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/add.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/remove.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        tblComCie10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane12.setViewportView(tblComCie10);

        jButton13.setText("Guardar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addComponent(txfCie10Desc, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(txfCie10, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton13)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(txfCie10Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfCie10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CERTIFICADO2", jPanel2);

        tblRestricciones2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblRestricciones2);

        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("+");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel14.setText("Categoria :");

        cbxCategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoria3ActionPerformed(evt);
            }
        });

        jButton12.setText("Guardar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        tblRecomendaciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblRecomendaciones1);

        jLabel15.setText("Condición :");

        jLabel16.setText("Restricciones :");

        jLabel17.setText("Motivo de la Observación :");

        jLabel18.setText("Recomendaciones :");

        tblOnservaciones2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tblOnservaciones2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRecomendacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton11))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbxRestricciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxCondicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                        .addComponent(jScrollPane6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxObservacion2, 0, 261, Short.MAX_VALUE)
                                    .addComponent(cbxCategoria3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addComponent(jButton10)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbxCondicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbxCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbxRestricciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jLabel17)
                    .addComponent(cbxObservacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbxRecomendacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 164, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CERTIFICADO3", jPanel3);

        jLabel3.setText("Apellidos y Nombres :");

        txfApellidosNombres.setEnabled(false);

        jLabel4.setText("N° de DNI :");

        txfDni.setEnabled(false);

        jLabel5.setText("Edad :");

        txfEdad.setEnabled(false);

        jLabel6.setText("Empresa :");

        txfEmpresa.setEnabled(false);

        jLabel7.setText("Puesto Laboral :");

        txfPuestoLaboral.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txfDni)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txfPuestoLaboral)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txfPuestoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoria1ActionPerformed
        if (cbxCategoria1.getSelectedIndex() > 0) {
            cargarCombosDependientes();
        }

    }//GEN-LAST:event_cbxCategoria1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cbxRestricciones1.getSelectedIndex() > 0) {
            agregarRestricciones();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cbxObservacion1.getSelectedIndex() > 0) {
            agregarObservaciones();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (cbxRecomendacion1.getSelectedIndex() > 0) {
            agregarRecomendaciones();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardarCertificado1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        root.insertarInternalFrames(root.jifAdminCie10);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (isDatosValidosCie10()) {
            agregarCie10();
            personalizaVistaTabla();
            resetComponentCie10();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Cie10", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (cbxRestricciones2.getSelectedIndex() > 0) {
            agregarRestricciones2();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (cbxObservacion2.getSelectedIndex() > 0) {
            agregarObservaciones2();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (cbxRecomendacion2.getSelectedIndex() > 0) {
            agregarRecomendaciones2();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cbxCategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoria3ActionPerformed
        if (cbxCategoria3.getSelectedIndex() > 0) {
            cargarCombosDependientes2();
        }
    }//GEN-LAST:event_cbxCategoria3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        guardarCertificado3();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (oModeloCmoCie10.size() > 0) {
            guardarCmoCie10();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCategoria1;
    private javax.swing.JComboBox cbxCategoria3;
    private javax.swing.JComboBox cbxCondicion1;
    private javax.swing.JComboBox cbxCondicion2;
    private javax.swing.JComboBox cbxObservacion1;
    private javax.swing.JComboBox cbxObservacion2;
    private javax.swing.JComboBox cbxRecomendacion1;
    private javax.swing.JComboBox cbxRecomendacion2;
    private javax.swing.JComboBox cbxRestricciones1;
    private javax.swing.JComboBox cbxRestricciones2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblComCie10;
    private javax.swing.JTable tblOnservaciones1;
    private javax.swing.JTable tblOnservaciones2;
    private javax.swing.JTable tblRecomendaciones;
    private javax.swing.JTable tblRecomendaciones1;
    private javax.swing.JTable tblRestricciones1;
    private javax.swing.JTable tblRestricciones2;
    private javax.swing.JTextField txfApellidosNombres;
    private javax.swing.JTextField txfCie10;
    private javax.swing.JTextField txfCie10Desc;
    private javax.swing.JTextField txfDni;
    private javax.swing.JTextField txfEdad;
    private javax.swing.JTextField txfEmpresa;
    private javax.swing.JTextField txfPuestoLaboral;
    // End of variables declaration//GEN-END:variables

    void iniciar() {
        oCondicionCtrl = new CondicionCtrl(root);
        oCondicionCtrl.rellenaCbx(cbxCondicion1);
        oExamenOcupacionalCtrl = new ExamenOcupacionalCtrl(root);
        oExamenOcupacionalCtrl.rellenaCbx(cbxCategoria1);
        oCondicionCtrl.rellenaCbx(cbxCondicion2);
        oExamenOcupacionalCtrl.rellenaCbx(cbxCategoria3);
    }

    private void cargarCombosDependientes() {
        oRestriccionCtrl = new RestriccionCtrl(root);
        oRestriccionCtrl.rellenaCbx(cbxRestricciones1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
        //
        oMotivoObservacionCtrl = new MotivoObservacionCtrl(root);
        oMotivoObservacionCtrl.rellenaCbx(cbxObservacion1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
        //
        oRecomendacionCtrl = new RecomendacionCtrl(root);
        oRecomendacionCtrl.rellenaCbx(cbxRecomendacion1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
    }

    private void agregarRestricciones() {
        FmoRestricciones fmoRestriccion = new FmoRestricciones();
        fmoRestriccion.setIdRestriccion(((Restriccion) cbxRestricciones1.getSelectedItem()).getIdrestriccion());
        oModeloRestricciones1.add(fmoRestriccion);
        cbxRestricciones1.setSelectedIndex(0);
    }

    private void agregarObservaciones() {
        CmoObservaciones oCmoObservaciones = new CmoObservaciones();
        oCmoObservaciones.setIdObservacion(((MotivoObservacion) cbxObservacion1.getSelectedItem()).getIdmotivoobservacion());
        oModeloObservacion1.add(oCmoObservaciones);
        cbxObservacion1.setSelectedIndex(0);
    }

    private void agregarRecomendaciones() {
        CmoRecomendaciones oCmoRecomendaciones = new CmoRecomendaciones();
        oCmoRecomendaciones.setIdRecomendacion(((Recomendacion) cbxRecomendacion1.getSelectedItem()).getIdrecomendacion());
        oModeloRecomendacion.add(oCmoRecomendaciones);
        cbxRecomendacion1.setSelectedIndex(0);
    }

    private void guardarCertificado1() {
        if (isDatosValidos()) {
            oCertMedicoOcupacional = guardarGenerales();
            if (oCertMedicoOcupacional != null) {
                if (oModeloRestricciones1.size() > 0) {
                    guardarRestricciones1();
                }
                if (oModeloObservacion1.size() > 0) {
                    guardarObservaciones1();
                }
                if (oModeloRestricciones1.size() > 0) {
                    guardarRecomendaciones1();
                }
                Mensajes.msjRegCorrecta();
                imprimirCertificado(oCertMedicoOcupacional);
                resetComponentCert1();
            }

        }
    }

    private boolean isDatosValidos() {
        return (cbxCondicion1.getSelectedIndex() > 0);
    }

    private void guardarRestricciones1() {
        FmoRestriccionesBl oFmoRestriccionesBl = new FmoRestriccionesBl();
        for (int i = 0; i < oModeloRestricciones1.size(); i++) {
            FmoRestricciones oFmoRestricciones = new FmoRestricciones();
            oFmoRestricciones = oModeloRestricciones1.get(i);
            oFmoRestricciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oFmoRestriccionesBl.registrar(oFmoRestricciones);
        }
    }

    private void guardarObservaciones1() {
        CmoObservacionesBl oCmoObservacionesBl = new CmoObservacionesBl();
        for (int i = 0; i < oModeloObservacion1.size(); i++) {
            CmoObservaciones oCmoObservaciones = new CmoObservaciones();
            oCmoObservaciones = oModeloObservacion1.get(i);
            oCmoObservaciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oCmoObservacionesBl.registrar(oCmoObservaciones);
        }
    }

    private void guardarRecomendaciones1() {
        CmoRecomendacionesBl oCmoRecomendacionesBl = new CmoRecomendacionesBl();
        for (int i = 0; i < oModeloRecomendacion.size(); i++) {
            CmoRecomendaciones oCmoRecomendaciones = new CmoRecomendaciones();
            oCmoRecomendaciones = oModeloRecomendacion.get(i);
            oCmoRecomendaciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oCmoRecomendacionesBl.registrar(oCmoRecomendaciones);
        }
    }

    private CertMedicoOcupacional guardarGenerales() {
        oCertMedicoOcupacional = new CertMedicoOcupacional();
        oCertMedicoOcupacionalBl = new CertMedicoOcupacionalBl();
        oCertMedicoOcupacional.setAtencionOcupacional(oAtencionOcupacional);
        oCertMedicoOcupacional.setCondicion((Condicion) cbxCondicion1.getSelectedItem());
        return oCertMedicoOcupacionalBl.registrar(oCertMedicoOcupacional);

    }

    void enviarDatos(AtencionOcupacional oAtencionOcupacional, Persona beanTablaPersona) {
        this.oPersona = beanTablaPersona;
        this.oAtencionOcupacional = oAtencionOcupacional;
        resetCampos(oPersona, oAtencionOcupacional);
    }

    private void resetCampos(Persona oPersona, AtencionOcupacional oAtencionOcupacional) {
        txfApellidosNombres.setText(oPersona.getApellidoPaterno().trim() + " " + oPersona.getApellidoMaterno().trim() + " " + oPersona.getNombre().trim());
        txfDni.setText(oPersona.getNumeroDocumento().trim());
        txfEdad.setText(oAtencionOcupacional.getEdadIngreso().toString());
        txfEmpresa.setText(oAtencionOcupacional.getPersonaJuridica().getRazonSocial().trim());
        txfPuestoLaboral.setText(oAtencionOcupacional.getPuestoLaboral().getPuestoLaboral().trim());
    }

    private void guardarCertificado3() {
        if (isDatosValidos2()) {
            oCertMedicoOcupacional2 = guardarGenerales2();
            if (oCertMedicoOcupacional2 != null) {
                if (oModeloRestricciones2.size() > 0) {
                    guardarRestricciones2();
                }
                if (oModeloObservacion2.size() > 0) {
                    guardarObservaciones2();
                }
                if (oModeloRestricciones2.size() > 0) {
                    guardarRecomendaciones2();
                }
                Mensajes.msjRegCorrecta();
                imprimirCertificado3(oCertMedicoOcupacional2);
                resetComponentCert3();
            }

        }
    }

    private CertMedicoOcupacional2 guardarGenerales2() {
        oCertMedicoOcupacional2 = new CertMedicoOcupacional2();
        oCertMedicoOcupacional2Bl = new CertMedicoOcupacional2Bl();
        oCertMedicoOcupacional2.setAtencionOcupacional(oAtencionOcupacional);
        oCertMedicoOcupacional2.setCondicion((Condicion) cbxCondicion2.getSelectedItem());
        return oCertMedicoOcupacional2Bl.registrar(oCertMedicoOcupacional2);
    }

    private void guardarRestricciones2() {
        FmoRestricciones2Bl oFmoRestricciones2Bl = new FmoRestricciones2Bl();
        for (int i = 0; i < oModeloRestricciones2.size(); i++) {
            FmoRestricciones2 oFmoRestricciones2 = new FmoRestricciones2();
            oFmoRestricciones2 = oModeloRestricciones2.get(i);
            oFmoRestricciones2.setCertMedicoOcupacional2(oCertMedicoOcupacional2);
            oFmoRestricciones2Bl.registrar(oFmoRestricciones2);
        }
    }

    private void guardarObservaciones2() {
        CmoObservaciones2Bl oCmoObservaciones2Bl = new CmoObservaciones2Bl();
        for (int i = 0; i < oModeloObservacion2.size(); i++) {
            CmoObservaciones2 oCmoObservaciones2 = new CmoObservaciones2();
            oCmoObservaciones2 = oModeloObservacion2.get(i);
            oCmoObservaciones2.setCertMedicoOcupacional2(oCertMedicoOcupacional2);
            oCmoObservaciones2Bl.registrar(oCmoObservaciones2);
        }
    }

    private void guardarRecomendaciones2() {
        CmoRecomendaciones2Bl oCmoRecomendaciones2Bl = new CmoRecomendaciones2Bl();
        for (int i = 0; i < oModeloRecomendacion2.size(); i++) {
            CmoRecomendaciones2 oCmoRecomendaciones2 = new CmoRecomendaciones2();
            oCmoRecomendaciones2 = oModeloRecomendacion2.get(i);
            oCmoRecomendaciones2.setCertMedicoOcupacional2(oCertMedicoOcupacional2);
            oCmoRecomendaciones2Bl.registrar(oCmoRecomendaciones2);
        }
    }

    private void cargarCombosDependientes2() {
        oRestriccionCtrl = new RestriccionCtrl(root);
        oRestriccionCtrl.rellenaCbx(cbxRestricciones2, ((ExamenOcupacional) cbxCategoria3.getSelectedItem()).getIdexamenocupacional());
        //
        oMotivoObservacionCtrl = new MotivoObservacionCtrl(root);
        oMotivoObservacionCtrl.rellenaCbx(cbxObservacion2, ((ExamenOcupacional) cbxCategoria3.getSelectedItem()).getIdexamenocupacional());
        //
        oRecomendacionCtrl = new RecomendacionCtrl(root);
        oRecomendacionCtrl.rellenaCbx(cbxRecomendacion2, ((ExamenOcupacional) cbxCategoria3.getSelectedItem()).getIdexamenocupacional());
    }

    private void agregarRestricciones2() {
        FmoRestricciones2 fmoRestriccion = new FmoRestricciones2();
        fmoRestriccion.setIdRestriccion(((Restriccion) cbxRestricciones2.getSelectedItem()).getIdrestriccion());
        oModeloRestricciones2.add(fmoRestriccion);
        cbxRestricciones2.setSelectedIndex(0);
    }

    private void agregarObservaciones2() {
        CmoObservaciones2 oCmoObservaciones = new CmoObservaciones2();
        oCmoObservaciones.setIdObservacion(((MotivoObservacion) cbxObservacion2.getSelectedItem()).getIdmotivoobservacion());
        oModeloObservacion2.add(oCmoObservaciones);
        cbxObservacion2.setSelectedIndex(0);
    }

    private void agregarRecomendaciones2() {
        CmoRecomendaciones2 oCmoRecomendaciones = new CmoRecomendaciones2();
        oCmoRecomendaciones.setIdRecomendacion(((Recomendacion) cbxRecomendacion2.getSelectedItem()).getIdrecomendacion());
        oModeloRecomendacion2.add(oCmoRecomendaciones);
        cbxRecomendacion2.setSelectedIndex(0);
    }

    private boolean isDatosValidos2() {
        return (cbxCondicion2.getSelectedIndex() > 0);
    }

    public void cargarCie10(Cie10 beanTabla) {
        oCie10 = beanTabla;
        txfCie10.setText(oCie10.getCodigo());
        txfCie10Desc.setText(oCie10.getDescripcion());
    }

    private boolean isDatosValidosCie10() {
        return (oCie10 != null);
    }

    private void agregarCie10() {
        CmoCie10 oCmoCie10 = new CmoCie10();
        oCmoCie10.setIdCie10(oCie10.getIdcie10());
        oModeloCmoCie10.add(oCmoCie10);
    }

    private void resetComponentCie10() {
        txfCie10.setText("");
        txfCie10Desc.setText("");
        oCie10 = null;
    }

    private void personalizaVistaTabla() {
        Utilitarios.formateaAnchoColumnaTabla(0, tblComCie10, 50);
    }

    private void guardarCmoCie10() {
        oCmoCie10Bl = new CmoCie10Bl();
        for (int i = 0; i < oModeloCmoCie10.size(); i++) {
            oCmoCie10 = new CmoCie10();
            oCmoCie10 = oModeloCmoCie10.get(i);
            oCmoCie10.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oCmoCie10Bl.registrar(oCmoCie10);
            if (i == oModeloCmoCie10.size() - 1) {
                imprimirCert2(oCertMedicoOcupacional);
                //resetComponent
                resetComponentCert2();
            }
        }
        //imprimir

    }

    private void imprimirCertificado(CertMedicoOcupacional oCertMedicoOcupacional) {
        try {
            ds = new DSConeccion(root.getConfig());
            reportGenric = new ReportGeneric(ds.getConeccion());
            reportGenric.setReportParent("/lissa/reportes/");
            reportPanel = reportGenric.mkReport("Certificado1", new String[]{"ID"}, new Object[]{oCertMedicoOcupacional.getIdcertmedicoocupacional()});
            reportVisor = new JInternalFrame();
            reportVisor.setTitle("Reporte");
            reportVisor.setIconifiable(true);
            reportVisor.setResizable(true);
            reportVisor.setClosable(true);
            reportVisor.getContentPane().add(reportPanel);
            root.insertarInternalFrames(reportVisor);
            reportVisor.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(JIF_Certificados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetComponentCert1() {
        oModeloObservacion1.clear();
        oModeloRestricciones1.clear();
        oModeloRecomendacion.clear();
        cbxCondicion1.setSelectedIndex(0);
        cbxCategoria1.setSelectedIndex(0);
        cbxRestricciones1.setSelectedIndex(0);
        cbxObservacion1.setSelectedIndex(0);
        cbxRecomendacion1.setSelectedIndex(0);
    }

    private void imprimirCert2(CertMedicoOcupacional oCertMedicoOcupacional) {
        try {
            ds = new DSConeccion(root.getConfig());
            reportGenric = new ReportGeneric(ds.getConeccion());
            reportGenric.setReportParent("/lissa/reportes/");
            reportPanel = reportGenric.mkReport("Certificado2", new String[]{"ID"}, new Object[]{oCertMedicoOcupacional.getIdcertmedicoocupacional()});
            reportVisor = new JInternalFrame();
            reportVisor.setTitle("Reporte");
            reportVisor.setIconifiable(true);
            reportVisor.setResizable(true);
            reportVisor.setClosable(true);
            reportVisor.getContentPane().add(reportPanel);
            root.insertarInternalFrames(reportVisor);
            reportVisor.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(JIF_Certificados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetComponentCert2() {
        txfCie10.setText("");
        txfCie10Desc.setText("");
        oModeloCmoCie10.clear();
    }

    private void imprimirCertificado3(CertMedicoOcupacional2 oCertMedicoOcupacional) {
        try {
            ds = new DSConeccion(root.getConfig());
            reportGenric = new ReportGeneric(ds.getConeccion());
            reportGenric.setReportParent("/lissa/reportes/");
            reportPanel = reportGenric.mkReport("Certificado3", new String[]{"ID"}, new Object[]{oCertMedicoOcupacional.getIdcertmedicoocupacional()});
            reportVisor = new JInternalFrame();
            reportVisor.setTitle("Reporte");
            reportVisor.setIconifiable(true);
            reportVisor.setResizable(true);
            reportVisor.setClosable(true);
            reportVisor.getContentPane().add(reportPanel);
            root.insertarInternalFrames(reportVisor);
            reportVisor.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(JIF_Certificados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetComponentCert3() {
        oModeloObservacion2.clear();
        oModeloRestricciones2.clear();
        oModeloRecomendacion2.clear();
        cbxCondicion2.setSelectedIndex(0);
        cbxCategoria3.setSelectedIndex(0);
        cbxRestricciones2.setSelectedIndex(0);
        cbxObservacion2.setSelectedIndex(0);
        cbxRecomendacion2.setSelectedIndex(0);
    }
}
