package lissa.gui.ocupacional;

import lissa.be.AtencionOcupacional;
import lissa.be.CertMedicoOcupacional;
import lissa.be.CmoObservaciones;
import lissa.be.CmoRecomendaciones;
import lissa.be.Condicion;
import lissa.be.ExamenOcupacional;
import lissa.be.FmoRestricciones;
import lissa.be.MotivoObservacion;
import lissa.be.Persona;
import lissa.be.Recomendacion;
import lissa.be.Restriccion;
import lissa.bl.CertMedicoOcupacionalBl;
import lissa.bl.CmoObservacionesBl;
import lissa.bl.CmoRecomendacionesBl;
import lissa.bl.FmoRestriccionesBl;
import lissa.controller.CondicionCtrl;
import lissa.controller.ExamenOcupacionalCtrl;
import lissa.controller.MotivoObservacionCtrl;
import lissa.controller.RecomendacionCtrl;
import lissa.controller.RestriccionCtrl;
import lissa.gui.JF_Principal;
import lissa.table.ModeloObservacion;
import lissa.table.ModeloRecomendacion;
import lissa.table.ModeloRestricciones1;

public class JIF_Certificados extends javax.swing.JInternalFrame {

    private JF_Principal root;
    private CondicionCtrl oCondicionCtrl;
    private ExamenOcupacionalCtrl oExamenOcupacionalCtrl;
    private RestriccionCtrl oRestriccionCtrl;
    private MotivoObservacionCtrl oMotivoObservacionCtrl;
    private RecomendacionCtrl oRecomendacionCtrl;
    private ModeloRestricciones1 oModeloRestricciones1;
    private ModeloObservacion oModeloObservacion1;
    private ModeloRecomendacion oModeloRecomendacion;
    private Persona oPersona;
    private AtencionOcupacional oAtencionOcupacional;
    private CertMedicoOcupacional oCertMedicoOcupacional;
    private CertMedicoOcupacionalBl oCertMedicoOcupacionalBl;

    public JIF_Certificados(JF_Principal root) {
        initComponents();
        this.root = root;
        oModeloRestricciones1 = new ModeloRestricciones1();
        tblRestricciones1.setModel(oModeloRestricciones1);
        oModeloObservacion1 = new ModeloObservacion();
        tblOnservaciones1.setModel(oModeloObservacion1);
        oModeloRecomendacion = new ModeloRecomendacion();
        tblRecomendaciones.setModel(oModeloRecomendacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbxCondicion1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxRestricciones1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbxObservacion1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbxRecomendacion1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbxCategoria1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecomendaciones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOnservaciones1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRestricciones1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfApellidosNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfEmpresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfPuestoLaboral = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setTitle("Certificado de Aptitud Medico Ocupacional");

        jLabel8.setText("Condición :");

        jLabel9.setText("Restricciones :");

        jLabel10.setText("Motivo de la Observación :");

        jLabel11.setText("Recomendaciones :");

        jCheckBox1.setText("Replicar");

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Categoria :");

        cbxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoria1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblRecomendaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblRecomendaciones);

        tblOnservaciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblOnservaciones1);

        tblRestricciones1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblRestricciones1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRecomendacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxCondicion1, 0, 324, Short.MAX_VALUE)
                                    .addComponent(cbxRestricciones1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jCheckBox1))
                                .addGap(45, 45, 45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxCondicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxRestricciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel10)
                    .addComponent(cbxObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxRecomendacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CERTIFICADO1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CERTIFICADO2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CERTIFICADO3", jPanel3);

        jLabel1.setText("Evaluación :");

        jComboBox1.setEnabled(false);

        jLabel2.setText("N° de HC :");

        jTextField1.setEnabled(false);

        jLabel3.setText("Apellidos y Nombres :");

        txfApellidosNombres.setEnabled(false);

        jLabel4.setText("N° de DNI :");

        txfDni.setEnabled(false);

        jLabel5.setText("Edad :");

        txfEdad.setEnabled(false);

        jLabel6.setText("Empresa :");

        txfEmpresa.setEnabled(false);

        jLabel7.setText("Puesto Laboral :");

        txfPuestoLaboral.setEnabled(false);

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txfPuestoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txfPuestoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoria1ActionPerformed
        if (cbxCategoria1.getSelectedIndex() > 0) {
            cargarCombosDependientes();
        }

    }//GEN-LAST:event_cbxCategoria1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cbxRestricciones1.getSelectedIndex() > 0) {
            agregarRestricciones();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cbxObservacion1.getSelectedIndex() > 0) {
            agregarObservaciones();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (cbxRecomendacion1.getSelectedIndex() > 0) {
            agregarRecomendaciones();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardarCertificado1();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCategoria1;
    private javax.swing.JComboBox cbxCondicion1;
    private javax.swing.JComboBox cbxObservacion1;
    private javax.swing.JComboBox cbxRecomendacion1;
    private javax.swing.JComboBox cbxRestricciones1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblOnservaciones1;
    private javax.swing.JTable tblRecomendaciones;
    private javax.swing.JTable tblRestricciones1;
    private javax.swing.JTextField txfApellidosNombres;
    private javax.swing.JTextField txfDni;
    private javax.swing.JTextField txfEdad;
    private javax.swing.JTextField txfEmpresa;
    private javax.swing.JTextField txfPuestoLaboral;
    // End of variables declaration//GEN-END:variables

    void iniciar() {
        oCondicionCtrl = new CondicionCtrl(root);
        oCondicionCtrl.rellenaCbx(cbxCondicion1);
        oExamenOcupacionalCtrl = new ExamenOcupacionalCtrl(root);
        oExamenOcupacionalCtrl.rellenaCbx(cbxCategoria1);
    }

    private void cargarCombosDependientes() {
        oRestriccionCtrl = new RestriccionCtrl(root);
        oRestriccionCtrl.rellenaCbx(cbxRestricciones1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
        //
        oMotivoObservacionCtrl = new MotivoObservacionCtrl(root);
        oMotivoObservacionCtrl.rellenaCbx(cbxObservacion1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
        //
        oRecomendacionCtrl = new RecomendacionCtrl(root);
        oRecomendacionCtrl.rellenaCbx(cbxRecomendacion1, ((ExamenOcupacional) cbxCategoria1.getSelectedItem()).getIdexamenocupacional());
    }

    private void agregarRestricciones() {
        FmoRestricciones fmoRestriccion = new FmoRestricciones();
        fmoRestriccion.setIdRestriccion(((Restriccion) cbxRestricciones1.getSelectedItem()).getIdrestriccion());
        oModeloRestricciones1.add(fmoRestriccion);
        cbxRestricciones1.setSelectedIndex(0);
    }

    private void agregarObservaciones() {
        CmoObservaciones oCmoObservaciones = new CmoObservaciones();
        oCmoObservaciones.setIdObservacion(((MotivoObservacion) cbxObservacion1.getSelectedItem()).getIdmotivoobservacion());
        oModeloObservacion1.add(oCmoObservaciones);
        cbxObservacion1.setSelectedIndex(0);
    }

    private void agregarRecomendaciones() {
        CmoRecomendaciones oCmoRecomendaciones = new CmoRecomendaciones();
        oCmoRecomendaciones.setIdRecomendacion(((Recomendacion) cbxRecomendacion1.getSelectedItem()).getIdrecomendacion());
        oModeloRecomendacion.add(oCmoRecomendaciones);
        cbxRecomendacion1.setSelectedIndex(0);
    }

    private void guardarCertificado1() {
        if (isDatosValidos()) {
            oCertMedicoOcupacional = guardarGenerales();
            if (oCertMedicoOcupacional != null) {
                if (oModeloRestricciones1.size() > 0) {
                    guardarRestricciones1();
                }
                if (oModeloObservacion1.size() > 0) {
                    guardarObservaciones1();
                }
                if (oModeloRestricciones1.size() > 0) {
                    guardarRecomendaciones1();
                }
            }

        }
    }

    private boolean isDatosValidos() {
        return (cbxCondicion1.getSelectedIndex() > 0);
    }

    private void guardarRestricciones1() {
        FmoRestriccionesBl oFmoRestriccionesBl = new FmoRestriccionesBl();
        for (int i = 0; i < oModeloRestricciones1.size(); i++) {
            FmoRestricciones oFmoRestricciones = new FmoRestricciones();
            oFmoRestricciones = oModeloRestricciones1.get(i);
            oFmoRestricciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oFmoRestriccionesBl.registrar(oFmoRestricciones);
        }
    }

    private void guardarObservaciones1() {
        CmoObservacionesBl oCmoObservacionesBl = new CmoObservacionesBl();
        for (int i = 0; i < oModeloObservacion1.size(); i++) {
            CmoObservaciones oCmoObservaciones = new CmoObservaciones();
            oCmoObservaciones = oModeloObservacion1.get(i);
            oCmoObservaciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oCmoObservacionesBl.registrar(oCmoObservaciones);
        }
    }

    private void guardarRecomendaciones1() {
        CmoRecomendacionesBl oCmoRecomendacionesBl = new CmoRecomendacionesBl();
        for (int i = 0; i < oModeloRecomendacion.size(); i++) {
            CmoRecomendaciones oCmoRecomendaciones = new CmoRecomendaciones();
            oCmoRecomendaciones = oModeloRecomendacion.get(i);
            oCmoRecomendaciones.setCertMedicoOcupacional(oCertMedicoOcupacional);
            oCmoRecomendacionesBl.registrar(oCmoRecomendaciones);
        }
    }

    private CertMedicoOcupacional guardarGenerales() {
        oCertMedicoOcupacional = new CertMedicoOcupacional();
        oCertMedicoOcupacionalBl = new CertMedicoOcupacionalBl();
        oCertMedicoOcupacional.setAtencionOcupacional(oAtencionOcupacional);
        oCertMedicoOcupacional.setCondicion((Condicion) cbxCondicion1.getSelectedItem());
        return oCertMedicoOcupacionalBl.registrar(oCertMedicoOcupacional);

    }

    void enviarDatos(AtencionOcupacional oAtencionOcupacional, Persona beanTablaPersona) {
        this.oPersona = beanTablaPersona;
        this.oAtencionOcupacional = oAtencionOcupacional;
        resetCampos(oPersona, oAtencionOcupacional);
    }

    private void resetCampos(Persona oPersona, AtencionOcupacional oAtencionOcupacional) {
        txfApellidosNombres.setText(oPersona.getApellidoPaterno().trim() + " " + oPersona.getApellidoMaterno().trim() + " " + oPersona.getNombre().trim());
        txfDni.setText(oPersona.getNumeroDocumento().trim());
        txfEdad.setText(oAtencionOcupacional.getEdadIngreso().toString());
        txfEmpresa.setText(oAtencionOcupacional.getPersonaJuridica().getRazonSocial().trim());
        txfPuestoLaboral.setText(oAtencionOcupacional.getPuestoLaboral().getPuestoLaboral().trim());
    }
}
