/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lissa.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import lissa.be.MedicoDerivaAtiende;
import lissa.bl.MedicoDerivaAtiendeBl;
import lissa.table.ModeloMedicoDerivaAtiende;
import lissa.util.Mensajes;
import lissa.util.Utilitarios;

/**
 *
 * @author JORGE
 */
public class JIF_PagoMedicos extends javax.swing.JInternalFrame {

    private JF_Principal root;

    private ModeloMedicoDerivaAtiende oModeloMedicoDerivaAtiende;
    private MedicoDerivaAtiende oMedicoDerivaAtiende;
    private MedicoDerivaAtiende oMedicoDerivaAtiendeTemp;
    private MedicoDerivaAtiendeBl oMedicoDerivaAtiendeBl;
    private ArrayList<MedicoDerivaAtiende> listMDA;

    /**
     * Creates new form JIF_PagoMedicos
     */
    public JIF_PagoMedicos(JF_Principal root) {
        initComponents();
        this.root = root;
        oModeloMedicoDerivaAtiende = new ModeloMedicoDerivaAtiende();
        tblResultados.setModel(oModeloMedicoDerivaAtiende);
        personalizaVistaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        cbxMedico = new javax.swing.JComboBox();
        jdcFechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdcFechaHasta = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pago Médicos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago a médico"));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblResultadosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Tipo atención: ");

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/next.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        cbxMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<seleccione>", "DERIVA", "ATIENDE" }));
        cbxMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Desde :");

        jLabel4.setText("Hasta :");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPagar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1))
                    .addComponent(jdcFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (isDatosValidos2()) {
            buscarPagoMedicos();
            resetPaintComponent();
        } else {
            Mensajes.msjValidarIngreso();
            paintComponents();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblResultadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosMouseReleased
        if (tblResultados.getRowSelectionAllowed() && tblResultados.getSelectedRow() != -1) {
            obtenerDatosTabla();
        }
    }//GEN-LAST:event_tblResultadosMouseReleased

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        configuraPagar();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void cbxMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox cbxMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaDesde;
    private com.toedter.calendar.JDateChooser jdcFechaHasta;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables

    private void buscarPagoMedicos() {
        oMedicoDerivaAtiendeBl = new MedicoDerivaAtiendeBl();
        oModeloMedicoDerivaAtiende.clear();
        listMDA = oMedicoDerivaAtiendeBl.listar(jdcFechaDesde.getDate(), jdcFechaHasta.getDate(), cbxMedico.getSelectedItem().toString().trim());
        if (!listMDA.isEmpty()) {
            oModeloMedicoDerivaAtiende.addAll(listMDA);
        }
        personalizaVistaTabla();
    }

    private void personalizaVistaTabla() {
        Utilitarios.formateaColumna(0, tblResultados, 50);
        Utilitarios.formateaColumna(1, tblResultados, 60);
        Utilitarios.formateaColumna(2, tblResultados, 50);
        Utilitarios.formateaColumna(5, tblResultados, 60);
        Utilitarios.formateaColumna(6, tblResultados, 60);
        Utilitarios.alinearDatosColumnaTablaDerecha(5, tblResultados);
    }

    private boolean isDatosValidos() {
        return (tblResultados.getRowSelectionAllowed()
                && tblResultados.getSelectedRow() != -1);
    }

    private void configuraPagar() {
        if (isDatosValidos()) {
            if (oMedicoDerivaAtiende.getEstadoPago().equals("PAGADO")) {
                JOptionPane.showMessageDialog(null, "Ya esta pagado", "Atención", JOptionPane.ERROR_MESSAGE);
            }else{
                actulizar();
            }
        } else {
            Mensajes.tblSelected();
        }
    }

    private void actulizar() {
        int res = actualizarPago();
        if (res == 1) {
            Mensajes.msjActCorrecta();
        } else {
            Mensajes.msjActErronea();
        }
        buscarPagoMedicos();
    }

    private int actualizarPago() {
        oMedicoDerivaAtiendeBl = new MedicoDerivaAtiendeBl();
        oMedicoDerivaAtiendeTemp = new MedicoDerivaAtiende();
//        oMedicoDerivaAtiendeTemp = oMedicoDerivaAtiende;
//        oMedicoDerivaAtiende = null;
        oMedicoDerivaAtiendeTemp.setIdmedicoderivaatiende(oMedicoDerivaAtiende.getIdmedicoderivaatiende());
        oMedicoDerivaAtiendeTemp.setItemsComprobante(oMedicoDerivaAtiende.getItemsComprobante());
        oMedicoDerivaAtiendeTemp.setMedico(oMedicoDerivaAtiende.getMedico());
        oMedicoDerivaAtiendeTemp.setMonto(oMedicoDerivaAtiende.getMonto());
        oMedicoDerivaAtiendeTemp.setEstadoPago("PAGADO");
        oMedicoDerivaAtiendeTemp.setTipoMedico(oMedicoDerivaAtiende.getTipoMedico());
        oMedicoDerivaAtiendeTemp.setIdCajaafecto(oMedicoDerivaAtiende.getIdCajaafecto());
        //oMedicoDerivaAtiende = null;
        return oMedicoDerivaAtiendeBl.actualizarTemp(oMedicoDerivaAtiendeTemp);
    }

    private void obtenerDatosTabla() {
        oMedicoDerivaAtiende = oModeloMedicoDerivaAtiende.get(tblResultados.getSelectedRow());
    }

    private boolean isDatosValidos2() {
        return (cbxMedico.getSelectedIndex() > 0
                && jdcFechaDesde.getDate() != null
                && jdcFechaHasta.getDate() != null);
    }

    private void paintComponents() {
        Utilitarios.paintCbxVacio(cbxMedico);
        Utilitarios.paintJdcVacio(jdcFechaDesde);
        Utilitarios.paintJdcVacio(jdcFechaHasta);
    }

    private void resetPaintComponent() {
        Utilitarios.resetPaintCbx(cbxMedico);
        Utilitarios.resetPaintJdc(jdcFechaDesde);
        Utilitarios.resetPaintJdc(jdcFechaHasta);
    }

    void inicializar() {
        cbxMedico.setSelectedIndex(1);
        Utilitarios.fechaActual(jdcFechaDesde);
        Utilitarios.fechaActual(jdcFechaHasta);
        buscarPagoMedicos();
        personalizaVistaTabla();
    }

}
